import test,{beforeEach} from 'node:test';import assert from 'node:assert/strict';import {getAssignedCurriculumOutline} from '../src/services/assignedCurriculumOutline.js';
const storage=new Map();globalThis.localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,String(value))};globalThis.window={dispatchEvent(){}};globalThis.CustomEvent??=class{constructor(type){this.type=type;}};
const ctx={personId:'outline-learner',workspaceId:'outline-learner:student',role:'student',locale:'en'};
const objective=(id,position=0,version='1')=>({conceptId:id,title:'Objective '+id,status:'reviewed',locale:'en',selection:{board:'Fictional framework',classLevel:'6',subject:'Mathematics'},provenance:{provider:'Fictional provider',sourceId:'Source section',version},sourceChapter:{id:'chapter',title:'Fractions',sourceSection:'Pages 1–4',position:0},objectivePosition:position,explanation:'PRIVATE_EXPLANATION_NOT_IN_OUTLINE',representations:[],criteria:[{id:'criterion',label:'Explain',prompt:'PRIVATE_RUBRIC_PROMPT'}]});
beforeEach(()=>{storage.clear();const user={id:ctx.personId,email:'learner@outline.test',identity:'student',full_name:'Fictional learner',age_band:'adult',roles:['student'],onboarding_complete:true};const empty={conversations:[],sessions:[],artifacts:[],resources:[],notifications:[],audit:[],preferences:{locale:'en',interfaceLocale:'en',voice:false,memory:true},subscription:{plan:'Free',state:'active',invoices:[],usage:0,usageDay:new Date().toISOString().slice(0,10)},legacyImported:false};storage.set('visionary_users',JSON.stringify([user]));storage.set('visionary_sessions',JSON.stringify([{token:'outline',userId:user.id,email:user.email,expiresAt:Date.now()+86400000}]));storage.set('visionary_session_token','outline');storage.set('visionary_workspace_v2',JSON.stringify({version:2,people:[{id:user.id,email:user.email,name:user.full_name,ageBand:'adult',roles:['student']}],workspaces:[{id:ctx.workspaceId,personId:user.id,role:'student',name:'Personal',lastPath:'/dashboard/classes'}],active:{[user.id]:ctx.workspaceId},relationships:[],data:{[ctx.workspaceId]:empty}}));storage.set('visionary_entity_Classroom',JSON.stringify([{id:'class',name:'Fictional class',teacher_email:'teacher@outline.test'},{id:'foreign',name:'PRIVATE_FOREIGN_CLASS',teacher_email:'other@outline.test'}]));storage.set('visionary_entity_Enrollment',JSON.stringify([{id:'enrollment',class_id:'class',student_email:user.email,status:'active'}]));storage.set('visionary_entity_Assignment',JSON.stringify([{id:'one',class_id:'class',title:'Assignment one',status:'published',objective_snapshot:objective('second',1)},{id:'two',class_id:'class',title:'Assignment two',status:'published',objective_snapshot:objective('first',0)},{id:'version-two',class_id:'class',title:'Assignment version two',status:'published',objective_snapshot:objective('first',0,'2')},{id:'unmapped',class_id:'class',title:'Written activity',status:'published'},{id:'foreign-assignment',class_id:'foreign',title:'PRIVATE_FOREIGN',status:'published',objective_snapshot:objective('foreign')} ]));storage.set('visionary_entity_Submission',JSON.stringify([{id:'submission',class_id:'class',assignment_id:'two',student_email:user.email,status:'graded',grade:75,text:'PRIVATE_RESPONSE',self_review:{criterion:'PRIVATE_REVIEW'}}]));});
test('assigned outline orders chapters/objectives, separates source versions and omits content/answers/grades',async()=>{
 const before=storage.get('visionary_workspace_v2'),result=await getAssignedCurriculumOutline(ctx,'class');assert.equal(result.chapters.length,2);assert.deepEqual(result.chapters[0].objectives.map(row=>row.title),['Objective first','Objective second']);assert.equal(result.chapters[0].objectives[0].state,'graded');assert.equal(result.chapters[1].source.version,'2');assert.equal(result.unmapped[0].title,'Written activity');assert.equal(result.assignedCount,4);assert.equal(storage.get('visionary_workspace_v2'),before);assert.doesNotMatch(JSON.stringify(result),/PRIVATE_|grade":|answerIndex|explanation|criteria/);assert.equal(result.chapters[0].objectives[0].href,'/dashboard/learn?assignment=two');
});
test('malformed and ambiguous assigned sources are partial without overwriting originals',async()=>{
 const rows=JSON.parse(storage.get('visionary_entity_Assignment'));rows[1].objective_snapshot.sourceChapter.title={invalid:true};rows.push({...rows[0]});storage.set('visionary_entity_Assignment',JSON.stringify(rows));const before=storage.get('visionary_entity_Assignment');const result=await getAssignedCurriculumOutline(ctx,'class');assert.equal(result.unavailableCount,3);assert.equal(result.chapters.length,1);assert.equal(result.chapters[0].source.version,'2');assert.equal(storage.get('visionary_entity_Assignment'),before);
});
test('foreign class, closed enrollment and wrong role cannot read the outline',async()=>{
 await assert.rejects(getAssignedCurriculumOutline(ctx,'foreign'),/no longer connected/);await assert.rejects(getAssignedCurriculumOutline({...ctx,role:'parent'},'class'),/access|learning workspace/);storage.set('visionary_entity_Enrollment',JSON.stringify([{id:'enrollment',class_id:'class',student_email:'learner@outline.test',status:'left'}]));await assert.rejects(getAssignedCurriculumOutline(ctx,'class'),/no longer connected/);
});
