import test,{beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {seedDemo,configureMock,workspaceIdentity} from '../src/services/workspaceService.ts';
import {configureContentRepository,getContentRepository} from '../src/services/contentRepository.ts';
import {selectLearningSyllabus,startLearningUnit,getLearningUnit,requestUnitTeaching,updateLearningLanguage} from '../src/services/learningPipelineService.ts';
import {proposeStageTransition,postponeStageTransition,configureStageTransitionClock} from '../src/services/stageTransitionService.ts';
import {getCurriculumBridge,requireBridgeObjective,startReviewedBridgeObjective} from '../src/services/curriculumBridgeService.ts';
const memory=new Map();globalThis.localStorage={getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,String(value)),removeItem:key=>memory.delete(key)};globalThis.window={dispatchEvent(){}};globalThis.CustomEvent??=class{constructor(type){this.type=type;}};
const ctx={personId:'demo-adult',workspaceId:'demo-adult:student',role:'student',locale:'en'};
const selection={board:'Reviewed fixture',classLevel:'6',subject:'Mathematics'},next={...selection,classLevel:'7'},source={provider:'Reviewed fixture only',sourceId:'math:6',version:'1'};
function graph(level){const prefix='fixture:'+level;const ids=level==='6'?['old-a','old-b','old-c']:['new-a','new-b'];return {syllabus:{...selection,classLevel:level,id:prefix,status:'official',contentLocale:'en',availableLocales:['en'],provenance:level==='6'?source:{...source,sourceId:'math:7'},textbooks:[{id:prefix+':book',title:'Fictional source',chapterIds:[prefix+':chapter']}],chapters:[{id:prefix+':chapter',title:'Source chapter',textbookId:prefix+':book',topicIds:[prefix+':topic'],status:'official'}]},topics:[{id:prefix+':topic',title:'Source topic',chapterId:prefix+':chapter',conceptIds:ids,status:'official'}],concepts:ids.map(id=>({id,title:id,topicId:prefix+':topic',prerequisiteIds:id==='new-b'?['new-a']:[],status:'official',representations:[],locale:'en',availableLocales:['en']}))};}
const mapping=(id,to)=>({fromConceptId:id,fromSelection:selection,fromSource:source,disposition:to?'equivalent':'archive',...(to?{toConceptId:to}:{}),reason:to?'Reviewed one-to-one objective continuity':'Removed from this source; original work remains available',reviewedBy:'fixture-reviewer',reviewedAt:'2026-10-01T00:00:00Z'});
beforeEach(()=>{memory.clear();configureMock({latency:0,fault:'none'});configureStageTransitionClock(()=>new Date('2026-10-01T12:00:00Z'));seedDemo('adult');configureContentRepository(null);});
async function setup(){configureContentRepository({async getSyllabus(query){return graph(query.classLevel);}});await selectLearningSyllabus(ctx,selection);proposeStageTransition(ctx,{...selection,subjects:['Mathematics']},'Source profile');const units=await Promise.all(['old-a','old-b','old-c'].map(id=>startLearningUnit(ctx,id)));const transition=proposeStageTransition(ctx,{classLevel:'7'},'Next profile');const target=graph('7');target.continuityMappings=[mapping('old-a','new-a'),mapping('old-b')];configureContentRepository({async getSyllabus(){return target;}});await getContentRepository(ctx).getSyllabus(next.board,next.classLevel,next.subject);return{units,transition,target};}
test('versioned equivalent/archive/unresolved mappings preserve original activities, evidence and due stores',async()=>{const {units,transition}=await setup();const before=memory.get('visionary_learning_pipeline_v1'),evidence=memory.get('visionary_mentor_v1');const plan=getCurriculumBridge(ctx,transition.id);assert.deepEqual(plan.rows.map(row=>row.status),['equivalent','archive','unresolved']);assert.equal(plan.targets.find(item=>item.id==='new-b').prerequisites[0].title,'new-a');assert.equal(plan.targets.find(item=>item.id==='new-b').prerequisites[0].priorReadiness,false);assert.equal(plan.mappingCount,1);assert.equal(memory.get('visionary_learning_pipeline_v1'),before);assert.equal(memory.get('visionary_mentor_v1'),evidence);assert.equal(requireBridgeObjective(ctx,transition.id,'new-a').id,'new-a');const oldClass=JSON.parse(memory.get('visionary_mentor_v1')).spaces[ctx.workspaceId].events.at(-1).class;const newUnit=await startLearningUnit(ctx,'new-a');assert.equal(newUnit.sourceContext.selection.classLevel,'7');assert.notEqual(JSON.parse(memory.get('visionary_mentor_v1')).spaces[ctx.workspaceId].events.at(-1).class,oldClass);assert.equal(getCurriculumBridge(ctx,transition.id).rows.find(row=>row.unitId===newUnit.id).status,'current');assert.equal(getLearningUnit(ctx,units[0].id).sourceContext.selection.classLevel,'6');postponeStageTransition(ctx,transition.id);assert.equal(getCurriculumBridge(ctx,transition.id).canStart,false);assert.throws(()=>requireBridgeObjective(ctx,transition.id,'new-a'),/unavailable/);assert.equal(workspaceIdentity(ctx).person.learningContext.classLevel,'6');});
test('mapping declarations reject ambiguity and incomplete review before replacing cached content',async()=>{const {target}=await setup();const before=memory.get('visionary_content_v1');for(const mappings of [[mapping('old-a','missing')],[{...mapping('old-a','new-a'),reviewedAt:'bad'}],[{...mapping('old-a','new-a'),reason:''}],[mapping('old-a','new-a'),mapping('old-c','new-a')],[mapping('old-a','new-a'),mapping('old-a')]]){configureContentRepository({async getSyllabus(){return{...target,continuityMappings:mappings};}});await assert.rejects(getContentRepository(ctx).getSyllabus(next.board,next.classLevel,next.subject),/mapping/);assert.equal(memory.get('visionary_content_v1'),before);}});
test('unknown legacy origins, wrong versions, absent languages and other owners remain unresolved',async()=>{const {transition,target}=await setup();const db=JSON.parse(memory.get('visionary_learning_pipeline_v1'));delete db.spaces[ctx.workspaceId].units[2].sourceContext;memory.set('visionary_learning_pipeline_v1',JSON.stringify(db));target.continuityMappings[0].fromSource={...source,version:'2'};configureContentRepository({async getSyllabus(){return target;}});await getContentRepository(ctx).getSyllabus(next.board,next.classLevel,next.subject);const plan=getCurriculumBridge(ctx,transition.id);assert.equal(plan.rows[0].status,'unresolved');assert.match(plan.rows[2].reason,/older activity/);assert.equal(getCurriculumBridge({...ctx,locale:'hi'},transition.id).targets.length,0);assert.throws(()=>getCurriculumBridge({...ctx,personId:'demo-bengali',workspaceId:'demo-bengali:student'},transition.id),/unavailable/);});

test('changed source versions do not replace a pinned activity explanation or language',async()=>{const {units}=await setup();const changed=graph('6');changed.syllabus.provenance={...source,version:'2'};configureContentRepository({async getSyllabus(){return changed;}});await getContentRepository(ctx).getSyllabus(selection.board,selection.classLevel,selection.subject);const before=memory.get('visionary_learning_pipeline_v1');await assert.rejects(requestUnitTeaching(ctx,units[0].id,'explanation'),/source version/);await assert.rejects(updateLearningLanguage(ctx,units[0].id,'hi'),/source version/);assert.equal(memory.get('visionary_learning_pipeline_v1'),before);const replacement=await startLearningUnit(ctx,units[0].conceptId);assert.notEqual(replacement.id,units[0].id);assert.equal(replacement.sourceContext.provenance.version,'2');assert.equal(getLearningUnit(ctx,units[0].id).sourceContext.provenance.version,'1');});

test('explicit bridge starts fresh on new source and retries resume without transferring original answers',async()=>{
 const {units,transition}=await setup();const original=getLearningUnit(ctx,units[0].id);
 const nextUnit=await startReviewedBridgeObjective(ctx,transition.id,'new-a');assert.equal(nextUnit.stage,'explain');assert.equal(nextUnit.checkPassed,false);assert.equal(nextUnit.attempts,undefined);assert.equal(nextUnit.sourceContext.selection.classLevel,'7');
 assert.equal((await startReviewedBridgeObjective(ctx,transition.id,'new-a')).id,nextUnit.id);assert.deepEqual(getLearningUnit(ctx,units[0].id),original);
});
test('postponement or cancellation during async bridge opening prevents persistence',async()=>{
 const {transition}=await setup();const before=memory.get('visionary_learning_pipeline_v1');
 const pending=startReviewedBridgeObjective(ctx,transition.id,'new-a');postponeStageTransition(ctx,transition.id);await assert.rejects(pending,/unavailable/);assert.equal(memory.get('visionary_learning_pipeline_v1'),before);
});
test('aborted bridge opening retains all original learning bytes',async()=>{
 const fresh=await setup();const before=memory.get('visionary_learning_pipeline_v1');const controller=new AbortController();const cancelled=startReviewedBridgeObjective({...ctx,signal:controller.signal},fresh.transition.id,'new-a');controller.abort();await assert.rejects(cancelled,/Cancelled/);assert.equal(memory.get('visionary_learning_pipeline_v1'),before);
});
