import test,{beforeEach} from 'node:test';import assert from 'node:assert/strict';
import * as w from '../src/services/workspaceService.ts';import {assertCurriculumTemplate,curriculumObjectiveSnapshot} from '../src/services/curriculumTemplate.ts';
const storage=new Map();globalThis.localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,String(value))};globalThis.window={dispatchEvent(){}};globalThis.CustomEvent??=class{constructor(type){this.type=type;}};
const org={personId:'demo-school-admin',workspaceId:'demo-school-admin:organization',role:'organization',locale:'en'},reviewerPersonal={personId:'demo-company-admin',workspaceId:'demo-company-admin:organization',role:'organization',locale:'en'},teacherPersonal={personId:'demo-teacher',workspaceId:'demo-teacher:teacher',role:'teacher',locale:'en'};
const template=()=>({schemaVersion:1,selection:{board:'Fictional source framework',classLevel:'6',subject:'Mathematics'},provenance:{provider:'Fictional reviewed provider',sourceId:'book-fixture',version:'1'},chapters:[{id:'chapter-one',title:'Fractions',sourceSection:'Chapter 1, pages 1–4',objectives:[{id:'objective-one',title:'Locate a fraction',explanation:'Four of eight equal intervals locate one half.',prerequisiteIds:[],representations:[{id:'number-line',kind:'number-line',alternative:'Halfway between zero and one.',numberLine:{minimum:0,maximum:1,divisions:8,initial:4}}],criteria:[{id:'criterion-one',label:'Equal intervals',prompt:'Explain why the intervals are equal.'}]},{id:'objective-two',title:'Apply a fraction',explanation:'Use a fraction to describe a selected share.',prerequisiteIds:['objective-one'],representations:[],criteria:[{id:'criterion-two',label:'Explain the share',prompt:'Explain the whole and the selected part.'}]}]}]});
function work(personal,email,role){const invite=w.requestOrganizationInvite(org,email,role,'Fictional school',role==='organization'?'academic-admin':undefined);w.changeOrganizationInvite(personal,invite.id,'active');const space=w.bootstrapPerson({id:personal.personId,email,identity:role}).workspaces.find(row=>row.organizationId==='school-admin@visionary.test');return {...personal,workspaceId:space.id};}
beforeEach(()=>{storage.clear();w.configureMock({latency:0,fault:'none'});w.seedDemo('school-admin');});
test('unfinished structure saves privately but submission requires complete references, teaching and criteria',()=>{
 const value=template();value.chapters[0].objectives[0].criteria[0].prompt='';const saved=w.saveOrganizationContent(org,{title:'Curriculum structure',body:'Preparation notes',source:'Fictional source version 1',language:'en',kind:'curriculum',curriculumTemplate:value});const before=storage.get('visionary_workspace_v2');assert.throws(()=>w.changeOrganizationContent(org,saved.id,saved.contentReview.revision,'submit'),/incomplete/);assert.equal(storage.get('visionary_workspace_v2'),before);assert.equal(saved.curriculumTemplate.chapters[0].objectives[0].criteria[0].prompt,'');
});
test('cycles, duplicate identities, orphan prerequisites and invalid representations reject without replacing saved drafts',()=>{
 const saved=w.saveOrganizationContent(org,{title:'Curriculum structure',body:'Preparation notes',source:'Fictional source version 1',language:'en',kind:'curriculum',curriculumTemplate:template()});const before=storage.get('visionary_workspace_v2');for(const mutate of [value=>value.chapters[0].objectives[0].prerequisiteIds.push('objective-two'),value=>value.chapters[0].objectives[1].id='objective-one',value=>value.chapters[0].objectives[1].prerequisiteIds=['unknown'],value=>value.chapters[0].objectives[0].representations[0].numberLine.divisions=100]){const value=template();mutate(value);assert.throws(()=>w.saveOrganizationContent(org,{id:saved.id,title:saved.title,body:saved.body,source:'Source',language:'en',kind:'curriculum',curriculumTemplate:value},saved.contentReview.revision),/incomplete|inconsistent/);assert.equal(storage.get('visionary_workspace_v2'),before);}
});
test('reviewed delivery pins structure and distinct objective drafts through later edits, retry and revocation',()=>{
 const reviewer=work(reviewerPersonal,'company-admin@visionary.test','organization'),teacher=work(teacherPersonal,'teacher@visionary.test','teacher');const input={title:'Structured fractions',body:'Preparation notes',source:'Fictional source version 1',language:'en',kind:'curriculum',curriculumTemplate:template()};let item=w.saveOrganizationContent(org,input);w.changeOrganizationContent(org,item.id,item.contentReview.revision,'submit');assert.throws(()=>w.changeOrganizationContent(org,item.id,item.contentReview.revision,'approve','Checked',{source:true,accuracy:true,language:true}),/different/);w.changeOrganizationContent(reviewer,item.id,item.contentReview.revision,'approve','Source, teaching and language checked',{source:true,accuracy:true,language:true});const delivery=w.deliverOrganizationContent(reviewer,item.id,item.contentReview.revision,'teacher@visionary.test');assert.throws(()=>w.importOrganizationContent(teacher,delivery.id),/Choose an objective/);const first=w.importOrganizationContent(teacher,delivery.id,'objective-one'),second=w.importOrganizationContent(teacher,delivery.id,'objective-two');assert.notEqual(first.id,second.id);assert.equal(first.objectiveSnapshot.status,'reviewed');assert.equal(first.objectiveSnapshot.provenance.version,'1');assert.equal(first.objectiveSnapshot.representations[0].numberLine.initial,4);assert.equal(w.importOrganizationContent(teacher,delivery.id,'objective-one').id,first.id);assert.equal(first.status,'draft');assert.equal(w.snapshot(teacher).sessions.length,0);
 w.changeOrganizationContent(org,item.id,item.contentReview.revision,'revise');const changed=template();changed.provenance.version='2';changed.chapters[0].objectives[0].explanation='Revised teaching';item=w.saveOrganizationContent(org,{...input,id:item.id,curriculumTemplate:changed},item.contentReview.revision);assert.equal(item.contentReview.versions[0].curriculumTemplate.provenance.version,'1');assert.equal(w.teacherOrganizationContent(teacher)[0].curriculumTemplate.provenance.version,'1');assert.equal(w.snapshot(teacher).resources.find(row=>row.id===first.id).objectiveSnapshot.explanation,'Four of eight equal intervals locate one half.');const invite=w.organizationInvites(org).find(row=>row.email==='teacher@visionary.test');w.changeOrganizationInvite(org,invite.id,'revoked');assert.throws(()=>w.importOrganizationContent(teacher,delivery.id,'objective-one'),/active|unavailable/);
});
test('authored snapshots carry explicit reviewed status and source section; malformed types cannot masquerade as curriculum',()=>{
 const value=template();assertCurriculumTemplate(value,true);const snapshot=curriculumObjectiveSnapshot(value,'objective-one','bn');assert.equal(snapshot.locale,'bn');assert.equal(snapshot.status,'reviewed');assert.match(snapshot.provenance.sourceId,/pages 1/);assert.throws(()=>assertCurriculumTemplate({...value,chapters:'invalid'}),/incomplete/);assert.throws(()=>curriculumObjectiveSnapshot(value,'foreign','en'),/Choose/);
});
test('corrupted delivered curriculum is unavailable without rewriting the source or importing a partial objective',()=>{
 const reviewer=work(reviewerPersonal,'company-admin@visionary.test','organization'),teacher=work(teacherPersonal,'teacher@visionary.test','teacher');const item=w.saveOrganizationContent(org,{title:'Structured fractions',body:'Preparation notes',source:'Fictional source version 1',language:'en',kind:'curriculum',curriculumTemplate:template()});w.changeOrganizationContent(org,item.id,item.contentReview.revision,'submit');w.changeOrganizationContent(reviewer,item.id,item.contentReview.revision,'approve','Checked',{source:true,accuracy:true,language:true});const delivery=w.deliverOrganizationContent(reviewer,item.id,item.contentReview.revision,'teacher@visionary.test');const db=JSON.parse(storage.get('visionary_workspace_v2'));db.data[org.workspaceId].resources.find(row=>row.id===item.id).contentReview.deliveries.find(row=>row.id===delivery.id).curriculumTemplate.chapters='unreadable';storage.set('visionary_workspace_v2',JSON.stringify(db));const before=storage.get('visionary_workspace_v2');assert.throws(()=>w.teacherOrganizationContent(teacher),/incomplete/);assert.throws(()=>w.importOrganizationContent(teacher,delivery.id,'objective-one'),/incomplete/);assert.equal(storage.get('visionary_workspace_v2'),before);
 const snapshot=curriculumObjectiveSnapshot(template(),'objective-two','en');assert.deepEqual(snapshot.prerequisites,[{id:'objective-one',title:'Locate a fraction'}]);
});
