import test,{beforeEach} from 'node:test';import assert from 'node:assert/strict';
import * as w from '../src/services/workspaceService.ts';import {appClient} from '../src/api/appClient.js';import {assignReviewedLesson} from '../src/services/classroomService.js';import {getClassworkPractice,answerClassworkPractice,moveClassworkPractice} from '../src/services/classworkStudyService.js';
const storage=new Map();globalThis.localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,String(value)),removeItem:key=>storage.delete(key)};globalThis.window={dispatchEvent(){},location:{origin:'http://localhost',search:''}};globalThis.CustomEvent??=class{constructor(type){this.type=type;}};
const org={personId:'demo-school-admin',workspaceId:'demo-school-admin:organization',role:'organization',locale:'en'};
const template=()=>({schemaVersion:1,selection:{board:'Fictional framework',classLevel:'6',subject:'Mathematics'},provenance:{provider:'Fictional provider',sourceId:'book-fixture',version:'1'},chapters:[{id:'chapter',title:'Fractions',sourceSection:'Chapter 1, pages 1–4',objectives:[{id:'target',title:'Locate one half',explanation:'Four of eight equal intervals locate one half.',prerequisiteIds:[],representations:[],criteria:[{id:'equal',label:'Intervals',prompt:'Explain why four of eight intervals is one half.'}],practice:[{id:'practice',prompt:'Which fraction locates the midpoint?',options:['One quarter','One half','Three quarters','One whole'],answerIndex:1}]}]}]});
beforeEach(()=>{storage.clear();w.configureMock({latency:0,fault:'none'});w.seedDemo('school-admin');});
function grant(personId,email,role){const personal={personId,workspaceId:personId+':'+role,role,locale:'en'};const invite=w.requestOrganizationInvite(org,email,role,'Fictional school',role==='organization'?'academic-admin':undefined);w.changeOrganizationInvite(personal,invite.id,'active');const space=w.bootstrapPerson({id:personId,email,identity:role}).workspaces.find(row=>row.organizationId==='school-admin@visionary.test');const db=JSON.parse(storage.get('visionary_workspace_v2'));db.active[personId]=space.id;storage.set('visionary_workspace_v2',JSON.stringify(db));return {...personal,workspaceId:space.id};}
async function fixture(){const reviewer=grant('demo-company-admin','company-admin@visionary.test','organization'),teacher=grant('demo-teacher','teacher@visionary.test','teacher'),learner=grant('demo-adult','adult@visionary.test','student');const users=[{id:'demo-teacher',email:'teacher@visionary.test',identity:'teacher'},{id:'demo-adult',email:'adult@visionary.test',identity:'student'}].map(user=>({...user,roles:[user.identity],age_band:'adult',onboarding_complete:true}));storage.set('visionary_users',JSON.stringify(users));storage.set('visionary_sessions',JSON.stringify(users.map(user=>({token:user.id,userId:user.id,email:user.email,expiresAt:Date.now()+86400000}))));storage.set('visionary_session_token','demo-teacher');const input={title:'Reviewed fractions',body:'Explain the selected fraction.',source:'Fictional book version 1',language:'en',kind:'curriculum',curriculumTemplate:template()};const content=w.saveOrganizationContent(org,input);w.changeOrganizationContent(org,content.id,content.contentReview.revision,'submit');w.changeOrganizationContent(reviewer,content.id,content.contentReview.revision,'approve','Fictional source reviewed',{source:true,accuracy:true,language:true});const delivery=w.deliverOrganizationContent(reviewer,content.id,content.contentReview.revision,'teacher@visionary.test');const imported=w.importOrganizationContent(teacher,delivery.id,'target');const reviewed=w.saveResource(teacher,{...imported,status:'reviewed'});const classroom=await appClient.entities.Classroom.create({name:'Structured class',subject:'Mathematics',teacher_email:'teacher@visionary.test',teacher_id:'demo-teacher',organization_email:'school-admin@visionary.test',join_code:'STRUCTURE'});const assignment=await assignReviewedLesson(teacher,{resourceId:reviewed.id,classId:classroom.id});storage.set('visionary_session_token','demo-adult');await appClient.entities.Enrollment.create({class_id:classroom.id,student_email:'adult@visionary.test',student_id:'demo-adult',status:'active',join_code:'STRUCTURE'});return {reviewer,teacher,learner,content,delivery,assignment,input};}
test('reviewed assigned practice projects no keys and private attempts cannot create grades or mastery',async()=>{
 const {learner,assignment,teacher}=await fixture();const view=await getClassworkPractice(learner,assignment.id);assert.deepEqual(Object.keys(view.question).sort(),['id','options','prompt']);assert.equal(JSON.stringify(view.assignment).includes('answerIndex'),false);const evidence=storage.get('visionary_mentor_v1');const input={assignmentId:assignment.id,expectedRevision:view.revision,expectedQuestionRevision:view.questionRevision,expectedRound:view.study.round,index:1};const result=await answerClassworkPractice(learner,input);assert.equal(result.correct,true);assert.equal(result.study.attempts.length,1);assert.equal((await answerClassworkPractice(learner,input)).study.attempts.length,1);assert.equal(storage.get('visionary_entity_Submission'),undefined);assert.equal(storage.get('visionary_mentor_v1'),evidence);const next=await moveClassworkPractice(learner,{assignmentId:assignment.id,expectedRevision:result.revision,next:0});assert.equal(next.study.round,1);await assert.rejects(getClassworkPractice(teacher,assignment.id),/own learning workspace/);
});
test('changed source pointers and corrupted banks fail without grading or repairing stored originals',async()=>{
 const {learner,assignment,content,delivery}=await fixture();const view=await getClassworkPractice(learner,assignment.id);const assignments=JSON.parse(storage.get('visionary_entity_Assignment'));assignments[0].source_provenance.deliveryId='foreign-delivery';storage.set('visionary_entity_Assignment',JSON.stringify(assignments));await assert.rejects(getClassworkPractice(learner,assignment.id),/unavailable/);assert.equal(storage.get('visionary_classwork_study_v1:'+learner.personId),undefined);assignments[0].source_provenance.deliveryId=delivery.id;storage.set('visionary_entity_Assignment',JSON.stringify(assignments));const db=JSON.parse(storage.get('visionary_workspace_v2'));db.data[org.workspaceId].resources.find(row=>row.id===content.id).contentReview.deliveries[0].curriculumTemplate.chapters[0].objectives[0].practice[0].options=['same','same'];storage.set('visionary_workspace_v2',JSON.stringify(db));const before=storage.get('visionary_workspace_v2');await assert.rejects(answerClassworkPractice(learner,{assignmentId:assignment.id,expectedRevision:view.revision,expectedQuestionRevision:view.questionRevision,expectedRound:0,index:1}),/incomplete/);assert.equal(storage.get('visionary_workspace_v2'),before);assert.equal(storage.get('visionary_classwork_study_v1:'+learner.personId),undefined);
});
test('later curriculum edits do not replace delivered questions; stale keys and revoked access reject private grading',async()=>{
 const {learner,assignment,content,input}=await fixture();const original=await getClassworkPractice(learner,assignment.id);w.changeOrganizationContent(org,content.id,content.contentReview.revision,'revise');const changed=template();changed.provenance.version='2';changed.chapters[0].objectives[0].practice[0].prompt='Different revision prompt';w.saveOrganizationContent(org,{...input,id:content.id,curriculumTemplate:changed},content.contentReview.revision);assert.equal((await getClassworkPractice(learner,assignment.id)).question.prompt,original.question.prompt);const db=JSON.parse(storage.get('visionary_workspace_v2'));db.data[org.workspaceId].resources.find(row=>row.id===content.id).contentReview.deliveries[0].curriculumTemplate.chapters[0].objectives[0].practice[0].answerIndex=0;storage.set('visionary_workspace_v2',JSON.stringify(db));await assert.rejects(answerClassworkPractice(learner,{assignmentId:assignment.id,expectedRevision:original.revision,expectedQuestionRevision:original.questionRevision,expectedRound:0,index:1}),/question changed/);assert.equal(storage.get('visionary_classwork_study_v1:'+learner.personId),undefined);const invite=w.organizationInvites(org).find(row=>row.email==='adult@visionary.test');w.changeOrganizationInvite(org,invite.id,'revoked');await assert.rejects(getClassworkPractice(learner,assignment.id),/active|unavailable|changed/);
});
test('a draft bank keeps an unselected answer key; editorial submission rejects it without a write',()=>{
 const value=template();value.chapters[0].objectives[0].practice[0].answerIndex=-1;const content=w.saveOrganizationContent(org,{title:'Unfinished bank',body:'Preparation notes',source:'Fictional version 1',language:'en',kind:'curriculum',curriculumTemplate:value});const before=storage.get('visionary_workspace_v2');assert.equal(content.curriculumTemplate.chapters[0].objectives[0].practice[0].answerIndex,-1);assert.throws(()=>w.changeOrganizationContent(org,content.id,content.contentReview.revision,'submit'),/incomplete/);assert.equal(storage.get('visionary_workspace_v2'),before);
});
test('older reviewed assignment copies retain practice without inventing newly added chapter metadata',async()=>{
 const {learner,assignment}=await fixture();const rows=JSON.parse(storage.get('visionary_entity_Assignment'));delete rows[0].objective_snapshot.sourceChapter;delete rows[0].objective_snapshot.objectivePosition;storage.set('visionary_entity_Assignment',JSON.stringify(rows));const original=storage.get('visionary_entity_Assignment');const view=await getClassworkPractice(learner,assignment.id);assert.equal(view.question.prompt,'Which fraction locates the midpoint?');assert.equal(view.assignment.objective_snapshot.sourceChapter,undefined);assert.equal(storage.get('visionary_entity_Assignment'),original);
});
