import * as workspace from '../src/services/workspaceService.ts';
import { workspaceIdentity } from '../src/services/workspaceService.ts';
import * as pipeline from '../src/services/learningPipelineService.ts';
import { proposeStageTransition, undoStageTransition, configureStageTransitionClock } from '../src/services/stageTransitionService.ts';
import { SAMPLE_SELECTION } from '../src/services/contentRepository.ts';
const memory = new Map();
globalThis.localStorage = { getItem: k => memory.get(k) ?? null, setItem: (k, v) => memory.set(k, String(v)), removeItem: k => memory.delete(k) };
globalThis.window = { dispatchEvent() {} };
globalThis.crypto ??= { randomUUID: () => 'id-' + Math.random().toString(16).slice(2) };
const ctx = { personId: 'demo-adult', workspaceId: 'demo-adult:student', role: 'student', locale: 'en' };
workspace.seedDemo('adult');
await pipeline.selectLearningSyllabus(ctx, SAMPLE_SELECTION);
configureStageTransitionClock(() => new Date(Date.now() - 60000));
const transition = proposeStageTransition(ctx, { classLevel: '8' }, 'promotion');
console.log('appliedAt:', transition.appliedAt);
const unit = await pipeline.startLearningUnit(ctx, 'sample:cube:concept');
console.log('unit.updatedAt:', unit.updatedAt);
const undone = undoStageTransition(ctx, transition.id);
console.log('laterWorkCount:', undone.laterWorkCount);
console.log('string compare:', unit.updatedAt > transition.appliedAt);
