import test,{beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {appClient} from '../src/api/appClient.js';
import {bootstrapPerson,saveResource,resourceRevision,snapshot} from '../src/services/workspaceService.ts';
import {teacherObjectiveChoices,prepareTeacherObjective,assignReviewedLesson} from '../src/services/classroomService.js';
import {SAMPLE_SELECTION} from '../src/services/contentRepository.ts';
import {getClassworkActivity,classworkActivityRevision,submitClassworkActivity} from '../src/services/classworkPlayerService.js';
import {saveClassworkDraft,readClassworkDrafts} from '../src/services/classworkDraftService.js';
const memory=new Map();globalThis.localStorage={getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,String(value)),removeItem:key=>memory.delete(key)};globalThis.window={dispatchEvent(){},location:{origin:'http://localhost',search:''}};globalThis.CustomEvent??=class{constructor(type){this.type=type;}};
beforeEach(()=>memory.clear());const password='Objective-preview-123!';
async function account(role){const email=`${role}@objective.test`;await appClient.auth.register({email,password});await appClient.auth.verifyOtp({email});const user=await appClient.auth.updateMe({identity:role,onboarding_complete:true,age_band:'adult'});const state=bootstrapPerson(user);return {user,ctx:{personId:user.id,workspaceId:state.active,role,locale:'en'}};}
async function fixture(){const teacher=await account('teacher');const classroom=await appClient.entities.Classroom.create({name:'Objective class',subject:'Mathematics',teacher_id:teacher.user.id,teacher_email:teacher.user.email,join_code:'OBJECTIVE'});const loaded=await teacherObjectiveChoices(teacher.ctx,SAMPLE_SELECTION);const objective=await prepareTeacherObjective(teacher.ctx,{selection:SAMPLE_SELECTION,conceptId:'sample:cube:concept',expectedSource:JSON.stringify(loaded.syllabus.provenance)});const lesson=saveResource(teacher.ctx,{title:'Explain a cube',body:'Describe how the three side lengths determine volume.',kind:'lesson',status:'reviewed',audience:'Class',objectiveSnapshot:objective});return {teacher,classroom,loaded,objective,lesson};}
test('teacher attaches a sourced objective without answer keys and assigns an immutable learner visual copy',async()=>{
 const {teacher,classroom,objective,lesson}=await fixture();assert.equal(objective.locale,'en');assert.equal(objective.provenance.version,'2');assert.equal(objective.status,'sample');assert.ok(objective.representations.some(item=>item.kind==='cube'));assert.equal('check' in objective,false);assert.equal('practice' in objective,false);
 const assignment=await assignReviewedLesson(teacher.ctx,{resourceId:lesson.id,classId:classroom.id,expectedRevision:resourceRevision(lesson)});assert.deepEqual(assignment.objective_snapshot,objective);assert.equal((await assignReviewedLesson(teacher.ctx,{resourceId:lesson.id,classId:classroom.id,expectedRevision:resourceRevision(lesson)})).id,assignment.id);
 saveResource(teacher.ctx,{...lesson,body:'Later private preparation',objectiveSnapshot:null});assert.deepEqual((await appClient.entities.Assignment.get(assignment.id)).objective_snapshot,objective);
 const learner=await account('student');await appClient.entities.Enrollment.create({class_id:classroom.id,student_id:learner.user.id,student_email:learner.user.email,join_code:'OBJECTIVE',status:'active'});const view=await getClassworkActivity(learner.ctx,assignment.id);assert.equal(view.assignment.objective_snapshot.conceptId,objective.conceptId);assert.equal(snapshot(learner.ctx).sessions.length,0);
});
test('source and teacher context are rechecked and provisional or unavailable objectives do not attach',async()=>{
 const {teacher,loaded}=await fixture();const args={selection:SAMPLE_SELECTION,conceptId:'sample:cube:concept',expectedSource:JSON.stringify(loaded.syllabus.provenance)};
 await assert.rejects(prepareTeacherObjective(teacher.ctx,{...args,expectedSource:'stale'}),/source changed/);await assert.rejects(prepareTeacherObjective(teacher.ctx,{...args,conceptId:'outside'}),/loaded curriculum/);await assert.rejects(teacherObjectiveChoices(teacher.ctx,{board:'Unconnected',classLevel:'6',subject:'Missing subject'}),/No sourced curriculum/);
 const hindi=await teacherObjectiveChoices({...teacher.ctx,locale:'hi'},SAMPLE_SELECTION);const translated=await prepareTeacherObjective({...teacher.ctx,locale:'hi'},{...args,expectedSource:JSON.stringify(hindi.syllabus.provenance)});assert.equal(translated.locale,'hi');assert.notEqual(translated.explanation,(await prepareTeacherObjective(teacher.ctx,args)).explanation);
 await account('student');await assert.rejects(prepareTeacherObjective(teacher.ctx,args),/teacher workspace/);
});
test('same-clock lesson edits reject stale assignment and cannot replay a different saved objective',async()=>{
 const {teacher,classroom,lesson}=await fixture();const revision=resourceRevision(lesson);const first=await assignReviewedLesson(teacher.ctx,{resourceId:lesson.id,classId:classroom.id,expectedRevision:revision});const db=JSON.parse(memory.get('visionary_workspace_v2'));db.data[teacher.ctx.workspaceId].resources.find(row=>row.id===lesson.id).body='Different instructions at the same clock instant';memory.set('visionary_workspace_v2',JSON.stringify(db));
 await assert.rejects(assignReviewedLesson(teacher.ctx,{resourceId:lesson.id,classId:classroom.id,expectedVersion:lesson.updatedAt,expectedRevision:revision}),/changed before assignment/);const latest=snapshot(teacher.ctx).resources.find(row=>row.id===lesson.id);const second=await assignReviewedLesson(teacher.ctx,{resourceId:lesson.id,classId:classroom.id,expectedRevision:resourceRevision(latest)});assert.notEqual(first.id,second.id);assert.equal(first.description,lesson.body);assert.equal(second.description,latest.body);
});
test('malformed objective writes and visual drafts preserve originals; changed assignment objective rejects submission',async()=>{
 const {teacher,classroom,lesson,objective}=await fixture();const original=memory.get('visionary_workspace_v2');const bad=structuredClone(objective);bad.representations=[{id:'line',kind:'number-line',alternative:'Line',numberLine:{minimum:0,maximum:1,divisions:0,initial:0}}];assert.throws(()=>saveResource(teacher.ctx,{...lesson,objectiveSnapshot:bad}),/representation is incomplete/);assert.equal(memory.get('visionary_workspace_v2'),original);assert.throws(()=>saveResource(teacher.ctx,{...lesson,objectiveSnapshot:{...objective,answerIndex:0}}),/representation is incomplete/);assert.equal(memory.get('visionary_workspace_v2'),original);
 const assignment=await assignReviewedLesson(teacher.ctx,{resourceId:lesson.id,classId:classroom.id});const learner=await account('student');await appClient.entities.Enrollment.create({class_id:classroom.id,student_email:learner.user.email,student_id:learner.user.id,join_code:'OBJECTIVE',status:'active'});saveClassworkDraft(learner.ctx,assignment.id,{text:'Own response',objectiveRevision:JSON.stringify(objective),objectiveView:{mode:'model',size:5,rotation:90}},'null');const draftBytes=memory.get(`visionary_classwork_drafts_v1:${learner.user.id}`);assert.throws(()=>saveClassworkDraft(learner.ctx,assignment.id,{objectiveView:{size:100}}),/incomplete/);assert.equal(memory.get(`visionary_classwork_drafts_v1:${learner.user.id}`),draftBytes);assert.equal(readClassworkDrafts(learner.ctx)[assignment.id].objectiveView.size,5);
 const view=await getClassworkActivity(learner.ctx,assignment.id);const rows=JSON.parse(memory.get('visionary_entity_Assignment'));rows[0].objective_snapshot.explanation='Changed explanation';memory.set('visionary_entity_Assignment',JSON.stringify(rows));await assert.rejects(submitClassworkActivity(learner.ctx,{assignmentId:assignment.id,expectedRevision:classworkActivityRevision(view.assignment),text:'Own response',responses:[]}),/assigned content changed/);assert.equal((await appClient.entities.Submission.list()).length,0);
 rows[0].objective_snapshot=bad;memory.set('visionary_entity_Assignment',JSON.stringify(rows));const assignmentBytes=memory.get('visionary_entity_Assignment');await assert.rejects(getClassworkActivity(learner.ctx,assignment.id),/representation is incomplete/);assert.equal(memory.get('visionary_entity_Assignment'),assignmentBytes);
});
