import test,{beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import * as workspace from '../src/services/workspaceService.ts';
const storage=new Map();globalThis.localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,String(value))};globalThis.window={dispatchEvent(){}};globalThis.CustomEvent??=class{constructor(type){this.type=type;}};
beforeEach(()=>{storage.clear();workspace.configureMock({latency:0,fault:'none'});workspace.seedDemo('adult');const db=JSON.parse(storage.get('visionary_workspace_v2'));db.people.find(row=>row.id==='demo-adult').roles=['student'];db.workspaces=db.workspaces.filter(row=>row.personId!=='demo-adult'||row.role==='student');for(const key of Object.keys(db.data))if(key.startsWith('demo-adult:')&&key!=='demo-adult:student')delete db.data[key];storage.set('visionary_workspace_v2',JSON.stringify(db));});
test('role entry rejects unknown/prototype roles and adult-only roles for minors without changing records',()=>{
 const before=storage.get('visionary_workspace_v2');for(const role of ['unknown','toString','__proto__',null])assert.throws(()=>workspace.addRole('demo-adult',role),/available workspace role/);assert.equal(storage.get('visionary_workspace_v2'),before);workspace.seedDemo('minor-cbse');const minor=storage.get('visionary_workspace_v2');assert.throws(()=>workspace.addRole('demo-minor-cbse','teacher'),/adult age/);assert.equal(storage.get('visionary_workspace_v2'),minor);
});
test('failed role creation keeps original work; retry creates one separate workspace and existing retries need no write',()=>{
 const before=storage.get('visionary_workspace_v2');const set=localStorage.setItem;localStorage.setItem=()=>{throw Error('Fictional storage failure');};try{assert.throws(()=>workspace.addRole('demo-adult','teacher'),/save|storage/i);}finally{localStorage.setItem=set;}assert.equal(storage.get('visionary_workspace_v2'),before);const teacher=workspace.addRole('demo-adult','teacher');assert.equal(teacher.id,'demo-adult:teacher');const ctx={personId:'demo-adult',workspaceId:teacher.id,role:'teacher',locale:'en'};assert.equal(workspace.snapshot(ctx).resources.length,0);const saved=storage.get('visionary_workspace_v2');localStorage.setItem=()=>{throw Error('Should not write existing role');};try{assert.equal(workspace.addRole('demo-adult','teacher').id,teacher.id);}finally{localStorage.setItem=set;}assert.equal(storage.get('visionary_workspace_v2'),saved);const db=JSON.parse(saved);assert.equal(db.workspaces.filter(row=>row.id===teacher.id).length,1);assert.deepEqual(db.data['demo-adult:student'],JSON.parse(before).data['demo-adult:student']);
});
