import { teacherCopy } from './teacherCopy.js';
const entries = [
['Left','कक्षा छोड़ी','ক্লাস ছেড়েছে'],['Inactive','निष्क्रिय','নিষ্ক্রিয়'],['An enrollment record already exists for this student. Share the class code to reconnect.','विद्यार्थी का नामांकन रिकॉर्ड मौजूद है। फिर जुड़ने के लिए कक्षा कोड साझा करें।','শিক্ষার্থীর নথিভুক্তির রেকর্ড আছে। আবার সংযোগের জন্য ক্লাস কোড ভাগ করুন।'],
["Review and return submissions. Grades must be within the assignment’s point range. Edits are kept on this device until returned.","प्रस्तुत कार्य की समीक्षा करके लौटाएँ। अंक कार्य की सीमा में हों। लौटाने तक बदलाव इस डिवाइस पर रहते हैं।","জমা দেওয়া কাজ পর্যালোচনা করে ফেরত দিন। নম্বর কাজের সীমার মধ্যে হতে হবে। ফেরত দেওয়া পর্যন্ত সম্পাদনা এই ডিভাইসে থাকে।"],
["Saved lesson version:","सहेजा पाठ संस्करण:","সংরক্ষিত পাঠ সংস্করণ:"],
["Export current review edits","वर्तमान समीक्षा बदलाव निर्यात करें","বর্তমান পর্যালোচনার সম্পাদনা রপ্তানি করুন"],
["Discard edits and load latest reviews","बदलाव छोड़कर नवीनतम समीक्षा पढ़ें","সম্পাদনা বাদ দিয়ে সর্বশেষ পর্যালোচনা পড়ুন"],
["No submissions yet. They'll appear here as students turn in their work.","अभी कोई कार्य प्रस्तुत नहीं हुआ। विद्यार्थियों के प्रस्तुत करने पर यहाँ दिखेगा।","এখনও কাজ জমা হয়নি। শিক্ষার্থীরা জমা দিলে এখানে দেখা যাবে।"],
["Returned","लौटाया गया","ফেরত দেওয়া"],
["No submission text","प्रस्तुत उत्तर नहीं है","জমা দেওয়া উত্তর নেই"],
["Review the assigned criteria","सौंपे मानदंड की समीक्षा करें","নির্ধারিত মানদণ্ড পর্যালোচনা করুন"],
["Returning a grade requires a rating and note for each criterion. Revision requests may address selected criteria.","अंक लौटाने के लिए हर मानदंड की रेटिंग और टिप्पणी चाहिए। संशोधन में चुने मानदंड ले सकते हैं।","নম্বর ফেরাতে প্রতি মানদণ্ডের রেটিং ও নোট চাই। সংশোধনে নির্বাচিত মানদণ্ড থাকতে পারে।"],
["Choose a rating","रेटिंग चुनें","রেটিং বাছুন"],
["Met","पूरा हुआ","পূরণ হয়েছে"],
["Needs work","सुधार चाहिए","উন্নতি দরকার"],
["Not assessed","मूल्यांकन नहीं हुआ","মূল্যায়িত হয়নি"],
["Grade","अंक","নম্বর"],
["Feedback (required for revision)","प्रतिक्रिया (संशोधन के लिए आवश्यक)","প্রতিক্রিয়া (সংশোধনের জন্য প্রয়োজন)"],
["Return","लौटाएँ","ফেরত দিন"],
["Request revision","संशोधन माँगें","সংশোধন চাইুন"],
["Attempt {number}","प्रयास {number}","প্রচেষ্টা {number}"],
[" · Revision requested"," · संशोधन माँगा गया"," · সংশোধন চাওয়া হয়েছে"],
["Previous attempts and feedback ({count})","पिछले प्रयास और प्रतिक्रिया ({count})","আগের প্রচেষ্টা ও প্রতিক্রিয়া ({count})"],
["Feedback:","प्रतिक्रिया:","প্রতিক্রিয়া:"],
["Criterion rating: {criterion} for {name}","{name} के लिए {criterion} की रेटिंग","{name}-এর জন্য {criterion}-এর রেটিং"],
["Criterion note: {criterion} for {name}","{name} के लिए {criterion} की टिप्पणी","{name}-এর জন্য {criterion}-এর নোট"],
["Grade for {name}","{name} के अंक","{name}-এর নম্বর"],
["Feedback for {name}","{name} की प्रतिक्रिया","{name}-এর প্রতিক্রিয়া"],
["Submissions unavailable. Saved work has not been replaced.","प्रस्तुत कार्य अनुपलब्ध हैं। सहेजे कार्य बदले नहीं गए।","জমা দেওয়া কাজ অনুপলব্ধ। সংরক্ষিত কাজ বদলানো হয়নি।"],
["Write to the class community","कक्षा समुदाय में लिखें","ক্লাসের সম্প্রদায়ে লিখুন"],
["Share with your class","अपनी कक्षा से साझा करें","নিজের ক্লাসের সঙ্গে ভাগ করুন"],
["Share with your class community","कक्षा समुदाय से साझा करें","ক্লাসের সম্প্রদায়ের সঙ্গে ভাগ করুন"],
["Ask a question, share an idea, or help a classmate…","प्रश्न पूछें, विचार साझा करें या सहपाठी की सहायता करें…","প্রশ্ন করুন, ধারণা ভাগ করুন বা সহপাঠীকে সাহায্য করুন…"],
["Post","पोस्ट करें","পোস্ট করুন"],
["Visible to everyone in this class, including your teacher. Nothing here is public.","शिक्षक सहित इस कक्षा के सभी लोगों को दिखता है। यह सार्वजनिक नहीं है।","শিক্ষকসহ এই ক্লাসের সবাই দেখতে পায়। এখানে কিছুই সর্বজনীন নয়।"],
["Loading the community…","समुदाय पढ़ रहे हैं…","সম্প্রদায় পড়া হচ্ছে…"],
["No posts yet. Start the conversation — a question or an idea is enough.","अभी कोई पोस्ट नहीं है। प्रश्न या विचार से बातचीत शुरू करें।","এখনও পোস্ট নেই। প্রশ্ন বা ধারণা দিয়ে কথোপকথন শুরু করুন।"],
["Community posts","समुदाय के पोस्ट","সম্প্রদায়ের পোস্ট"],
["Learner","शिक्षार्थी","শিক্ষার্থী"],
["A learner reported this post.","एक शिक्षार्थी ने इस पोस्ट की शिकायत की है।","এক শিক্ষার্থী এই পোস্টের অভিযোগ করেছে।"],
["Remove","हटाएँ","সরান"],
["Report","शिकायत करें","অভিযোগ করুন"],
["Remove post by {name}","{name} का पोस्ट हटाएँ","{name}-এর পোস্ট সরান"],
["Restore reported post by {name}","{name} का शिकायत किया पोस्ट वापस लाएँ","{name}-এর অভিযোগ করা পোস্ট ফেরান"],
["Report post by {name}","{name} के पोस्ट की शिकायत करें","{name}-এর পোস্টের অভিযোগ করুন"],
 ["Create assignments and return feedback to your students.","कार्य बनाएँ और विद्यार्थियों को प्रतिक्रिया लौटाएँ।","কাজ তৈরি করে শিক্ষার্থীদের প্রতিক্রিয়া ফেরত দিন।"],
 ["Create assignment","कार्य बनाएँ","কাজ তৈরি করুন"],
 ["New assignment","नया कार्य","নতুন কাজ"],
 ["Title","शीर्षक","শিরোনাম"],
 ["Assignment title","कार्य का शीर्षक","কাজের শিরোনাম"],
 ["Assignment instructions","कार्य के निर्देश","কাজের নির্দেশনা"],
 ["Instructions (optional)","निर्देश (वैकल्पिक)","নির্দেশনা (ঐচ্ছিক)"],
 ["Concepts (optional)","अवधारणाएँ (वैकल्पिक)","ধারণা (ঐচ্ছিক)"],
 ["e.g. Quadratic equations","जैसे द्विघात समीकरण","যেমন দ্বিঘাত সমীকরণ"],
 ["Add","जोड़ें","যোগ করুন"],
 ["Assign","सौंपें","দিন"],
 ["Review","समीक्षा करें","পর্যালোচনা করুন"],
 ["Review ({count}{newCount})","समीक्षा ({count}{newCount})","পর্যালোচনা ({count}{newCount})"],
 [" · {count} new"," · {count} नए"," · {count}টি নতুন"],
 ["{points} points{due}","{points} अंक{due}","{points} নম্বর{due}"],
 [" · Due {date}"," · अंतिम तिथि {date}"," · শেষ তারিখ {date}"],
 ["Remove {topic}","{topic} हटाएँ","{topic} সরান"],
 ["Actions for {title}","{title} के विकल्प","{title}-এর বিকল্প"],
 ["Publication time (optional)","प्रकाशन का समय (वैकल्पिक)","প্রকাশের সময় (ঐচ্ছিক)"],
 ["Publication time","प्रकाशन का समय","প্রকাশের সময়"],
 ["Shown in your device timezone. Scheduled preview access uses the browser clock; no external notification is sent.","डिवाइस के समय क्षेत्र में दिखता है। निर्धारित पूर्वावलोकन ब्राउज़र घड़ी से चलता है; बाहरी सूचना नहीं भेजी जाती।","ডিভাইসের সময় অঞ্চলে দেখানো হয়। নির্ধারিত প্রিভিউ ব্রাউজারের ঘড়ি ব্যবহার করে; বাইরে বিজ্ঞপ্তি পাঠানো হয় না।"],
 ["Schedule assignment","कार्य निर्धारित करें","কাজের সময় নির্ধারণ করুন"],
 ["No assignments yet. Create your first one and tag the concepts it covers.","अभी कोई कार्य नहीं है। पहला कार्य बनाकर अवधारणाएँ जोड़ें।","এখনও কাজ নেই। প্রথম কাজ তৈরি করে ধারণা যোগ করুন।"],
 ["Retry classwork loading","कक्षा कार्य फिर पढ़ें","ক্লাসের কাজ আবার পড়ুন"],
 ["We couldn’t load classwork. Saved assignments and feedback have not been replaced.","कक्षा कार्य पढ़ा नहीं जा सका। सहेजे कार्य और प्रतिक्रिया बदले नहीं गए।","ক্লাসের কাজ পড়া যায়নি। সংরক্ষিত কাজ ও প্রতিক্রিয়া বদলানো হয়নি।"],
 ["Your assignment wasn’t saved. Please try again.","कार्य सहेजा नहीं गया। फिर प्रयास करें।","কাজ সংরক্ষণ হয়নি। আবার চেষ্টা করুন।"],
 ["Choose a future publication date and time.","भविष्य की प्रकाशन तिथि और समय चुनें।","ভবিষ্যতের প্রকাশের তারিখ ও সময় বাছুন।"],
 ["The due date must be on or after publication.","अंतिम तिथि प्रकाशन के दिन या बाद में होनी चाहिए।","শেষ তারিখ প্রকাশের দিন বা তার পরে হতে হবে।"],
 ["Choose a point total between 1 and 10,000.","कुल अंक 1 से 10,000 के बीच चुनें।","মোট নম্বর 1 থেকে 10,000-এর মধ্যে বাছুন।"],
 ["Draft · visible only to your teacher workspace","ड्राफ़्ट · केवल आपके शिक्षण कार्यक्षेत्र में दिखता है","খসড়া · শুধু আপনার শিক্ষাদানের কর্মক্ষেত্রে দৃশ্যমান"],
 ["Scheduled publication · browser-local preview","निर्धारित प्रकाशन · ब्राउज़र में स्थानीय पूर्वावलोकन","নির্ধারিত প্রকাশ · ব্রাউজারে স্থানীয় প্রিভিউ"],
 ["Published · accepting responses","प्रकाशित · उत्तर स्वीकार हो रहे हैं","প্রকাশিত · উত্তর গ্রহণ করা হচ্ছে"],
 ["Closed · saved work and reviews retained","बंद · सहेजे कार्य और समीक्षाएँ सुरक्षित हैं","বন্ধ · সংরক্ষিত কাজ ও পর্যালোচনা রাখা হয়েছে"],
 ["Archived · prior submitters retain their work","संग्रह में · पहले उत्तर देने वालों के कार्य सुरक्षित हैं","আর্কাইভ করা · আগে জমা দেওয়া শিক্ষার্থীদের কাজ রাখা হয়েছে"],
 ["State unavailable","स्थिति अनुपलब्ध","অবস্থা অনুপলব্ধ"],
 ["Scheduled publication reached · accepting responses","निर्धारित प्रकाशन शुरू · उत्तर स्वीकार हो रहे हैं","নির্ধারিত প্রকাশ শুরু · উত্তর গ্রহণ করা হচ্ছে"],
 ["Scheduled · {date} · hidden until publication","निर्धारित · {date} · प्रकाशन तक नहीं दिखेगा","নির্ধারিত · {date} · প্রকাশ পর্যন্ত লুকানো"],
 ["Publish assignment","कार्य प्रकाशित करें","কাজ প্রকাশ করুন"],
 ["Reopen submissions","उत्तर फिर स्वीकार करें","উত্তর আবার গ্রহণ করুন"],
 ["Publish now","अभी प्रकाशित करें","এখন প্রকাশ করুন"],
 ["Cancel schedule to draft","समय रद्द करके ड्राफ़्ट करें","সময় বাতিল করে খসড়া করুন"],
 ["Close submissions","उत्तर स्वीकार करना बंद करें","উত্তর গ্রহণ বন্ধ করুন"],
 ["Archive assignment","कार्य संग्रह में रखें","কাজ আর্কাইভ করুন"],
 ["Restore as closed","बंद स्थिति में वापस लाएँ","বন্ধ অবস্থায় ফেরান"],
 ["Assignment state history","कार्य की स्थिति का इतिहास","কাজের অবস্থার ইতিহাস"],
 ["Record class promotion","कक्षा परिवर्तन दर्ज करें","ক্লাস পরিবর্তন নথিভুক্ত করুন"],
 ["Adjacent class changes apply to actively enrolled learners. Anyone already in that class or needing a larger change keeps their current stage.","अगली कक्षा का बदलाव सक्रिय शिक्षार्थियों पर लागू होता है। उस कक्षा में पहले से मौजूद या बड़े बदलाव की आवश्यकता वाले अपने चरण में रहते हैं।","পরের ক্লাসের পরিবর্তন সক্রিয় শিক্ষার্থীদের জন্য। ইতিমধ্যে সেই ক্লাসে থাকা বা বড় পরিবর্তন প্রয়োজন হলে বর্তমান ধাপ বজায় থাকে।"],
 ["Moving to class","अगली कक्षा","পরের ক্লাস"],
 ["Next class level","अगली कक्षा का स्तर","পরের ক্লাসের স্তর"],
 ["Reason (shared with learners)","कारण (शिक्षार्थियों से साझा)","কারণ (শিক্ষার্থীদের সঙ্গে ভাগ করা)"],
 ["End of year promotion","वर्ष के अंत में कक्षा परिवर्तन","বছরের শেষে ক্লাস পরিবর্তন"],
 ["Promotion reason","कक्षा परिवर्तन का कारण","ক্লাস পরিবর্তনের কারণ"],
 ["Recording…","दर्ज कर रहे हैं…","নথিভুক্ত করা হচ্ছে…"],
 ["Record promotion","परिवर्तन दर्ज करें","পরিবর্তন নথিভুক্ত করুন"],
 ["{count} learners moved to class {level}.","{count} शिक्षार्थी कक्षा {level} में गए।","{count}জন শিক্ষার্থী ক্লাস {level}-এ গেছে।"],
 ["{count} already in class {level}.","{count} पहले से कक्षा {level} में हैं।","{count}জন ইতিমধ্যে ক্লাস {level}-এ আছে।"],
 ["{count} need individual review or learner confirmation; their stage was not changed.","{count} को व्यक्तिगत समीक्षा या पुष्टि चाहिए; चरण बदला नहीं गया।","{count}জনের ব্যক্তিগত পর্যালোচনা বা নিশ্চিতকরণ দরকার; ধাপ বদলানো হয়নি।"],
 ["Promoted learners can postpone or undo this on their own Home.","शिक्षार्थी अपने होम से बदलाव टाल या वापस कर सकते हैं।","শিক্ষার্থীরা নিজের হোম থেকে পরিবর্তন পিছিয়ে দিতে বা ফেরাতে পারে।"],
 ['AI class analysis','कक्षा का AI विश्लेषण','ক্লাসের AI বিশ্লেষণ'],
 ['AI analysis is not connected yet. The coverage and assessment summaries below use your recorded classwork.','AI विश्लेषण अभी जुड़ा नहीं है। नीचे के सारांश दर्ज कक्षा कार्य से बनते हैं।','AI বিশ্লেষণ এখনও সংযুক্ত নয়। নিচের সারাংশ নথিভুক্ত ক্লাসের কাজ থেকে তৈরি হয়।'],
 ['Refresh class records','कक्षा के रिकॉर्ड फिर पढ़ें','ক্লাসের রেকর্ড আবার পড়ুন'],
 ['Class insights could not be loaded. Please try again.','कक्षा के अवलोकन पढ़े नहीं जा सके। फिर प्रयास करें।','ক্লাসের তথ্য পড়া যায়নি। আবার চেষ্টা করুন।'],
 ['Loading class records…','कक्षा के रिकॉर्ड पढ़ रहे हैं…','ক্লাসের রেকর্ড পড়া হচ্ছে…'],
 ['Concept assessment','अवधारणा का मूल्यांकन','ধারণার মূল্যায়ন'],
 ['Average scores from graded assignments, normalized to a percentage. A useful signal—not a complete measure of understanding.','मूल्यांकित कार्यों के औसत अंक, प्रतिशत में। यह उपयोगी संकेत है; समझ का पूरा माप नहीं।','মূল্যায়িত কাজের গড় নম্বর, শতাংশ হিসেবে। এটি কার্যকর ইঙ্গিত; বোঝাপড়ার সম্পূর্ণ মাপ নয়।'],
 ['No valid graded concept evidence yet. Tag concepts and return graded work to see recorded scores here.','अभी अवधारणाओं के मान्य मूल्यांकित रिकॉर्ड नहीं हैं। अवधारणाएँ जोड़ें और मूल्यांकित कार्य लौटाएँ।','এখনও ধারণার বৈধ মূল্যায়িত রেকর্ড নেই। ধারণা যোগ করে মূল্যায়িত কাজ ফেরত দিন।'],
 ['{count} graded records have missing or invalid scores, point totals, assignments or learner identifiers and are excluded.','{count} मूल्यांकित रिकॉर्ड में अंक, कुल अंक, कार्य या शिक्षार्थी की पहचान अनुपलब्ध या अमान्य है; वे शामिल नहीं हैं।','{count}টি মূল্যায়িত রেকর্ডে নম্বর, মোট নম্বর, কাজ বা শিক্ষার্থীর পরিচয় অনুপস্থিত বা অবৈধ; সেগুলি বাদ দেওয়া হয়েছে।'],
 ['{score}% · {count} graded','{score}% · {count} मूल्यांकित','{score}% · {count}টি মূল্যায়িত'],
 ['Concept coverage','अवधारणाओं की पहुँच','ধারণার অন্তর্ভুক্তি'],
 ['Topics tagged on recorded assignments. Each assignment counts once per topic.','दर्ज कार्यों पर जोड़ी अवधारणाएँ। हर अवधारणा के लिए एक कार्य एक बार गिना जाता है।','নথিভুক্ত কাজে যুক্ত ধারণা। প্রতি ধারণায় একটি কাজ একবার গণনা হয়।'],
 ['No concepts tagged yet. Add concept tags when creating assignments to map your coverage.','अभी कोई अवधारणा नहीं जोड़ी गई। कार्य बनाते समय अवधारणाएँ जोड़ें।','এখনও ধারণা যুক্ত হয়নি। কাজ তৈরির সময় ধারণা যোগ করুন।'],
 ['{count} assignments','{count} कार्य','{count}টি কাজ'],
 ['Recorded score heatmap','दर्ज अंकों का मानचित्र','নথিভুক্ত নম্বরের মানচিত্র'],
 ['Recorded assignment scores by concept. Use these alongside conversations and practice to decide what support helps.','अवधारणा के अनुसार दर्ज कार्यों के अंक। सहायता तय करने के लिए बातचीत और अभ्यास के साथ देखें।','ধারণা অনুযায়ী নথিভুক্ত কাজের নম্বর। সহায়তা ঠিক করতে কথোপকথন ও অনুশীলনের সঙ্গে দেখুন।'],
 ['The heatmap fills in once you tag concepts on assignments and return graded work.','कार्यों में अवधारणाएँ जोड़ने और मूल्यांकित कार्य लौटाने पर मानचित्र बनता है।','কাজে ধারণা যোগ করে মূল্যায়িত কাজ ফেরত দিলে মানচিত্র তৈরি হয়।'],
 ['Student','विद्यार्थी','শিক্ষার্থী'],['Teacher','शिक्षक','শিক্ষক'],
 ['Score 70%+','अंक 70%+','নম্বর 70%+'],['Score 40–69%','अंक 40–69%','নম্বর 40–69%'],['Score below 40%','अंक 40% से कम','নম্বর 40%-এর নিচে'],['No valid graded evidence','मान्य मूल्यांकित रिकॉर्ड नहीं','বৈধ মূল্যায়িত রেকর্ড নেই'],
 ['Share an update with your class','कक्षा के साथ सूचना साझा करें','ক্লাসের সঙ্গে খবর ভাগ করুন'],
 ['Announcements, reminders, or a welcome message…','घोषणाएँ, अनुस्मारक या स्वागत संदेश…','ঘোষণা, মনে করানো বা স্বাগত বার্তা…'],
 ['Welcome template','स्वागत संदेश का नमूना','স্বাগত বার্তার নমুনা'],
 ['Welcome to {name}! You’ll find assignments in Classwork and class updates here. I’m looking forward to learning together.','{name} में स्वागत है! कार्य कक्षा कार्य में और सूचनाएँ यहाँ मिलेंगी। साथ सीखने के लिए उत्साहित हूँ।','{name}-এ স্বাগত! ক্লাসের কাজে কাজ এবং এখানে ক্লাসের খবর পাবেন। একসঙ্গে শেখার অপেক্ষায় আছি।'],
 ['our class','हमारी कक्षा','আমাদের ক্লাস'],['Posting…','पोस्ट कर रहे हैं…','পোস্ট করা হচ্ছে…'],['Post update','सूचना पोस्ट करें','খবর পোস্ট করুন'],
 ['Class updates couldn’t be loaded. Please try again.','कक्षा की सूचनाएँ पढ़ी नहीं जा सकीं। फिर प्रयास करें।','ক্লাসের খবর পড়া যায়নি। আবার চেষ্টা করুন।'],
 ['Your update wasn’t posted. Your draft is still here; please try again.','सूचना पोस्ट नहीं हुई। आपका ड्राफ़्ट यहाँ है; फिर प्रयास करें।','খবর পোস্ট হয়নি। আপনার খসড়া এখানে আছে; আবার চেষ্টা করুন।'],
 ['Loading updates…','सूचनाएँ पढ़ रहे हैं…','খবর পড়া হচ্ছে…'],['Keep your class in the loop','कक्षा को जानकारी देते रहें','ক্লাসকে খবর জানান'],['Post a welcome message to get started.','स्वागत संदेश पोस्ट करके शुरू करें।','স্বাগত বার্তা পোস্ট করে শুরু করুন।'],['Class update','कक्षा की सूचना','ক্লাসের খবর'],
 ['Invite students','विद्यार्थियों को आमंत्रित करें','শিক্ষার্থীদের আমন্ত্রণ জানান'],['Student email address','विद्यार्थी का ईमेल पता','শিক্ষার্থীর ইমেল ঠিকানা'],['Invite','आमंत्रित करें','আমন্ত্রণ জানান'],['Teachers','शिक्षक','শিক্ষক'],['Students','विद्यार्थी','শিক্ষার্থীরা'],
 ['Add an in-app invitation by email, or share class code {code}. Email delivery is not connected yet.','ईमेल से ऐप में निमंत्रण जोड़ें या कक्षा कोड {code} साझा करें। ईमेल भेजने की सुविधा अभी जुड़ी नहीं है।','ইমেল দিয়ে অ্যাপে আমন্ত্রণ যোগ করুন বা ক্লাস কোড {code} ভাগ করুন। ইমেল পাঠানো এখনও সংযুক্ত নয়।'],
 ['from the class header','कक्षा के शीर्ष से','ক্লাসের শিরোনাম থেকে'],
 ['We couldn’t load your class members. Please try again.','कक्षा की सदस्य सूची पढ़ी नहीं जा सकी। फिर प्रयास करें।','ক্লাসের সদস্য তালিকা পড়া যায়নি। আবার চেষ্টা করুন।'],
 ['Use a student’s email address, rather than your teaching account.','विद्यार्थी का ईमेल पता दें।','শিক্ষার্থীর ইমেল ঠিকানা দিন।'],
 ['This student is already connected or has a pending invitation.','यह विद्यार्थी पहले से जुड़ा है या निमंत्रण लंबित है।','এই শিক্ষার্থী ইতিমধ্যে সংযুক্ত বা আমন্ত্রণ অপেক্ষায় আছে।'],
 ['Invitation added. It will appear in this student’s Classes page when they sign in on this device. You can also share the class code.','निमंत्रण जोड़ा गया। इस डिवाइस पर साइन इन करने पर विद्यार्थी की कक्षाओं में दिखेगा। कक्षा कोड भी साझा कर सकते हैं।','আমন্ত্রণ যোগ হয়েছে। এই ডিভাইসে সাইন ইন করলে শিক্ষার্থীর ক্লাসে দেখা যাবে। ক্লাস কোডও ভাগ করতে পারেন।'],
 ["Couldn't invite that student. Please try again.",'विद्यार्थी को आमंत्रित नहीं कर सके। फिर प्रयास करें।','শিক্ষার্থীকে আমন্ত্রণ জানানো যায়নি। আবার চেষ্টা করুন।'],
 ['No students yet. Invite your first student above to see them here.','अभी कोई विद्यार्थी नहीं है। ऊपर से पहला निमंत्रण जोड़ें।','এখনও শিক্ষার্থী নেই। উপরে প্রথম আমন্ত্রণ যোগ করুন।'],
 ['{connected} connected · {invited} invited','{connected} जुड़े · {invited} आमंत्रित','{connected}জন সংযুক্ত · {invited}জন আমন্ত্রিত'],
 ['Connected','जुड़ा','সংযুক্ত'],['Invited','आमंत्रित','আমন্ত্রিত'],['Removed','हटाया गया','সরানো হয়েছে'],['Declined','अस्वीकृत','প্রত্যাখ্যাত'],['Expired','समय समाप्त','মেয়াদ শেষ'],['Unavailable','अनुपलब्ध','অনুপলব্ধ'],
];
const map = Object.fromEntries(entries.map(([en, hi, bn]) => [en, { en, hi, bn }]));
export const classTabCopy = locale => (key, params = {}) => (map[key]?.[locale] || teacherCopy(locale)(key)).replace(/\{(\w+)\}/g, (match, name) => String(params[name] ?? match));
