// Interface copy only. Authored prompts, responses and teacher feedback retain
// their own source language and are never translated by this lookup.
const copy={
 'Opening your workspace…':['आपका कार्यक्षेत्र खुल रहा है…','আপনার কাজের স্থান খোলা হচ্ছে…'],
 'Class activity':['कक्षा की गतिविधि','শ্রেণির কাজ'],
 'Opening the saved assignment…':['सहेजा गया काम खुल रहा है…','সংরক্ষিত কাজ খোলা হচ্ছে…'],
 'Retry activity':['गतिविधि फिर खोलें','কাজটি আবার খুলুন'],
 'Open my classes':['मेरी कक्षाएँ खोलें','আমার শ্রেণিগুলো খুলুন'],
 'Back to classwork':['कक्षा के काम पर लौटें','শ্রেণির কাজে ফিরুন'],
 'Teacher-authored activity':['शिक्षक द्वारा लिखी गतिविधि','শিক্ষকের লেখা কাজ'],
 'points':['अंक','নম্বর'], 'Due':['अंतिम तारीख','শেষ তারিখ'],
 'Saved on this device. Your teacher reviews written responses; this activity does not automatically score understanding or establish mastery.':['इस डिवाइस पर सहेजा गया है। शिक्षक लिखे उत्तर की समीक्षा करते हैं; यह गतिविधि समझ का अपने आप अंक नहीं देती या दक्षता सिद्ध नहीं करती।','এই ডিভাইসে সংরক্ষিত। শিক্ষক লেখা উত্তরের পর্যালোচনা করেন; এই কাজ বোঝার নম্বর নিজে দেয় না বা দক্ষতা প্রমাণ করে না।'],
 'Assigned source version':['निर्धारित स्रोत संस्करण','নির্ধারিত উৎসের সংস্করণ'],
 'Ask about this assignment':['इस काम के बारे में पूछें','এই কাজ সম্পর্কে জিজ্ঞাসা করুন'],
 'Rehearse this objective':['इस उद्देश्य का अभ्यास करें','এই উদ্দেশ্যের অনুশীলন করুন'],
 'Checking class access and refreshing the saved activity…':['कक्षा की पहुँच जाँची जा रही है और सहेजी गतिविधि अपडेट हो रही है…','শ্রেণির অনুমতি যাচাই ও সংরক্ষিত কাজ হালনাগাদ হচ্ছে…'],
 'Export current response':['वर्तमान उत्तर निर्यात करें','বর্তমান উত্তর রপ্তানি করুন'],
 'Export saved drafts backup':['सहेजे मसौदों का बैकअप निर्यात करें','সংরক্ষিত খসড়ার ব্যাকআপ রপ্তানি করুন'],
 'Discard current edits and load latest draft':['वर्तमान संपादन छोड़कर नया मसौदा लोड करें','বর্তমান সম্পাদনা বাদ দিয়ে সর্বশেষ খসড়া লোড করুন'],
 'Returned by your teacher':['शिक्षक द्वारा लौटाया गया','শিক্ষক ফেরত দিয়েছেন'],
 'Submitted for review':['समीक्षा के लिए जमा','পর্যালোচনার জন্য জমা'],
 'Your submitted copy':['आपकी जमा की गई प्रति','আপনার জমা দেওয়া কপি'],
 'Refresh feedback':['प्रतिक्रिया फिर लोड करें','প্রতিক্রিয়া আবার লোড করুন'],
 'Revision requested':['संशोधन माँगा गया','সংশোধন চাওয়া হয়েছে'], 'Attempt':['प्रयास','চেষ্টা'],
 'Class activity stages':['कक्षा की गतिविधि के चरण','শ্রেণির কাজের ধাপ'],
 'Understand':['समझें','বুঝুন'], 'Respond':['उत्तर दें','উত্তর দিন'], 'Review':['समीक्षा करें','পর্যালোচনা করুন'],
 'Understand the assigned activity':['निर्धारित गतिविधि समझें','নির্ধারিত কাজটি বুঝুন'],
 'Your teacher has not supplied an explanation. Review the assignment title and ask your teacher for clarification before responding.':['शिक्षक ने व्याख्या नहीं दी है। उत्तर देने से पहले काम का शीर्षक देखें और शिक्षक से स्पष्ट करने को कहें।','শিক্ষক ব্যাখ্যা দেননি। উত্তর দেওয়ার আগে কাজের শিরোনাম দেখুন এবং শিক্ষককে ব্যাখ্যা করতে বলুন।'],
 'No reviewed interactive representation or objective mapping was attached to this assignment. The saved instructions remain available; visual or model-generated content has not been invented.':['इस काम से समीक्षित इंटरैक्टिव दृश्य या उद्देश्य का संबंध नहीं जोड़ा गया है। सहेजे निर्देश उपलब्ध हैं; दृश्य या मॉडल का बनाया हुआ विषय नहीं गढ़ा गया है।','এই কাজের সঙ্গে পর্যালোচিত ইন্টার‌্যাক্টিভ দৃশ্য বা উদ্দেশ্যের সম্পর্ক সংযুক্ত নেই। সংরক্ষিত নির্দেশ উপলব্ধ; দৃশ্য বা মডেলের তৈরি বিষয় বানানো হয়নি।'],
 'Continue to response':['उत्तर देने के लिए आगे बढ़ें','উত্তর দিতে এগিয়ে যান'],
 'Explain in your own words':['अपने शब्दों में समझाएँ','নিজের ভাষায় ব্যাখ্যা করুন'],
 'Class activity response':['कक्षा की गतिविधि का उत्तर','শ্রেণির কাজের উত্তর'],
 'Review the assigned criteria':['निर्धारित मानदंडों की समीक्षा करें','নির্ধারিত মানদণ্ড পর্যালোচনা করুন'],
 'These notes go to your teacher with the response. They are your self-review, not an automatic grade.':['ये नोट उत्तर के साथ शिक्षक को जाते हैं। ये आपकी स्व-समीक्षा हैं, अपने आप दिया गया अंक नहीं।','এই নোট উত্তরের সঙ্গে শিক্ষকের কাছে যায়। এগুলো আপনার নিজের পর্যালোচনা, স্বয়ংক্রিয় নম্বর নয়।'],
 'Criterion review':['मानदंड की समीक्षा','মানদণ্ডের পর্যালোচনা'],
 'Review my response':['मेरे उत्तर की समीक्षा करें','আমার উত্তর পর্যালোচনা করুন'],
 'Review the copy your teacher will receive':['शिक्षक को जाने वाली प्रति की समीक्षा करें','শিক্ষক যে কপি পাবেন তা পর্যালোচনা করুন'],
 'Submitting sends this response to your class teacher. Private learning notes and project drafts are excluded. An earlier attempt stays in the response history.':['जमा करने पर यह उत्तर आपकी कक्षा के शिक्षक को जाता है। निजी सीखने के नोट और परियोजना के मसौदे शामिल नहीं हैं। पिछला प्रयास उत्तर के इतिहास में रहता है।','জমা দিলে এই উত্তর শ্রেণির শিক্ষকের কাছে যায়। ব্যক্তিগত শেখার নোট ও প্রকল্পের খসড়া বাদ থাকে। আগের চেষ্টা উত্তরের ইতিহাসে থাকে।'],
 'No response yet':['अभी कोई उत्तर नहीं','এখনো কোনো উত্তর নেই'],
 'Criterion self-review included in this copy':['इस प्रति में शामिल मानदंडों की स्व-समीक्षा','এই কপিতে থাকা মানদণ্ডের নিজের পর্যালোচনা'],
 'Not reviewed yet':['अभी समीक्षा नहीं हुई','এখনো পর্যালোচনা হয়নি'],
 'Edit response':['उत्तर संपादित करें','উত্তর সম্পাদনা করুন'],
 'Submitting…':['जमा किया जा रहा है…','জমা দেওয়া হচ্ছে…'],
 'Resubmit to teacher':['शिक्षक को फिर जमा करें','শিক্ষকের কাছে আবার জমা দিন'],
 'Submit to teacher':['शिक्षक को जमा करें','শিক্ষকের কাছে জমা দিন'],
 'Submissions are closed. Your draft remains saved. Your teacher can reopen this activity.':['जमा करना बंद है। आपका मसौदा सहेजा गया है। शिक्षक यह गतिविधि फिर खोल सकते हैं।','জমা দেওয়া বন্ধ। আপনার খসড়া সংরক্ষিত আছে। শিক্ষক কাজটি আবার খুলতে পারেন।'],
 'Previous attempts and feedback':['पिछले प्रयास और प्रतिक्रिया','আগের চেষ্টা ও প্রতিক্রিয়া'],
 'Feedback':['प्रतिक्रिया','প্রতিক্রিয়া'],
 'Older saved drafts remain unreadable. Keep this page open and export your current response.':['पुराने सहेजे मसौदे पढ़े नहीं जा सके। यह पृष्ठ खुला रखें और वर्तमान उत्तर निर्यात करें।','আগের সংরক্ষিত খসড়া পড়া যায়নি। এই পৃষ্ঠা খোলা রাখুন এবং বর্তমান উত্তর রপ্তানি করুন।'],
 'Your response was submitted.':['आपका उत्तर जमा हो गया।','আপনার উত্তর জমা হয়েছে।'],
 'Current criterion notes':['वर्तमान मानदंड के नोट','বর্তমান মানদণ্ডের নোট'],
 'Teacher criterion feedback':['मानदंड पर शिक्षक की प्रतिक्रिया','মানদণ্ডে শিক্ষকের প্রতিক্রিয়া'],
 'Met':['पूरा हुआ','পূরণ হয়েছে'], 'Needs work':['और काम चाहिए','আরও কাজ দরকার'],
 'Not assessed':['मूल्यांकन नहीं हुआ','মূল্যায়ন হয়নি'], 'Unknown rating':['अज्ञात मूल्यांकन','অজানা মূল্যায়ন'],
 'Feedback unavailable':['प्रतिक्रिया उपलब्ध नहीं','প্রতিক্রিয়া উপলব্ধ নেই'],
 'Assigned objective practice':['निर्धारित उद्देश्य का अभ्यास','নির্ধারিত উদ্দেশ্যের অনুশীলন'],
 'Ask about classwork':['कक्षा के काम के बारे में पूछें','শ্রেণির কাজ সম্পর্কে জিজ্ঞাসা করুন'],
 'Opening the authorized source and saved private study…':['अनुमति प्राप्त स्रोत और सहेजा निजी अध्ययन खुल रहा है…','অনুমোদিত উৎস ও সংরক্ষিত ব্যক্তিগত পড়াশোনা খোলা হচ্ছে…'],
 'Retry source':['स्रोत फिर खोलें','উৎস আবার খুলুন'],
 'Export private study backup':['निजी अध्ययन का बैकअप निर्यात करें','ব্যক্তিগত পড়াশোনার ব্যাকআপ রপ্তানি করুন'],
 'Export current question':['वर्तमान प्रश्न निर्यात करें','বর্তমান প্রশ্ন রপ্তানি করুন'],
 'Return to assigned activity':['निर्धारित गतिविधि पर लौटें','নির্ধারিত কাজে ফিরুন'],
 'Private rehearsal':['निजी अभ्यास','ব্যক্তিগত অনুশীলন'],
 'Source-scoped Ask':['स्रोत से जुड़ा प्रश्न','উৎসভিত্তিক প্রশ্ন'],
 'Teacher instructions':['शिक्षक के निर्देश','শিক্ষকের নির্দেশ'],
 'Source version':['स्रोत संस्करण','উৎসের সংস্করণ'],
 'not recorded':['दर्ज नहीं है','লিপিবদ্ধ নেই'],
 'Saved on this device. Questions and rehearsal history are excluded from your class response and teacher grade.':['इस डिवाइस पर सहेजा गया है। प्रश्न और अभ्यास का इतिहास कक्षा के उत्तर और शिक्षक के अंक में शामिल नहीं हैं।','এই ডিভাইসে সংরক্ষিত। প্রশ্ন ও অনুশীলনের ইতিহাস শ্রেণির উত্তর এবং শিক্ষকের নম্বর থেকে বাদ থাকে।'],
 'Discard current edits and reload saved study':['वर्तमान संपादन छोड़कर सहेजा अध्ययन लोड करें','বর্তমান সম্পাদনা বাদ দিয়ে সংরক্ষিত পড়াশোনা লোড করুন'],
 'Ask using this assigned source':['इस निर्धारित स्रोत का उपयोग करके पूछें','এই নির্ধারিত উৎস ব্যবহার করে জিজ্ঞাসা করুন'],
 'Your private classwork question':['कक्षा के काम का आपका निजी प्रश्न','শ্রেণির কাজ নিয়ে আপনার ব্যক্তিগত প্রশ্ন'],
 'Save or send to keep your question across refresh. Source buttons can show the fixed assigned text. Other questions require the teaching service; no model answer is invented. Replies are transient.':['प्रश्न को रीफ़्रेश के बाद रखने के लिए सहेजें या भेजें। स्रोत बटन निर्धारित पाठ दिखाते हैं। अन्य प्रश्नों के लिए शिक्षण सेवा चाहिए; मॉडल का उत्तर नहीं गढ़ा जाता। प्रतिक्रियाएँ अस्थायी हैं।','রিফ্রেশের পর প্রশ্ন রাখতে সংরক্ষণ করুন বা পাঠান। উৎসের বোতাম নির্ধারিত পাঠ দেখায়। অন্য প্রশ্নের জন্য শিক্ষণ পরিষেবা দরকার; মডেলের উত্তর বানানো হয় না। প্রতিক্রিয়া অস্থায়ী।'],
 'Save private question':['निजी प्रश्न सहेजें','ব্যক্তিগত প্রশ্ন সংরক্ষণ করুন'],
 'Review assigned explanation':['निर्धारित व्याख्या देखें','নির্ধারিত ব্যাখ্যা দেখুন'],
 'Review teacher instructions':['शिक्षक के निर्देश देखें','শিক্ষকের নির্দেশ দেখুন'],
 'Ask this question':['यह प्रश्न पूछें','এই প্রশ্ন জিজ্ঞাসা করুন'],
 'Stop guidance':['मार्गदर्शन रोकें','নির্দেশনা থামান'],
 'From the assigned copy':['निर्धारित प्रति से','নির্ধারিত কপি থেকে'],
 'Connected teaching response':['जुड़ी शिक्षण सेवा की प्रतिक्रिया','সংযুক্ত শিক্ষণ পরিষেবার প্রতিক্রিয়া'],
 'Teaching paused':['शिक्षण रुका हुआ है','শিক্ষণ বিরত আছে'],
 'Teaching service unavailable':['शिक्षण सेवा उपलब्ध नहीं है','শিক্ষণ পরিষেবা উপলব্ধ নেই'],
 'Authored exercise':['लिखा गया अभ्यास','লেখা অনুশীলন'], 'of':['में से','এর মধ্যে'],
 'This checks a rehearsal answer against the authored key; it does not change your class grade or establish concept mastery.':['यह अभ्यास का उत्तर लिखी उत्तर कुंजी से जाँचता है; कक्षा का अंक नहीं बदलता या अवधारणा की दक्षता सिद्ध नहीं करता।','এটি অনুশীলনের উত্তর লেখা উত্তরসূচির সঙ্গে মিলিয়ে দেখে; শ্রেণির নম্বর বদলায় না বা ধারণার দক্ষতা প্রমাণ করে না।'],
 'Practice answer':['अभ्यास का उत्तर','অনুশীলনের উত্তর'],
 'Correct for this authored exercise.':['इस लिखे अभ्यास का सही उत्तर।','এই লেখা অনুশীলনের সঠিক উত্তর।'],
 'This answer did not match the authored key. Review the assigned explanation before a distinct retry.':['यह उत्तर लिखी उत्तर कुंजी से नहीं मिला। नया प्रयास करने से पहले निर्धारित व्याख्या देखें।','এই উত্তর লেখা উত্তরসূচির সঙ্গে মেলেনি। নতুন চেষ্টা করার আগে নির্ধারিত ব্যাখ্যা দেখুন।'],
 'Start a distinct retry':['नया प्रयास शुरू करें','নতুন চেষ্টা শুরু করুন'],
 'Next authored question':['अगला लिखा प्रश्न','পরবর্তী লেখা প্রশ্ন'],
 'Check rehearsal answer':['अभ्यास का उत्तर जाँचें','অনুশীলনের উত্তর যাচাই করুন'],
 'You reached the last authored exercise. Your rehearsal history is saved. Return to the assigned activity to prepare your response.':['आप आखिरी लिखे अभ्यास तक पहुँच गए हैं। अभ्यास का इतिहास सहेजा गया है। अपना उत्तर तैयार करने के लिए निर्धारित गतिविधि पर लौटें।','আপনি শেষ লেখা অনুশীলনে পৌঁছেছেন। অনুশীলনের ইতিহাস সংরক্ষিত। উত্তর তৈরি করতে নির্ধারিত কাজে ফিরুন।'],
 'Previous authored question':['पिछला लिखा प्रश्न','আগের লেখা প্রশ্ন'],
 'Prepare my class response':['कक्षा का मेरा उत्तर तैयार करें','শ্রেণির উত্তর তৈরি করুন'],
 'Private rehearsal history':['निजी अभ्यास का इतिहास','ব্যক্তিগত অনুশীলনের ইতিহাস'],
 'matched key':['उत्तर कुंजी से मिला','উত্তরসূচির সঙ্গে মিলেছে'],
 'did not match key':['उत्तर कुंजी से नहीं मिला','উত্তরসূচির সঙ্গে মেলেনি'],
 'Export my rehearsal':['मेरा अभ्यास निर्यात करें','আমার অনুশীলন রপ্তানি করুন'],
 'Guidance stopped. Your question remains here.':['मार्गदर्शन रुक गया। आपका प्रश्न यहाँ रहता है।','নির্দেশনা থেমেছে। আপনার প্রশ্ন এখানেই আছে।'],
 'Help me review the assigned instructions.':['निर्धारित निर्देश समझने में मदद करें।','নির্ধারিত নির্দেশ বুঝতে সাহায্য করুন।'],
 'Help me review the assigned explanation.':['निर्धारित व्याख्या समझने में मदद करें।','নির্ধারিত ব্যাখ্যা বুঝতে সাহায্য করুন।'],
 'Submit a saved project copy':['सहेजी परियोजना की प्रति जमा करें','সংরক্ষিত প্রকল্পের কপি জমা দিন'],
 'Choose a completed project in this workspace. The preview shows the exact document and self-review your class teacher will receive. Future edits stay separate. Private drafts and parent sharing settings are excluded.':['इस कार्यक्षेत्र की पूरी परियोजना चुनें। पूर्वावलोकन में वही दस्तावेज़ और स्व-समीक्षा हैं जो शिक्षक को मिलेंगे। बाद के संपादन अलग रहते हैं। निजी मसौदे और माता-पिता के साथ साझा करने की सेटिंग शामिल नहीं हैं।','এই কাজের স্থানের সম্পূর্ণ প্রকল্প বেছে নিন। প্রিভিউতে শিক্ষক যে নথি ও নিজের পর্যালোচনা পাবেন তা দেখানো হয়। পরের সম্পাদনা আলাদা থাকে। ব্যক্তিগত খসড়া ও অভিভাবকের সঙ্গে ভাগ করার সেটিং বাদ থাকে।'],
 'No completed projects in this workspace.':['इस कार्यक्षेत्र में पूरी परियोजनाएँ नहीं हैं।','এই কাজের স্থানে সম্পূর্ণ প্রকল্প নেই।'],
 'Open projects':['परियोजनाएँ खोलें','প্রকল্প খুলুন'],
 'Completed project':['पूरी परियोजना','সম্পূর্ণ প্রকল্প'],
 'Choose a project':['परियोजना चुनें','প্রকল্প বেছে নিন'],
 'Preview classroom copy':['कक्षा की प्रति का पूर्वावलोकन करें','শ্রেণির কপির প্রিভিউ দেখুন'],
 'Classroom project copy':['कक्षा की परियोजना की प्रति','শ্রেণির প্রকল্পের কপি'],
 'Submitting creates a fixed class response. Your teacher can return feedback or request a revision. Completion and self-review do not establish mastery.':['जमा करने से कक्षा के लिए स्थिर उत्तर बनता है। शिक्षक प्रतिक्रिया दे सकते हैं या संशोधन माँग सकते हैं। पूरा करना और स्व-समीक्षा दक्षता सिद्ध नहीं करते।','জমা দিলে শ্রেণির জন্য স্থির উত্তর তৈরি হয়। শিক্ষক প্রতিক্রিয়া দিতে বা সংশোধন চাইতে পারেন। সম্পূর্ণ করা ও নিজের পর্যালোচনা দক্ষতা প্রমাণ করে না।'],
 'Submitting project…':['परियोजना जमा हो रही है…','প্রকল্প জমা দেওয়া হচ্ছে…'],
 'Resubmit project copy':['परियोजना की प्रति फिर जमा करें','প্রকল্পের কপি আবার জমা দিন'],
 'Submit project copy':['परियोजना की प्रति जमा करें','প্রকল্পের কপি জমা দিন'],
};
export function classworkTranslator(locale) {
 const index=locale==='hi'?0:locale==='bn'?1:-1;
 return text=>index<0?text:copy[text]?.[index]||text;
}
