import { primaryWorkspaceCopy } from './primaryWorkspaceCopy.js';

// Interface copy only. Authored concept names, assignments and project text stay verbatim.
const rows = [
  ['Change plan','योजना बदलें','পরিকল্পনা বদলান'],
  ['Open classwork','कक्षा का कार्य खोलें','ক্লাসের কাজ খুলুন'],
  ['{className}{due}. Open it to review and submit your work.','{className}{due}। कार्य देखने और जमा करने के लिए खोलें।','{className}{due}। কাজ পর্যালোচনা ও জমা দিতে খুলুন।'],
  [' · Due {date}',' · अंतिम तारीख {date}',' · শেষ তারিখ {date}'],
  ['Published assignment in a class where your enrollment is active.','सक्रिय नामांकन वाली कक्षा का प्रकाशित कार्य।','সক্রিয় ভর্তি থাকা ক্লাসের প্রকাশিত কাজ।'],
  ['Connected classwork','जुड़ी कक्षा का कार्य','সংযুক্ত ক্লাসের কাজ'],
  ['Review: {title}','पुनरावृत्ति: {title}','পুনরালোচনা: {title}'],
  ['Your saved project remains in Build.','सहेजा प्रोजेक्ट Build में है।','সংরক্ষিত প্রকল্প Build-এ আছে।'],
  ['Open projects','प्रोजेक्ट खोलें','প্রকল্প খুলুন'],
  ['Unfinished project work saved in this workspace.','इस कार्यक्षेत्र में सहेजा अधूरा प्रोजेक्ट।','এই কর্মক্ষেত্রে সংরক্ষিত অসমাপ্ত প্রকল্পের কাজ।'],
  ['Your saved project','आपका सहेजा प्रोजेक्ट','আপনার সংরক্ষিত প্রকল্প'],
  ['Done today · recorded comprehension check and practice. Reopen to revisit the explanation.','आज पूरा हुआ · समझ की जाँच और अभ्यास दर्ज हैं। व्याख्या फिर देखने के लिए खोलें।','আজ সম্পন্ন · বোঝার যাচাই ও অনুশীলন নথিভুক্ত। ব্যাখ্যা আবার দেখতে খুলুন।'],
  ['Reopen','फिर खोलें','আবার খুলুন'],
  ['Recorded earlier today from verified comprehension work.','आज पहले समझ की जाँच से दर्ज किया गया।','আজ আগে বোঝার যাচাই থেকে নথিভুক্ত।'],
  ['Done today · your project was marked complete in Build.','आज पूरा हुआ · प्रोजेक्ट को Build में पूरा चिह्नित किया गया।','আজ সম্পন্ন · Build-এ প্রকল্প সম্পূর্ণ হিসেবে চিহ্নিত।'],
  ['Recorded earlier today from your completed project.','आज पहले पूरे प्रोजेक्ट से दर्ज किया गया।','আজ আগে সম্পন্ন প্রকল্প থেকে নথিভুক্ত।'],
  ['Your next step is unavailable','अगला कदम उपलब्ध नहीं है','পরের ধাপ অনুপলব্ধ'],
  ['Retry','फिर प्रयास करें','আবার চেষ্টা করুন'],
  ['Open saved conversations','सहेजी बातचीत खोलें','সংরক্ষিত কথোপকথন খুলুন'],
  ['Preparing your next step…','अगला कदम तैयार हो रहा है…','পরের ধাপ প্রস্তুত হচ্ছে…'],
  ['Saved on this device','इस डिवाइस पर सहेजा गया','এই ডিভাইসে সংরক্ষিত'],
  ['Updating your next step…','अगला कदम अपडेट हो रहा है…','পরের ধাপ আপডেট হচ্ছে…'],
  ['Next for you','आपका अगला कदम','আপনার পরের ধাপ'],
  ['Why this?','यह क्यों?','এটি কেন?'],
  ['Not today','आज नहीं','আজ নয়'],
  ['Your plan is unchanged. Try Not today again after checking browser storage.','योजना नहीं बदली है। ब्राउज़र का स्टोरेज जाँचकर फिर प्रयास करें।','পরিকল্পনা বদলায়নি। ব্রাউজারের স্টোরেজ যাচাই করে আবার চেষ্টা করুন।'],
  ['Things I remember about you','आपके बारे में सहेजी जानकारी','আপনার সম্পর্কে সংরক্ষিত তথ্য'],
  ['Only from your saved activity this week. These are observations, not an AI assessment.','केवल इस सप्ताह की सहेजी गतिविधि से। ये अवलोकन हैं, AI का आकलन नहीं।','শুধু এই সপ্তাহের সংরক্ষিত কার্যকলাপ থেকে। এগুলি পর্যবেক্ষণ, AI মূল্যায়ন নয়।'],
  ['No weekly observations yet. Start a learning unit or practice step to build your own history.','अभी इस सप्ताह के अवलोकन नहीं हैं। सीखना या अभ्यास शुरू करके अपना इतिहास बनाएँ।','এখনও সাপ্তাহিক পর্যবেক্ষণ নেই। নিজের ইতিহাস তৈরি করতে শেখা বা অনুশীলন শুরু করুন।'],
  ['Learning memory is off for this workspace. You can change it in Personalization.','इस कार्यक्षेत्र की सीखने की मेमोरी बंद है। वैयक्तिकरण में इसे बदल सकते हैं।','এই কর্মক্ষেত্রে শেখার মেমরি বন্ধ। ব্যক্তিগতকরণে এটি বদলাতে পারেন।'],
  ['View or clear memory','मेमोरी देखें या साफ़ करें','মেমরি দেখুন বা মুছুন'],
  ['Need help along the way?','आगे बढ़ने में सहायता चाहिए?','এগিয়ে যেতে সাহায্য দরকার?'],
  ['Ask a question or continue a saved conversation.','प्रश्न पूछें या सहेजी बातचीत जारी रखें।','প্রশ্ন করুন বা সংরক্ষিত কথোপকথন চালিয়ে যান।'],
  ['Ask Visionary Guide','Visionary Guide से पूछें','Visionary Guide-কে জিজ্ঞাসা করুন'],
  ['Local preview · Saved on this device. No live model or cloud sync.','स्थानीय प्रीव्यू · इस डिवाइस पर सहेजा गया। लाइव मॉडल या क्लाउड सिंक नहीं जुड़ा है।','স্থানীয় প্রিভিউ · এই ডিভাইসে সংরক্ষিত। লাইভ মডেল বা ক্লাউড সিঙ্ক যুক্ত নেই।'],
  ['Sharing is always scoped','साझा करना अनुमति के दायरे में है','তথ্য ভাগ করা অনুমতির সীমার মধ্যে'],
  ['Only connected work belongs here','यहाँ केवल जुड़ा कार्य दिखता है','এখানে শুধু সংযুক্ত কাজ থাকে'],
  ['Connected organization · Personal learning stays separate','जुड़ा संगठन · निजी सीखना अलग रहता है','সংযুক্ত প্রতিষ্ঠান · ব্যক্তিগত শেখা আলাদা থাকে'],
  ['Choose something to understand','समझने के लिए एक विषय चुनें','বোঝার জন্য একটি বিষয় বেছে নিন'],
  ['Begin with one idea, explore it, then put it to use.','एक विचार से शुरू करें, समझें और उसका उपयोग करें।','একটি ধারণা দিয়ে শুরু করুন, অন্বেষণ করুন, তারপর কাজে লাগান।'],
  ['Choose a learning journey','सीखने का रास्ता चुनें','শেখার পথ বেছে নিন'],
  ['Explore a project','प्रोजेक्ट देखें','প্রকল্প দেখুন'],
  ['A starting point, not an assessment of what you know.','यह शुरुआत है, आपके ज्ञान का आकलन नहीं।','এটি শুরুর ধাপ, আপনার জ্ঞানের মূল্যায়ন নয়।'],
  ['Your selected learner role','आपकी चुनी शिक्षार्थी भूमिका','আপনার নির্বাচিত শিক্ষার্থী ভূমিকা'],
  ['Give your next skill a clear purpose','अगले कौशल का स्पष्ट लक्ष्य तय करें','পরের দক্ষতার স্পষ্ট উদ্দেশ্য ঠিক করুন'],
  ['Choose a work problem or career goal to guide your learning.','सीखने के लिए कार्य की समस्या या करियर लक्ष्य चुनें।','শেখার দিশা দিতে কাজের সমস্যা বা কর্মজীবনের লক্ষ্য বেছে নিন।'],
  ['Set a skill goal','कौशल का लक्ष्य तय करें','দক্ষতার লক্ষ্য ঠিক করুন'],
  ['Explore learning','सीखने के विकल्प देखें','শেখার সুযোগ দেখুন'],
  ['Your professional workspace starts with the outcome you want.','पेशेवर कार्यक्षेत्र आपके इच्छित परिणाम से शुरू होता है।','আপনার পেশাগত কর্মক্ষেত্র কাঙ্ক্ষিত ফলাফল থেকে শুরু হয়।'],
  ['Your selected professional role','आपकी चुनी पेशेवर भूमिका','আপনার নির্বাচিত পেশাগত ভূমিকা'],
  ['Build evidence for {title}','{title} के लिए कार्य का प्रमाण बनाएँ','{title}-এর জন্য কাজের প্রমাণ তৈরি করুন'],
  ['Connect this target to a capability, check your understanding, and save a project you can explain.','लक्ष्य को कौशल से जोड़ें, समझ जाँचें और ऐसा प्रोजेक्ट सहेजें जिसे समझा सकें।','লক্ষ্যকে দক্ষতার সঙ্গে যুক্ত করুন, বোঝা যাচাই করুন এবং ব্যাখ্যা করতে পারেন এমন প্রকল্প সংরক্ষণ করুন।'],
  ['Continue your career path','करियर का रास्ता जारी रखें','কর্মজীবনের পথ চালিয়ে যান'],
  ['This is the career target you saved in this workspace, not a prediction of your ability.','यह सहेजा करियर लक्ष्य है, क्षमता का अनुमान नहीं।','এটি এই কর্মক্ষেত্রে সংরক্ষিত কর্মজীবনের লক্ষ্য, আপনার ক্ষমতার পূর্বাভাস নয়।'],
  ['Your saved career target','आपका सहेजा करियर लक्ष्य','আপনার সংরক্ষিত কর্মজীবনের লক্ষ্য'],
  ['Continue activity','गतिविधि जारी रखें','কার্যকলাপ চালিয়ে যান'],
  ['Choose another journey','दूसरा सीखने का रास्ता चुनें','অন্য শেখার পথ বেছে নিন'],
  ['This is your most recently updated unfinished activity in this workspace.','यह इस कार्यक्षेत्र की हाल में अपडेट हुई अधूरी गतिविधि है।','এটি এই কর্মক্ষেত্রের সম্প্রতি আপডেট হওয়া অসমাপ্ত কার্যকলাপ।'],
  ['Saved activity on this device','इस डिवाइस पर सहेजी गतिविधि','এই ডিভাইসে সংরক্ষিত কার্যকলাপ'],
  ['Continue from {stage}. Your answers, notes and activity controls are saved.','{stage} से जारी रखें। उत्तर, नोट्स और गतिविधि के नियंत्रण सहेजे हैं।','{stage} থেকে চালিয়ে যান। উত্তর, নোট ও কার্যকলাপের নিয়ন্ত্রণ সংরক্ষিত।'],
  ['Continue from {stage}. Your answers and position are saved on this device.','{stage} से जारी रखें। उत्तर और स्थान इस डिवाइस पर सहेजे हैं।','{stage} থেকে চালিয়ে যান। উত্তর ও অবস্থান এই ডিভাইসে সংরক্ষিত।'],
  ['Continue learning','सीखना जारी रखें','শেখা চালিয়ে যান'],
  ['Open learning outline','सीखने की रूपरेखा खोलें','শেখার রূপরেখা খুলুন'],
  ['This is your most recently updated unfinished learning unit in this workspace.','यह इस कार्यक्षेत्र की हाल में अपडेट हुई अधूरी सीखने की इकाई है।','এটি এই কর্মক্ষেত্রের সম্প্রতি আপডেট হওয়া অসমাপ্ত শেখার একক।'],
  ['The most recently updated unfinished learning unit in this workspace.','इस कार्यक्षेत्र की हाल में अपडेट हुई अधूरी सीखने की इकाई।','এই কর্মক্ষেত্রের সম্প্রতি আপডেট হওয়া অসমাপ্ত শেখার একক।'],
  ['Saved learning activity','सहेजी सीखने की गतिविधि','সংরক্ষিত শেখার কার্যকলাপ'],
  ['A short review is due','थोड़ी पुनरावृत्ति का समय है','সংক্ষিপ্ত পুনরালোচনার সময় হয়েছে'],
  ['A previous check is ready to revisit. This is a reminder, not a claim about your ability.','पिछली जाँच फिर देख सकते हैं। यह याद दिलाना है, क्षमता का दावा नहीं।','আগের যাচাই আবার দেখার সময় হয়েছে। এটি স্মরণ করিয়ে দেওয়া, ক্ষমতার দাবি নয়।'],
  ['Open practice','अभ्यास खोलें','অনুশীলন খুলুন'],
  ['Scheduled from the date of your latest recorded check.','पिछली दर्ज जाँच की तारीख से तय किया गया।','শেষ নথিভুক্ত যাচাইয়ের তারিখ থেকে নির্ধারিত।'],
  ['Scheduled from the date of the latest recorded check for this concept.','इस अवधारणा की पिछली दर्ज जाँच की तारीख से तय किया गया।','এই ধারণার শেষ নথিভুক্ত যাচাইয়ের তারিখ থেকে নির্ধারিত।'],
  ['Your own recorded learning evidence','आपके सीखने का दर्ज प्रमाण','আপনার নিজের নথিভুক্ত শেখার প্রমাণ'],
  ['Your recorded learning evidence','सीखने का दर्ज प्रमाण','নথিভুক্ত শেখার প্রমাণ'],
  ['Start with {title}','{title} से शुरू करें','{title} দিয়ে শুরু করুন'],
  ['Open your subject outline. If official content is unavailable, you can keep a provisional learning place and ask a question.','विषय की रूपरेखा खोलें। आधिकारिक सामग्री न हो तो अस्थायी स्थान सहेजें और प्रश्न पूछें।','বিষয়ের রূপরেখা খুলুন। সরকারি পাঠ্য না থাকলে অস্থায়ী শেখার অবস্থান রেখে প্রশ্ন করতে পারেন।'],
  ['Open subject','विषय खोलें','বিষয় খুলুন'],
  ['Build a project','प्रोजेक्ट बनाएँ','প্রকল্প তৈরি করুন'],
  ['This is the starting subject you selected during setup, not an assessment of what you know.','यह सेटअप में चुना विषय है, आपके ज्ञान का आकलन नहीं।','এটি সেটআপে নির্বাচিত শুরুর বিষয়, আপনার জ্ঞানের মূল্যায়ন নয়।'],
  ['Your onboarding preference','सेटअप में आपकी पसंद','সেটআপে আপনার পছন্দ'],
  ['Today’s plan','आज की योजना','আজকের পরিকল্পনা'],
  ['Prepare your next lesson','अगला पाठ तैयार करें','পরের পাঠ প্রস্তুত করুন'],
  ['Continue preparing {title}','{title} की तैयारी जारी रखें','{title}-এর প্রস্তুতি চালিয়ে যান'],
  ['Review the objective, explanation and checks before sharing with a class.','कक्षा से साझा करने से पहले उद्देश्य, व्याख्या और जाँच की समीक्षा करें।','ক্লাসে ভাগ করার আগে উদ্দেশ্য, ব্যাখ্যা ও যাচাই পর্যালোচনা করুন।'],
  ['Open preparation','तैयारी खोलें','প্রস্তুতি খুলুন'],
  ['View classwork','कक्षा का कार्य देखें','ক্লাসের কাজ দেখুন'],
  ['You have an unfinished lesson draft in this teacher workspace.','शिक्षक कार्यक्षेत्र में एक अधूरा पाठ ड्राफ़्ट है।','এই শিক্ষক কর্মক্ষেত্রে একটি অসমাপ্ত পাঠের খসড়া আছে।'],
  ['Start with the idea you want your learners to understand.','उस विचार से शुरू करें जिसे शिक्षार्थियों को समझाना चाहते हैं।','শিক্ষার্থীদের যে ধারণা বোঝাতে চান সেটি দিয়ে শুরু করুন।'],
  ['Saved lesson draft','सहेजा पाठ ड्राफ़्ट','সংরক্ষিত পাঠের খসড়া'],
  ['Your selected teacher role','आपकी चुनी शिक्षक भूमिका','আপনার নির্বাচিত শিক্ষক ভূমিকা'],
  ['A little clarity for {name}’s week','{name} के सप्ताह को समझें','{name}-এর সপ্তাহ সম্পর্কে জানুন'],
  ['View shared report','साझा रिपोर्ट देखें','ভাগ করা প্রতিবেদন দেখুন'],
  ['Choose a child','बच्चा चुनें','সন্তান বেছে নিন'],
  ['An active connection permits a progress summary. Private conversations and notes are not included.','सक्रिय अनुमति से प्रगति का सारांश मिलता है। निजी बातचीत और नोट्स शामिल नहीं हैं।','সক্রিয় সংযোগ অগ্রগতির সারাংশের অনুমতি দেয়। ব্যক্তিগত কথোপকথন ও নোট অন্তর্ভুক্ত নয়।'],
  ['Last {days} days · Accepted progress sharing','पिछले {days} दिन · प्रगति साझा करने की अनुमति','গত {days} দিন · অগ্রগতি ভাগ করার অনুমতি'],
  ['Connect before viewing progress','प्रगति देखने से पहले जुड़ें','অগ্রগতি দেখার আগে সংযুক্ত হন'],
  ['Request permission to see a child’s learning summary. Family billing does not grant access.','सीखने का सारांश देखने की अनुमति माँगें। परिवार का भुगतान पहुँच नहीं देता।','সন্তানের শেখার সারাংশ দেখার অনুমতি চান। পরিবারের বিল দেওয়া তথ্যের অধিকার দেয় না।'],
  ['Connect with a child','बच्चे से जुड़ें','সন্তানের সঙ্গে সংযুক্ত হন'],
  ['Review sharing boundaries','साझा करने की सीमाएँ देखें','তথ্য ভাগ করার সীমা দেখুন'],
  ['There is no active progress-sharing connection available in this workspace.','इस कार्यक्षेत्र में प्रगति साझा करने की सक्रिय अनुमति नहीं है।','এই কর্মক্ষেত্রে অগ্রগতি ভাগ করার সক্রিয় সংযোগ নেই।'],
  ['Current sharing permissions','साझा करने की वर्तमान अनुमतियाँ','তথ্য ভাগ করার বর্তমান অনুমতি'],
  ['Ask which explanation helped most. Offer time for a short review together.','पूछें कौन सी व्याख्या सबसे उपयोगी थी। साथ थोड़ी पुनरावृत्ति का समय दें।','কোন ব্যাখ্যা সবচেয়ে সাহায্য করেছে জিজ্ঞাসা করুন। একসঙ্গে সংক্ষিপ্ত পুনরালোচনার সময় দিন।'],
  ['No guided-learning activity was shared in this period. Ask what they would like to explore next.','इस अवधि में निर्देशित सीखने की गतिविधि साझा नहीं हुई। पूछें आगे क्या सीखना चाहेंगे।','এই সময়ে নির্দেশিত শেখার কার্যকলাপ ভাগ করা হয়নি। পরের বার কী অন্বেষণ করতে চায় জিজ্ঞাসা করুন।'],
  ['Bring your people together','अपने लोगों को जोड़ें','আপনার মানুষদের একত্র করুন'],
  ['Review your organization’s next steps','संगठन के अगले कदम देखें','প্রতিষ্ঠানের পরের ধাপ পর্যালোচনা করুন'],
  ['Review the learning direction','सीखने की दिशा देखें','শেখার দিশা পর্যালোচনা করুন'],
  ['Connect curriculum and reviewed content to the groups you support.','समूहों को पाठ्यक्रम और समीक्षित सामग्री से जोड़ें।','যে দলগুলিকে সহায়তা করেন তাদের পাঠ্যক্রম ও পর্যালোচিত বিষয়বস্তুর সঙ্গে যুক্ত করুন।'],
  ['Start with invitations, then organize connected people into cohorts.','आमंत्रण से शुरू करें, फिर जुड़े लोगों के समूह बनाएँ।','আমন্ত্রণ দিয়ে শুরু করুন, তারপর সংযুক্ত মানুষদের দলে সাজান।'],
  ['Open insights','विश्लेषण खोलें','বিশ্লেষণ খুলুন'],
  ['Open curriculum','पाठ्यक्रम खोलें','পাঠ্যক্রম খুলুন'],
  ['Manage people','लोगों का प्रबंधन करें','মানুষদের পরিচালনা করুন'],
  ['Review cohorts','समूह देखें','দল পর্যালোচনা করুন'],
  ['A cohort is saved in this workspace; a draft alone does not establish approved curriculum.','समूह सहेजा है; केवल ड्राफ़्ट से पाठ्यक्रम स्वीकृत नहीं होता।','এই কর্মক্ষেত্রে একটি দল সংরক্ষিত; শুধু খসড়া অনুমোদিত পাঠ্যক্রম প্রমাণ করে না।'],
  ['No cohort has been saved in this workspace yet. People and permissions come first.','अभी समूह नहीं सहेजा है। पहले लोगों और अनुमतियों को जोड़ें।','এখনও দল সংরক্ষিত হয়নি। মানুষ ও অনুমতি আগে আসে।'],
  ['Saved organization setup records','संगठन के सहेजे सेटअप रिकॉर्ड','প্রতিষ্ঠানের সংরক্ষিত সেটআপের রেকর্ড'],
  ['Career suggestions use only your saved goal and recorded work. No hiring assessment or live model is connected.','करियर सुझाव सहेजे लक्ष्य और दर्ज कार्य से हैं। भर्ती आकलन या लाइव मॉडल जुड़ा नहीं है।','কর্মজীবনের পরামর্শ শুধু সংরক্ষিত লক্ষ্য ও কাজ ব্যবহার করে। নিয়োগ মূল্যায়ন বা লাইভ মডেল যুক্ত নেই।'],
  ['This view uses your saved learning stage and activity. Suggested session lengths are optional; they do not assess your ability.','यह दृश्य सहेजे सीखने के चरण और गतिविधि का उपयोग करता है। सुझाई अवधि वैकल्पिक है, क्षमता का आकलन नहीं।','এই দৃশ্য সংরক্ষিত শেখার স্তর ও কার্যকলাপ ব্যবহার করে। প্রস্তাবিত সময় ঐচ্ছিক, ক্ষমতার মূল্যায়ন নয়।'],
  ['A saved activity is unavailable in this preview. Its record has been preserved.','इस प्रीव्यू में सहेजी गतिविधि उपलब्ध नहीं है। रिकॉर्ड सुरक्षित है।','এই প্রিভিউয়ে সংরক্ষিত কার্যকলাপ অনুপলব্ধ। রেকর্ড রাখা হয়েছে।'],
  ['Open {title}. We will go step by step.','{title} खोलें। हम कदम-दर-कदम सीखेंगे।','{title} খুলুন। আমরা ধাপে ধাপে শিখব।'],
  ['your subject','अपना विषय','আপনার বিষয়'],
  ['Open the work your teacher assigned.','शिक्षक का दिया कार्य खोलें।','শিক্ষকের দেওয়া কাজ খুলুন।'],
  ['A quick review will keep it fresh.','थोड़ी पुनरावृत्ति से याद ताज़ा करें।','সংক্ষিপ্ত পুনরালোচনায় মনে রাখুন।'],
  ['Continue where you stopped.','जहाँ रुके थे वहीं से जारी रखें।','যেখানে থেমেছিলেন সেখান থেকে চালিয়ে যান।'],
  ['explain','समझना','বোঝা'],['check','समझ की जाँच','বোঝার যাচাই'],['practice','अभ्यास','অনুশীলন'],['build','प्रोजेक्ट','প্রকল্প'],
  ['explore','खोज करना','অন্বেষণ'],['reflect','चिंतन','ভাবনা'],['completed','पूरा हुआ','সম্পন্ন'],
];
const messages = Object.fromEntries(rows.map(([en,hi,bn]) => [en,{en,hi,bn}]));
export const homeCopy = locale => (key, params = {}) => (messages[key]?.[locale] || primaryWorkspaceCopy(locale)(key)).replace(/\{(\w+)\}/g,(match,name) => String(params[name] ?? match));
