const copy = {
 en: {
  representation:'Concept representation', another:'See the idea another way', temporary:'This exploration view stays on this page. It does not create a saved attempt or learning evidence.', saved:'Your view stays with this learning activity. Exploring it does not count as a correct answer.', mode:'Representation mode', cube:'Interactive 3D', line:'Interactive number line', chart:'View chart', description:'Read description', saveError:'The model view could not be saved. Try again.', cubeDescription:(side,volume,rotation)=>`Cube with side ${side} units, volume ${volume} cubic units, rotated ${rotation} degrees`, growth:'A cube grows in three directions. Volume = side × side × side.', cubic:'cubic units', side:'Side length', units:'units', rotation:'Rotation', resetModel:'Reset model', unsupported:'This interactive representation is not available in this local preview. The description remains usable.', lineDescription:(min,max,parts,value)=>`Number line from ${min} to ${max}, divided into ${parts} equal parts. Selected value ${value}.`, parts:(value,total)=>`Selected equal parts: ${value} of ${total}`, value:'Value', resetLine:'Reset number line', table:'Source values and calculated mean', sample:'Sample', mean:'Mean', cause:'These values describe the authored sample. A chart or mean alone does not establish a cause.',
  loading:'Reading assigned chapters and objectives…', unavailable:'Assigned outline unavailable', retry:'Retry assigned outline', title:'Your assigned learning outline', intro:'Only source copies your teacher actually assigned are shown. This is not the full book or a claim that unassigned chapters are complete. Source versions stay separate; response and teacher-feedback status are not knowledge scores.', find:'Find an assigned chapter or objective', unreadable:count=>`${count} assigned source ${count===1?'copy is':'copies are'} unreadable. Original records are retained.`, retrySources:'Retry assigned sources', version:'version', sourceSection:'Source section', reviewed:'Organization-reviewed copy', authored:'Authored sample', sourced:'Sourced curriculum', submitted:'Submitted for teacher review', graded:'Returned by teacher', revision_requested:'Revision requested', 'not-submitted':'No submitted response', returned:'Returned by teacher', savedStatus:'Saved teacher status', assignment:'Assignment', prerequisite:'Prerequisite guidance', reviewTeacher:'Review with your teacher if needed.', open:'Open assigned objective', ask:'Ask about assigned source', practice:'Practice assigned source', unmapped:'Assignments without an attached objective', unmappedIntro:'Their instructions remain usable. No chapter or curriculum mapping has been assumed.', noMatch:'No matching assigned chapters or objectives.', unreadableEmpty:'No readable attached objectives are available. Use Classwork to review the original assignment.', empty:'No source objectives have been assigned yet. Your own learning remains available.', clear:'Clear outline search', fallbackChapter:'Assigned source objectives', published:'Published', draft:'Draft', archived:'Archived', closed:'Closed', cancelled:'Cancelled', scheduled:'Scheduled', unknownAssignment:'Saved assignment status',
 },
 hi: {
  representation:'अवधारणा का दृश्य', another:'विचार को दूसरे तरीके से देखें', temporary:'यह दृश्य इसी पृष्ठ पर रहता है। इससे सहेजा गया प्रयास या सीखने का प्रमाण नहीं बनता।', saved:'आपका दृश्य इस सीखने की गतिविधि के साथ रहता है। इसे देखने से उत्तर सही नहीं माना जाता।', mode:'दृश्य का तरीका', cube:'इंटरैक्टिव 3D', line:'इंटरैक्टिव संख्या रेखा', chart:'चार्ट देखें', description:'विवरण पढ़ें', saveError:'दृश्य सहेजा नहीं जा सका। फिर कोशिश करें।', cubeDescription:(side,volume,rotation)=>`${side} इकाई भुजा और ${volume} घन इकाई आयतन वाला घन, ${rotation} डिग्री घुमाया गया`, growth:'घन तीन दिशाओं में बढ़ता है। आयतन = भुजा × भुजा × भुजा।', cubic:'घन इकाई', side:'भुजा की लंबाई', units:'इकाई', rotation:'घुमाव', resetModel:'मॉडल रीसेट करें', unsupported:'इस स्थानीय पूर्वावलोकन में यह इंटरैक्टिव दृश्य उपलब्ध नहीं है। विवरण पढ़ सकते हैं।', lineDescription:(min,max,parts,value)=>`${min} से ${max} तक संख्या रेखा, ${parts} बराबर भागों में विभाजित। चयनित मान ${value}।`, parts:(value,total)=>`चयनित बराबर भाग: ${total} में से ${value}`, value:'मान', resetLine:'संख्या रेखा रीसेट करें', table:'स्रोत के मान और गणना किया गया औसत', sample:'नमूना', mean:'औसत', cause:'ये मान लिखे गए नमूने का वर्णन करते हैं। केवल चार्ट या औसत से कारण सिद्ध नहीं होता।',
  loading:'निर्धारित अध्याय और उद्देश्य पढ़े जा रहे हैं…', unavailable:'निर्धारित रूपरेखा उपलब्ध नहीं है', retry:'रूपरेखा फिर लोड करें', title:'आपकी निर्धारित सीखने की रूपरेखा', intro:'यहाँ केवल शिक्षक द्वारा निर्धारित स्रोत की प्रतियाँ हैं। यह पूरी पुस्तक या अनिर्धारित अध्याय पूरे होने का दावा नहीं है। स्रोत संस्करण अलग रहते हैं; उत्तर और शिक्षक की प्रतिक्रिया ज्ञान का अंक नहीं हैं।', find:'निर्धारित अध्याय या उद्देश्य खोजें', unreadable:count=>`${count} निर्धारित स्रोत प्रतियाँ पढ़ी नहीं जा सकीं। मूल रिकॉर्ड सुरक्षित हैं।`, retrySources:'निर्धारित स्रोत फिर लोड करें', version:'संस्करण', sourceSection:'स्रोत का खंड', reviewed:'संस्था द्वारा समीक्षा की गई प्रति', authored:'लिखा गया नमूना', sourced:'स्रोत आधारित पाठ्यक्रम', submitted:'शिक्षक की समीक्षा के लिए जमा', graded:'शिक्षक द्वारा लौटाया गया', revision_requested:'संशोधन माँगा गया', 'not-submitted':'कोई उत्तर जमा नहीं है', returned:'शिक्षक द्वारा लौटाया गया', savedStatus:'शिक्षक की सहेजी गई स्थिति', assignment:'निर्धारित काम', prerequisite:'पूर्वशर्त का मार्गदर्शन', reviewTeacher:'ज़रूरत हो तो शिक्षक के साथ समीक्षा करें।', open:'निर्धारित उद्देश्य खोलें', ask:'निर्धारित स्रोत के बारे में पूछें', practice:'निर्धारित स्रोत का अभ्यास करें', unmapped:'संलग्न उद्देश्य के बिना निर्धारित काम', unmappedIntro:'इनके निर्देश इस्तेमाल कर सकते हैं। अध्याय या पाठ्यक्रम का संबंध नहीं माना गया है।', noMatch:'कोई मिलता हुआ निर्धारित अध्याय या उद्देश्य नहीं है।', unreadableEmpty:'पढ़ने योग्य संलग्न उद्देश्य उपलब्ध नहीं है। मूल काम देखने के लिए कक्षा का काम खोलें।', empty:'अभी कोई स्रोत उद्देश्य निर्धारित नहीं किया गया है। आपका अपना सीखना उपलब्ध है।', clear:'रूपरेखा की खोज साफ़ करें', fallbackChapter:'निर्धारित स्रोत उद्देश्य', published:'प्रकाशित', draft:'मसौदा', archived:'संग्रहीत', closed:'बंद', cancelled:'रद्द', scheduled:'निर्धारित समय', unknownAssignment:'काम की सहेजी गई स्थिति',
 },
 bn: {
  representation:'ধারণার দৃশ্য', another:'ধারণাটি অন্যভাবে দেখুন', temporary:'এই দৃশ্য এই পৃষ্ঠাতেই থাকে। এটি সংরক্ষিত চেষ্টা বা শেখার প্রমাণ তৈরি করে না।', saved:'আপনার দৃশ্য এই শেখার কাজের সঙ্গে থাকে। এটি দেখলে উত্তর সঠিক বলে গণ্য হয় না।', mode:'দৃশ্যের ধরন', cube:'ইন্টার‌্যাক্টিভ 3D', line:'ইন্টার‌্যাক্টিভ সংখ্যারেখা', chart:'চার্ট দেখুন', description:'বিবরণ পড়ুন', saveError:'দৃশ্য সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।', cubeDescription:(side,volume,rotation)=>`${side} একক বাহু ও ${volume} ঘন একক আয়তনের ঘনক, ${rotation} ডিগ্রি ঘোরানো`, growth:'ঘনক তিন দিকে বাড়ে। আয়তন = বাহু × বাহু × বাহু।', cubic:'ঘন একক', side:'বাহুর দৈর্ঘ্য', units:'একক', rotation:'ঘূর্ণন', resetModel:'মডেল রিসেট করুন', unsupported:'এই স্থানীয় প্রিভিউতে এই ইন্টার‌্যাক্টিভ দৃশ্য উপলব্ধ নেই। বিবরণ পড়া যায়।', lineDescription:(min,max,parts,value)=>`${min} থেকে ${max} পর্যন্ত সংখ্যারেখা, ${parts} সমান ভাগে বিভক্ত। নির্বাচিত মান ${value}।`, parts:(value,total)=>`নির্বাচিত সমান ভাগ: ${total}-এর মধ্যে ${value}`, value:'মান', resetLine:'সংখ্যারেখা রিসেট করুন', table:'উৎসের মান ও গণনা করা গড়', sample:'নমুনা', mean:'গড়', cause:'এই মানগুলো লেখা নমুনার বর্ণনা দেয়। শুধু চার্ট বা গড় থেকে কারণ প্রমাণিত হয় না।',
  loading:'নির্ধারিত অধ্যায় ও উদ্দেশ্য পড়া হচ্ছে…', unavailable:'নির্ধারিত রূপরেখা উপলব্ধ নেই', retry:'রূপরেখা আবার লোড করুন', title:'আপনার নির্ধারিত শেখার রূপরেখা', intro:'শুধু শিক্ষক যে উৎসের কপি নির্ধারণ করেছেন তা দেখানো হয়। এটি পুরো বই বা অনির্ধারিত অধ্যায় সম্পূর্ণ হওয়ার দাবি নয়। উৎসের সংস্করণ আলাদা থাকে; উত্তর ও শিক্ষকের প্রতিক্রিয়ার অবস্থা জ্ঞানের নম্বর নয়।', find:'নির্ধারিত অধ্যায় বা উদ্দেশ্য খুঁজুন', unreadable:count=>`${count}টি নির্ধারিত উৎসের কপি পড়া যায়নি। মূল রেকর্ড রাখা হয়েছে।`, retrySources:'নির্ধারিত উৎস আবার লোড করুন', version:'সংস্করণ', sourceSection:'উৎসের অংশ', reviewed:'প্রতিষ্ঠান দ্বারা পর্যালোচিত কপি', authored:'লেখা নমুনা', sourced:'উৎসভিত্তিক পাঠ্যক্রম', submitted:'শিক্ষকের পর্যালোচনার জন্য জমা', graded:'শিক্ষক ফেরত দিয়েছেন', revision_requested:'সংশোধন চাওয়া হয়েছে', 'not-submitted':'কোনো উত্তর জমা নেই', returned:'শিক্ষক ফেরত দিয়েছেন', savedStatus:'শিক্ষকের সংরক্ষিত অবস্থা', assignment:'নির্ধারিত কাজ', prerequisite:'পূর্বশর্তের নির্দেশনা', reviewTeacher:'প্রয়োজনে শিক্ষকের সঙ্গে পর্যালোচনা করুন।', open:'নির্ধারিত উদ্দেশ্য খুলুন', ask:'নির্ধারিত উৎস সম্পর্কে জিজ্ঞাসা করুন', practice:'নির্ধারিত উৎসের অনুশীলন করুন', unmapped:'সংযুক্ত উদ্দেশ্য ছাড়া নির্ধারিত কাজ', unmappedIntro:'এগুলোর নির্দেশ ব্যবহার করা যায়। অধ্যায় বা পাঠ্যক্রমের সম্পর্ক ধরে নেওয়া হয়নি।', noMatch:'মিলে যাওয়া নির্ধারিত অধ্যায় বা উদ্দেশ্য নেই।', unreadableEmpty:'পড়ার উপযোগী সংযুক্ত উদ্দেশ্য নেই। মূল কাজ দেখতে শ্রেণির কাজ খুলুন।', empty:'এখনো কোনো উৎসের উদ্দেশ্য নির্ধারণ করা হয়নি। আপনার নিজের শেখা উপলব্ধ আছে।', clear:'রূপরেখার অনুসন্ধান মুছুন', fallbackChapter:'নির্ধারিত উৎসের উদ্দেশ্য', published:'প্রকাশিত', draft:'খসড়া', archived:'সংরক্ষিত', closed:'বন্ধ', cancelled:'বাতিল', scheduled:'সময় নির্ধারিত', unknownAssignment:'কাজের সংরক্ষিত অবস্থা',
 },
};
export function learningSurfaceCopy(locale) { return copy[locale] || copy.en; }

const objectiveCopy={
 en:{attached:'Attached learning objective',title:'Learning objective',source:'Assigned objective source',level:'Level',retained:'This assigned copy retains its source version. Teacher review does not establish independent curriculum approval.',prerequisites:'Prerequisites in this assigned source',guidance:'Review these with your teacher if needed. This list does not assert that you have completed them.',noVisual:'No authored visual is available for this objective. The explanation remains usable.',criteria:'Assigned review criteria',reviewed:'Organization-reviewed objective · local copy',languages:{en:'English',hi:'Hindi',bn:'Bengali'}},
 hi:{attached:'संलग्न सीखने का उद्देश्य',title:'सीखने का उद्देश्य',source:'निर्धारित उद्देश्य का स्रोत',level:'स्तर',retained:'यह निर्धारित प्रति अपने स्रोत का संस्करण रखती है। शिक्षक की समीक्षा स्वतंत्र पाठ्यक्रम स्वीकृति नहीं है।',prerequisites:'इस निर्धारित स्रोत की पूर्वशर्तें',guidance:'ज़रूरत हो तो शिक्षक के साथ इनकी समीक्षा करें। इस सूची का मतलब यह नहीं कि आपने इन्हें पूरा कर लिया है।',noVisual:'इस उद्देश्य के लिए लिखा गया दृश्य उपलब्ध नहीं है। व्याख्या पढ़ सकते हैं।',criteria:'निर्धारित समीक्षा के मानदंड',reviewed:'संस्था द्वारा समीक्षित उद्देश्य · स्थानीय प्रति',languages:{en:'अंग्रेज़ी',hi:'हिन्दी',bn:'बांग्ला'}},
 bn:{attached:'সংযুক্ত শেখার উদ্দেশ্য',title:'শেখার উদ্দেশ্য',source:'নির্ধারিত উদ্দেশ্যের উৎস',level:'স্তর',retained:'এই নির্ধারিত কপি তার উৎসের সংস্করণ রাখে। শিক্ষকের পর্যালোচনা স্বাধীন পাঠ্যক্রম অনুমোদন নয়।',prerequisites:'এই নির্ধারিত উৎসের পূর্বশর্ত',guidance:'প্রয়োজনে শিক্ষকের সঙ্গে এগুলো পর্যালোচনা করুন। এই তালিকা এগুলো সম্পূর্ণ করার দাবি করে না।',noVisual:'এই উদ্দেশ্যের জন্য লেখা দৃশ্য উপলব্ধ নেই। ব্যাখ্যা পড়া যায়।',criteria:'নির্ধারিত পর্যালোচনার মানদণ্ড',reviewed:'প্রতিষ্ঠান দ্বারা পর্যালোচিত উদ্দেশ্য · স্থানীয় কপি',languages:{en:'ইংরেজি',hi:'হিন্দি',bn:'বাংলা'}},
};
export function objectivePreviewCopy(locale) { return {...learningSurfaceCopy(locale),...(objectiveCopy[locale]||objectiveCopy.en)}; }
