import { guideCopy } from './guideCopy.js';

const entries = [
 ['Bridge activity unavailable','ब्रिज गतिविधि उपलब्ध नहीं है','ব্রিজ কার্যকলাপ অনুপলব্ধ'],
 ['Retry bridge activity','ब्रिज गतिविधि फिर खोलें','ব্রিজ কার্যকলাপ আবার খুলুন'],
 ['Reading the sourced bridge objective…','स्रोत का ब्रिज उद्देश्य पढ़ रहे हैं…','উৎসের ব্রিজ উদ্দেশ্য পড়া হচ্ছে…'],
 ['Continue across curriculum sources','पाठ्यक्रम स्रोतों के बीच आगे बढ़ें','পাঠ্যক্রমের উৎসগুলির মধ্যে এগিয়ে যান'],
 ['Your original work is retained','आपका मूल कार्य सुरक्षित है','আপনার মূল কাজ রাখা হয়েছে'],
 ['Resume its saved explanation, check, practice or project on the original source. Recorded answers and review dates are not moved to the new curriculum.','मूल स्रोत पर सहेजी व्याख्या, जाँच, अभ्यास या प्रोजेक्ट जारी रखें। दर्ज उत्तर और समीक्षा तिथियाँ नए पाठ्यक्रम में नहीं जाते।','মূল উৎসে সংরক্ষিত ব্যাখ্যা, যাচাই, অনুশীলন বা প্রকল্প চালিয়ে যান। নথিভুক্ত উত্তর ও পর্যালোচনার তারিখ নতুন পাঠ্যক্রমে যায় না।'],
 ['Saved step:','सहेजा चरण:','সংরক্ষিত ধাপ:'],
 ['Resume original work','मूल कार्य जारी रखें','মূল কাজ চালিয়ে যান'],
 ['No reviewed equivalent original activity is available for this objective. Your other saved work remains accessible from Home.','इस उद्देश्य के लिए समीक्षा की गई समान मूल गतिविधि उपलब्ध नहीं है। अन्य सहेजा कार्य Home से उपलब्ध है।','এই উদ্দেশ্যে পর্যালোচিত সমতুল্য মূল কার্যকলাপ নেই। আপনার অন্য সংরক্ষিত কাজ Home থেকে পাওয়া যায়।'],
 ['Open the reviewed objective','समीक्षित उद्देश्य खोलें','পর্যালোচিত উদ্দেশ্য খুলুন'],
 ['New-source work starts with its own explanation and checks. An existing unfinished activity on this exact source resumes its saved step. Prior mastery, answers, question drafts and project reviews are not copied.','नए स्रोत का कार्य अपनी व्याख्या और जाँच से शुरू होता है। इसी स्रोत की अधूरी गतिविधि सहेजे चरण से जारी होती है। पुरानी दक्षता, उत्तर, प्रश्न ड्राफ़्ट और प्रोजेक्ट समीक्षाएँ कॉपी नहीं होते।','নতুন উৎসের কাজ নিজের ব্যাখ্যা ও যাচাই দিয়ে শুরু হয়। একই উৎসের অসমাপ্ত কার্যকলাপ সংরক্ষিত ধাপ থেকে চলে। আগের দক্ষতা, উত্তর, প্রশ্নের খসড়া ও প্রকল্প পর্যালোচনা কপি হয় না।'],
 ['Prior recorded readiness; review remains available','पहले दर्ज तैयारी; समीक्षा उपलब्ध है','আগে নথিভুক্ত প্রস্তুতি; পর্যালোচনা উপলব্ধ'],
 ['Review this prerequisite before starting','शुरू करने से पहले यह पूर्वापेक्षा देखें','শুরুর আগে এই পূর্বশর্ত পর্যালোচনা করুন'],
 ['Opening reviewed objective…','समीक्षित उद्देश्य खोल रहे हैं…','পর্যালোচিত উদ্দেশ্য খোলা হচ্ছে…'],
 ['Start or resume reviewed objective','समीक्षित उद्देश्य शुरू या जारी करें','পর্যালোচিত উদ্দেশ্য শুরু বা চালিয়ে যান'],
 ['Restoring your saved learning activity…','सहेजी अध्ययन गतिविधि वापस ला रहे हैं…','সংরক্ষিত শেখার কার্যকলাপ ফেরানো হচ্ছে…'],
 ['Opening your learning outline…','अध्ययन रूपरेखा खोल रहे हैं…','শেখার রূপরেখা খোলা হচ্ছে…'],
 ['Opening your learning workspace…','अध्ययन कार्यक्षेत्र खोल रहे हैं…','শেখার কর্মক্ষেত্র খোলা হচ্ছে…'],
 ['Saved learning unavailable','सहेजा अध्ययन उपलब्ध नहीं है','সংরক্ষিত শেখা অনুপলব্ধ'],
 ['Original records remain on this device. This page will not replace them or record an answer while they are unreadable. Restore a valid saved copy before retrying.','मूल रिकॉर्ड इस डिवाइस पर हैं। जब तक वे पढ़े नहीं जा सकते, यह पृष्ठ उन्हें बदलता या उत्तर दर्ज नहीं करता। फिर प्रयास करने से पहले मान्य सहेजी प्रति वापस लाएँ।','মূল রেকর্ড এই ডিভাইসে আছে। পড়া না গেলে এই পাতা তা বদলায় না বা উত্তর নথিভুক্ত করে না। আবার চেষ্টার আগে বৈধ সংরক্ষিত কপি ফেরান।'],
 ['Export current activity view','वर्तमान गतिविधि दृश्य निर्यात करें','বর্তমান কার্যকলাপের দৃশ্য রপ্তানি করুন'],
 ['Retry saved learning','सहेजा अध्ययन फिर खोलें','সংরক্ষিত শেখা আবার খুলুন'],
 ['Saved activity changed','सहेजी गतिविधि बदल गई है','সংরক্ষিত কার্যকলাপ বদলেছে'],
 ['Saved source changed','सहेजा स्रोत बदल गया है','সংরক্ষিত উৎস বদলেছে'],
 ['Your original activity is kept. Open the learning outline to start a separate activity from the current reviewed source.','आपकी मूल गतिविधि सुरक्षित है। वर्तमान समीक्षित स्रोत से अलग गतिविधि शुरू करने के लिए अध्ययन रूपरेखा खोलें।','আপনার মূল কার্যকলাপ রাখা হয়েছে। বর্তমান পর্যালোচিত উৎস থেকে আলাদা কার্যকলাপ শুরু করতে শেখার রূপরেখা খুলুন।'],
 ['A newer version of this activity is saved. Reload it to continue with the latest language, view and recorded answers.','इस गतिविधि का नया संस्करण सहेजा है। नवीनतम भाषा, दृश्य और दर्ज उत्तरों के साथ जारी रखने के लिए इसे फिर खोलें।','এই কার্যকলাপের নতুন সংস্করণ সংরক্ষিত। সর্বশেষ ভাষা, দৃশ্য ও নথিভুক্ত উত্তর নিয়ে চালিয়ে যেতে আবার খুলুন।'],
 ['Review local data and export','स्थानीय डेटा देखें और निर्यात करें','স্থানীয় তথ্য দেখুন ও রপ্তানি করুন'],
 ['Saving your place…','आपका स्थान सहेज रहे हैं…','আপনার অবস্থান সংরক্ষণ করা হচ্ছে…'],
 ['Your saved work is kept.','आपका सहेजा कार्य सुरक्षित है।','আপনার সংরক্ষিত কাজ রাখা হয়েছে।'],
 ['Open my outline','मेरी रूपरेखा खोलें','আমার রূপরেখা খুলুন'],
 ['Learning activity unavailable','अध्ययन गतिविधि उपलब्ध नहीं है','শেখার কার্যকলাপ অনুপলব্ধ'],
 ['Open your outline to choose an available concept. This link did not create or score an activity.','उपलब्ध अवधारणा चुनने के लिए रूपरेखा खोलें। इस लिंक ने गतिविधि बनाई या अंक नहीं दिए।','উপলব্ধ ধারণা বাছতে রূপরেখা খুলুন। এই লিঙ্ক কার্যকলাপ তৈরি বা নম্বর দেয়নি।'],
 ['Open learning outline','अध्ययन रूपरेखा खोलें','শেখার রূপরেখা খুলুন'],
 ['Retry activity','गतिविधि फिर खोलें','কার্যকলাপ আবার খুলুন'],
 ['Saved learning activity','सहेजी अध्ययन गतिविधि','সংরক্ষিত শেখার কার্যকলাপ'],
 ['Teaching content unavailable','शिक्षण सामग्री उपलब्ध नहीं है','শিক্ষাদানের বিষয়বস্তু অনুপলব্ধ'],
 ['This activity is still saved locally. No check, practice or mastery result was added while the content was unavailable.','यह गतिविधि स्थानीय रूप से सहेजी है। सामग्री अनुपलब्ध होने पर कोई जाँच, अभ्यास या दक्षता परिणाम नहीं जोड़ा गया।','কার্যকলাপটি স্থানীয়ভাবে সংরক্ষিত। বিষয়বস্তু অনুপলব্ধ থাকাকালে যাচাই, অনুশীলন বা দক্ষতার ফল যোগ হয়নি।'],
 ['Ask about this activity','इस गतिविधि के बारे में पूछें','এই কার্যকলাপ সম্পর্কে জিজ্ঞাসা করুন'],
 ['Retry content','सामग्री फिर खोलें','বিষয়বস্তু আবার খুলুন'],
 ['Learning outline','अध्ययन रूपरेखा','শেখার রূপরেখা'],
 ['Authored sample · Not official curriculum','लिखित नमूना · आधिकारिक पाठ्यक्रम नहीं','রচিত নমুনা · সরকারি পাঠ্যক্রম নয়'],
 ['Provisional learning outline','अस्थायी अध्ययन रूपरेखा','অস্থায়ী শেখার রূপরেখা'],
 ['Saved curriculum · source details unavailable','सहेजा पाठ्यक्रम · स्रोत विवरण अनुपलब्ध','সংরক্ষিত পাঠ্যক্রম · উৎসের বিবরণ অনুপলব্ধ'],
 ['Saved curriculum · source details unavailable.','सहेजा पाठ्यक्रम · स्रोत विवरण अनुपलब्ध।','সংরক্ষিত পাঠ্যক্রম · উৎসের বিবরণ অনুপলব্ধ।'],
 ['Your place is saved locally. Understanding is checked before guided practice and building.','आपका स्थान स्थानीय रूप से सहेजा है। निर्देशित अभ्यास और निर्माण से पहले समझ जाँची जाती है।','আপনার অবস্থান স্থানীয়ভাবে সংরক্ষিত। নির্দেশিত অনুশীলন ও তৈরির আগে বোঝাপড়া যাচাই হয়।'],
 ['Teaching language','शिक्षण भाषा','শিক্ষাদানের ভাষা'],
 ['Learning unit stages','अध्ययन इकाई के चरण','শেখার এককের ধাপ'],
 ['Teaching service response received.','शिक्षण सेवा का उत्तर मिला।','শিক্ষাদানের সেবার উত্তর পাওয়া গেছে।'],
 ['Understand one idea','एक विचार समझें','একটি ধারণা বুঝুন'],
 ['Source: connected teaching adapter.','स्रोत: जुड़ा शिक्षण अडैप्टर।','উৎস: সংযুক্ত শিক্ষাদানের অ্যাডাপ্টার।'],
 ['Source: explicitly authored sample content, not a generated model answer.','स्रोत: स्पष्ट रूप से लिखित नमूना सामग्री, मॉडल का बनाया उत्तर नहीं।','উৎস: স্পষ্টভাবে রচিত নমুনা বিষয়বস্তু, মডেলের তৈরি উত্তর নয়।'],
 ['Source details are unavailable for this saved content.','इस सहेजी सामग्री का स्रोत विवरण उपलब्ध नहीं है।','এই সংরক্ষিত বিষয়বস্তুর উৎসের বিবরণ অনুপলব্ধ।'],
 ['Check my understanding','मेरी समझ जाँचें','আমার বোঝাপড়া যাচাই করুন'],
 ['An explanation is unavailable in this language right now. Your position is saved; no understanding check has been scored.','इस भाषा में व्याख्या अभी उपलब्ध नहीं है। आपका स्थान सहेजा है; समझ की जाँच पर अंक नहीं दिए गए।','এই ভাষায় ব্যাখ্যা এখন অনুপলব্ধ। আপনার অবস্থান সংরক্ষিত; বোঝাপড়ার যাচাইয়ে নম্বর দেওয়া হয়নি।'],
 ['Request an explanation in your selected teaching language. If the service is disconnected, available authored sample content can still be used.','चुनी शिक्षण भाषा में व्याख्या माँगें। सेवा न जुड़ी होने पर उपलब्ध लिखित नमूना सामग्री इस्तेमाल हो सकती है।','বাছা শিক্ষাদানের ভাষায় ব্যাখ্যা চান। সেবা সংযুক্ত না থাকলে উপলব্ধ রচিত নমুনা ব্যবহার করা যায়।'],
 ['Request an explanation in your selected teaching language. If no sourced explanation is available while the teaching service is disconnected, this step cannot advance.','चुनी शिक्षण भाषा में व्याख्या माँगें। सेवा न जुड़ी होने और स्रोत की व्याख्या अनुपलब्ध होने पर यह चरण आगे नहीं बढ़ सकता।','বাছা শিক্ষাদানের ভাষায় ব্যাখ্যা চান। সেবা বিচ্ছিন্ন ও উৎসের ব্যাখ্যা অনুপলব্ধ থাকলে এই ধাপ এগোতে পারে না।'],
 ['Retry teaching connection','शिक्षण कनेक्शन फिर आज़माएँ','শিক্ষাদানের সংযোগ আবার চেষ্টা করুন'],
 ['Start this learning unit','यह अध्ययन इकाई शुरू करें','এই শেখার একক শুরু করুন'],
 ['Ask a doubt instead','इसके बजाय प्रश्न पूछें','পরিবর্তে প্রশ্ন করুন'],
 ['Check understanding','समझ जाँचें','বোঝাপড়া যাচাই করুন'],
 ['Practice one step at a time','एक-एक चरण का अभ्यास करें','একবারে একটি ধাপ অনুশীলন করুন'],
 ['No assessment evidence yet','अभी आकलन का साक्ष्य नहीं है','এখনও মূল্যায়নের প্রমাণ নেই'],
 ['Selection saved as a private draft. It is scored only when you choose Check answer.','चयन निजी ड्राफ़्ट के रूप में सहेजा है। उत्तर जाँचें चुनने पर ही अंक दिए जाते हैं।','বাছাই ব্যক্তিগত খসড়া হিসেবে সংরক্ষিত। উত্তর যাচাই করুন বাছলেই নম্বর দেওয়া হয়।'],
 ['This selection is only on this page. Retry saving it before leaving, or keep the page open.','चयन केवल इस पृष्ठ पर है। छोड़ने से पहले फिर सहेजें या पृष्ठ खुला रखें।','বাছাই শুধু এই পাতায় আছে। যাওয়ার আগে আবার সংরক্ষণ করুন বা পাতা খোলা রাখুন।'],
 ['Check answer','उत्तर जाँचें','উত্তর যাচাই করুন'],
 ['Correct for this recorded check.','इस दर्ज जाँच के लिए सही।','এই নথিভুক্ত যাচাইয়ে সঠিক।'],
 ['Not yet. Review the idea and try a smaller step.','अभी नहीं। विचार देखें और छोटा चरण आज़माएँ।','এখনও নয়। ধারণা দেখুন ও ছোট ধাপ চেষ্টা করুন।'],
 ['Accuracy is evidence, not a claim of overall mastery.','सटीकता साक्ष्य है, पूरी दक्षता का दावा नहीं।','সঠিকতা প্রমাণ, সামগ্রিক দক্ষতার দাবি নয়।'],
 ['This check comes from the authored sample.','यह जाँच लिखित नमूने से है।','এই যাচাই রচিত নমুনা থেকে আসে।'],
 ['Continue practice','अभ्यास जारी रखें','অনুশীলন চালিয়ে যান'],
 ['Retry understanding check','समझ की जाँच फिर करें','বোঝাপড়ার যাচাই আবার করুন'],
 ['Review explanation and model','व्याख्या और मॉडल देखें','ব্যাখ্যা ও মডেল দেখুন'],
 ['Apply this in Build','इसे Build में लागू करें','এটি Build-এ প্রয়োগ করুন'],
 ['No verifiable question is available yet. Your progress has not been advanced or scored.','अभी सत्यापित प्रश्न उपलब्ध नहीं है। आपकी प्रगति आगे नहीं बढ़ी या अंक नहीं दिए गए।','এখনও যাচাইযোগ্য প্রশ্ন নেই। আপনার অগ্রগতি এগোয়নি বা নম্বর দেওয়া হয়নি।'],
 ['Review explanation','व्याख्या देखें','ব্যাখ্যা দেখুন'],
 ['Ask a doubt','प्रश्न पूछें','প্রশ্ন করুন'],
 ['Your application is recorded','आपका अनुप्रयोग दर्ज है','আপনার প্রয়োগ নথিভুক্ত'],
 ['Put the idea to work','विचार काम में लाएँ','ধারণাটি কাজে লাগান'],
 ['Open your project','अपना प्रोजेक्ट खोलें','আপনার প্রকল্প খুলুন'],
 ['Request project guidance','प्रोजेक्ट मार्गदर्शन माँगें','প্রকল্পের নির্দেশনা চান'],
 ['Review this concept again','यह अवधारणा फिर देखें','এই ধারণা আবার দেখুন'],
 ['A review opens a new learning activity. This project and its recorded evidence stay saved.','समीक्षा नई अध्ययन गतिविधि खोलती है। यह प्रोजेक्ट और दर्ज साक्ष्य सुरक्षित रहते हैं।','পর্যালোচনা নতুন শেখার কার্যকলাপ খোলে। এই প্রকল্প ও নথিভুক্ত প্রমাণ সংরক্ষিত থাকে।'],
 ['Continue to next concept','अगली अवधारणा पर बढ़ें','পরের ধারণায় এগিয়ে যান'],
 ['You reached the end of this available chapter','आप इस उपलब्ध अध्याय के अंत तक पहुँचे','আপনি এই উপলব্ধ অধ্যায়ের শেষে পৌঁছেছেন'],
 ['This records the activities shown here, not mastery of the whole subject.','यह यहाँ दिखाई गतिविधियाँ दर्ज करता है, पूरे विषय की दक्षता नहीं।','এটি এখানে দেখানো কার্যকলাপ নথিভুক্ত করে, পুরো বিষয়ের দক্ষতা নয়।'],
 ['Ask a doubt · keep my place','प्रश्न पूछें · मेरा स्थान रखें','প্রশ্ন করুন · আমার অবস্থান রাখুন'],
 ['Save and return Home','सहेजें और Home लौटें','সংরক্ষণ করে Home-এ ফিরুন'],
 ['Review and strengthen','समीक्षा करें और मज़बूत बनाएँ','পর্যালোচনা করুন ও মজবুত করুন'],
 ['Explore and understand','खोजें और समझें','অন্বেষণ করুন ও বুঝুন'],
 ['Your next practice','आपका अगला अभ्यास','আপনার পরের অনুশীলন'],
 ['Your learning outline','आपकी अध्ययन रूपरेखा','আপনার শেখার রূপরেখা'],
 ['Revisit what you have already checked. Your results and next step stay connected to Learn.','पहले जाँची बातों पर लौटें। परिणाम और अगला चरण Learn से जुड़े रहते हैं।','আগে যাচাই করা বিষয় দেখুন। ফল ও পরের ধাপ Learn-এর সঙ্গে যুক্ত থাকে।'],
 ['Connect a skill goal to concepts, practice and portfolio work.','कौशल लक्ष्य को अवधारणाओं, अभ्यास और पोर्टफोलियो कार्य से जोड़ें।','দক্ষতার লক্ষ্য ধারণা, অনুশীলন ও পোর্টফোলিওর কাজের সঙ্গে যুক্ত করুন।'],
 ['Subjects become chapters, concepts, checks and projects—with your place kept at every step.','विषय अध्याय, अवधारणा, जाँच और प्रोजेक्ट बनते हैं—हर चरण पर आपका स्थान सुरक्षित रहता है।','বিষয় থেকে অধ্যায়, ধারণা, যাচাই ও প্রকল্প হয়—প্রতিটি ধাপে আপনার অবস্থান রাখা হয়।'],
 ['This outline uses your class subject. Assignments and teacher feedback remain in Classes.','यह रूपरेखा आपकी कक्षा का विषय इस्तेमाल करती है। असाइनमेंट और शिक्षक प्रतिक्रिया Classes में रहते हैं।','এই রূপরেখা আপনার ক্লাসের বিষয় ব্যবহার করে। অ্যাসাইনমেন্ট ও শিক্ষকের মতামত Classes-এ থাকে।'],
 ['Ready to revisit','फिर देखने के लिए तैयार','আবার দেখার জন্য প্রস্তুত'],
 ['Due for review','समीक्षा का समय है','পর্যালোচনার সময় হয়েছে'],
 ['Review available','समीक्षा उपलब्ध है','পর্যালোচনা উপলব্ধ'],
 ['Start review','समीक्षा शुरू करें','পর্যালোচনা শুরু করুন'],
 ['Resume practice','अभ्यास जारी करें','অনুশীলন চালিয়ে যান'],
 ['Finish a comprehension check in Learn first. No weakness is inferred from an empty history.','पहले Learn में समझ की जाँच पूरी करें। खाली इतिहास से कमजोरी नहीं मानी जाती।','আগে Learn-এ বোঝাপড়ার যাচাই শেষ করুন। খালি ইতিহাস থেকে দুর্বলতা অনুমান করা হয় না।'],
 ['Start in Learn','Learn में शुरू करें','Learn-এ শুরু করুন'],
 ['Choose a capability','क्षमता चुनें','সক্ষমতা বাছুন'],
 ['Choose a subject','विषय चुनें','বিষয় বাছুন'],
 ['Skill or capability (optional)','कौशल या क्षमता (वैकल्पिक)','দক্ষতা বা সক্ষমতা (ঐচ্ছিক)'],
 ['Subject (optional)','विषय (वैकल्पिक)','বিষয় (ঐচ্ছিক)'],
 ['For example, data interpretation','जैसे, डेटा की व्याख्या','যেমন, তথ্য ব্যাখ্যা'],
 ['For example, mathematics','जैसे, गणित','যেমন, গণিত'],
 ['Add goal and level','लक्ष्य और स्तर जोड़ें','লক্ষ্য ও স্তর যোগ করুন'],
 ['Add board and class','बोर्ड और कक्षा जोड़ें','বোর্ড ও শ্রেণি যোগ করুন'],
 ['Goal or industry (optional)','लक्ष्य या उद्योग (वैकल्पिक)','লক্ষ্য বা শিল্প (ঐচ্ছিক)'],
 ['Board (optional)','बोर्ड (वैकल्पिक)','বোর্ড (ঐচ্ছিক)'],
 ['Level (optional)','स्तर (वैकल्पिक)','স্তর (ঐচ্ছিক)'],
 ['Class / level (optional)','कक्षा / स्तर (वैकल्पिक)','শ্রেণি / স্তর (ঐচ্ছিক)'],
 ['Subject chapters','विषय के अध्याय','বিষয়ের অধ্যায়'],
 ['Provisional · The database has no matching outline yet. Your place and data-gap request are saved locally.','अस्थायी · डेटाबेस में मिलती रूपरेखा अभी नहीं है। आपका स्थान और डेटा की कमी का अनुरोध स्थानीय रूप से सहेजे हैं।','অস্থায়ী · ডেটাবেসে মেলা রূপরেখা এখনও নেই। আপনার অবস্থান ও তথ্যের ঘাটতির অনুরোধ স্থানীয়ভাবে সংরক্ষিত।'],
 ['Chapter learning path','अध्याय का अध्ययन पथ','অধ্যায়ের শেখার পথ'],
 ['Optional chapter name','वैकल्पिक अध्याय नाम','ঐচ্ছিক অধ্যায়ের নাম'],
 ['Save name','नाम सहेजें','নাম সংরক্ষণ করুন'],
 ['Starting concept','शुरुआती अवधारणा','শুরুর ধারণা'],
 ['Open previous saved topics and examples','पहले सहेजे विषय और उदाहरण खोलें','আগে সংরক্ষিত বিষয় ও উদাহরণ খুলুন'],
 ['Try authored learning sample','लिखित अध्ययन नमूना आज़माएँ','রচিত শেখার নমুনা চেষ্টা করুন'],
 ['Try authored workplace sample','लिखित कार्यस्थल नमूना आज़माएँ','রচিত কর্মস্থলের নমুনা চেষ্টা করুন'],
 ['No subject yet? A numbered provisional outline keeps your place until sourced content is available. Teaching responses require a connected model.','अभी विषय नहीं है? स्रोत सामग्री मिलने तक क्रमांकित अस्थायी रूपरेखा आपका स्थान रखती है। शिक्षण उत्तरों के लिए जुड़ा मॉडल चाहिए।','এখনও বিষয় নেই? উৎসের বিষয়বস্তু আসা পর্যন্ত সংখ্যাযুক্ত অস্থায়ী রূপরেখা আপনার অবস্থান রাখে। শিক্ষাদানের উত্তরে সংযুক্ত মডেল লাগে।'],
 ['No capability yet? A numbered provisional outline keeps your place until sourced content is available. Teaching responses require a connected model.','अभी क्षमता नहीं है? स्रोत सामग्री मिलने तक क्रमांकित अस्थायी रूपरेखा आपका स्थान रखती है। शिक्षण उत्तरों के लिए जुड़ा मॉडल चाहिए।','এখনও সক্ষমতা নেই? উৎসের বিষয়বস্তু আসা পর্যন্ত সংখ্যাযুক্ত অস্থায়ী রূপরেখা আপনার অবস্থান রাখে। শিক্ষাদানের উত্তরে সংযুক্ত মডেল লাগে।'],
 ['{started} of {total} concepts started. This counts activity, not mastery.','{total} में से {started} अवधारणाएँ शुरू हुईं। यह गतिविधि गिनता है, दक्षता नहीं।','{total}টি ধারণার মধ্যে {started}টি শুরু হয়েছে। এটি কার্যকলাপ গোনে, দক্ষতা নয়।'],
 ['{count} recorded answers','{count} दर्ज उत्तर','{count}টি নথিভুক্ত উত্তর'],
 ['{count} prerequisites','{count} पूर्वापेक्षाएँ','{count}টি পূর্বশর্ত'],
 ['{correct}/{total} recorded correct answers','{correct}/{total} दर्ज सही उत्तर','{correct}/{total}টি নথিভুক্ত সঠিক উত্তর'],
 ['Difficulty {level} / 5','कठिनाई {level} / 5','কঠিনতা {level} / 5'],
 ['Learning alongside {name}','{name} के साथ अध्ययन','{name}-এর সঙ্গে শেখা'],
 ['{title} learning path','{title} अध्ययन पथ','{title} শেখার পথ'],
 ['{title} · chapter path','{title} · अध्याय पथ','{title} · অধ্যায়ের পথ'],
 ['Next: {title}','अगला: {title}','পরের: {title}'],
 ['Next review {date}','अगली समीक्षा {date}','পরের পর্যালোচনা {date}'],
 ['Review {count} saved attempts','{count} सहेजे प्रयास देखें','{count}টি সংরক্ষিত প্রচেষ্টা দেখুন'],
 ['Understanding check','समझ की जाँच','বোঝাপড়ার যাচাই'],
 ['Your answer:','आपका उत्तर:','আপনার উত্তর:'],
 ['Recorded correct','सही दर्ज','সঠিক নথিভুক্ত'],
 ['Recorded for review','समीक्षा के लिए दर्ज','পর্যালোচনার জন্য নথিভুক্ত'],
 ['Authored sample','लिखित नमूना','রচিত নমুনা'],
 ['Sourced question','स्रोत का प्रश्न','উৎসের প্রশ্ন'],
 ['Prerequisite details are unavailable. You can explore this concept, but readiness cannot be confirmed from this outline.','पूर्वापेक्षा विवरण उपलब्ध नहीं हैं। आप अवधारणा खोज सकते हैं; रूपरेखा से तैयारी की पुष्टि नहीं हो सकती।','পূর্বশর্তের বিবরণ অনুপলব্ধ। আপনি ধারণা অন্বেষণ করতে পারেন; রূপরেখা থেকে প্রস্তুতি নিশ্চিত করা যায় না।'],
 ['Prerequisite path','पूर्वापेक्षा पथ','পূর্বশর্তের পথ'],
 ['Suggested first: review earlier concepts','पहले सुझाया: पिछली अवधारणाएँ देखें','আগে প্রস্তাবিত: আগের ধারণাগুলি দেখুন'],
 ['Earlier concepts have recorded secure evidence','पिछली अवधारणाओं में मज़बूत साक्ष्य दर्ज हैं','আগের ধারণায় দৃঢ় প্রমাণ নথিভুক্ত আছে'],
 ['Revisit','फिर देखें','আবার দেখুন'],
 ['You can still explore this concept now. A prerequisite is a guide, not a mastery claim.','आप अभी भी यह अवधारणा खोज सकते हैं। पूर्वापेक्षा मार्गदर्शन है, दक्षता का दावा नहीं।','আপনি এখনই এই ধারণা অন্বেষণ করতে পারেন। পূর্বশর্ত নির্দেশনা, দক্ষতার দাবি নয়।'],
 ['Attempt details unavailable','प्रयास विवरण अनुपलब्ध','প্রচেষ্টার বিবরণ অনুপলব্ধ'],
 ['Sourced curriculum · {provider} · version {version}','स्रोत का पाठ्यक्रम · {provider} · संस्करण {version}','উৎসের পাঠ্যক্রম · {provider} · সংস্করণ {version}'],
 ['Source: {provider} · version {version}.','स्रोत: {provider} · संस्करण {version}।','উৎস: {provider} · সংস্করণ {version}।'],
 ['Sourced from {provider} · version {version}.','स्रोत {provider} · संस्करण {version}।','উৎস {provider} · সংস্করণ {version}।'],
 ['{count} authored sample activities · not official content coverage.','{count} लिखित नमूना गतिविधियाँ · आधिकारिक सामग्री कवरेज नहीं।','{count}টি রচিত নমুনা কার্যকলাপ · সরকারি বিষয়বস্তুর পূর্ণ পরিসর নয়।'],
 ['Teaching content not loaded in {language}','{language} में शिक्षण सामग्री नहीं खुली','{language}-এ শিক্ষাদানের বিষয়বস্তু খোলেনি'],
 ['The saved outline is in {sourceLanguage}. Teaching content in {language} is shown only when it is actually available.','सहेजी रूपरेखा {sourceLanguage} में है। {language} में शिक्षण सामग्री तभी दिखती है जब उपलब्ध हो।','সংরক্ষিত রূপরেখা {sourceLanguage}-এ। {language}-এ বিষয়বস্তু উপলব্ধ থাকলেই দেখা যায়।'],
 ['This concept’s saved teaching content is not loaded in {language}. Your place and evidence remain saved. A teaching response requires the connected model.','इस अवधारणा की सामग्री {language} में नहीं खुली। आपका स्थान और साक्ष्य सहेजे हैं। शिक्षण उत्तर के लिए जुड़ा मॉडल चाहिए।','এই ধারণার বিষয়বস্তু {language}-এ খোলেনি। অবস্থান ও প্রমাণ সংরক্ষিত। শিক্ষাদানের উত্তরে সংযুক্ত মডেল লাগে।'],
 ['The outline text is in {language}.','रूपरेखा का पाठ {language} में है।','রূপরেখার পাঠ্য {language}-এ।'],
 ['Use available {language} teaching','उपलब्ध {language} शिक्षण इस्तेमाल करें','উপলব্ধ {language} শিক্ষাদান ব্যবহার করুন'],
 ['Saved teaching is not available in {language}. You can use the available source language above or request a connected teaching response.','सहेजा शिक्षण {language} में उपलब्ध नहीं है। ऊपर उपलब्ध स्रोत भाषा चुनें या जुड़े शिक्षण का उत्तर माँगें।','সংরক্ষিত শিক্ষাদান {language}-এ নেই। উপরে উপলব্ধ উৎসের ভাষা ব্যবহার করুন বা সংযুক্ত শিক্ষাদানের উত্তর চান।'],
 ['· version','· संस्करण','· সংস্করণ'],
];
entries.push(['Practice','अभ्यास','অনুশীলন'],['Open','खोलें','খুলুন'],['Check','जाँचें','যাচাই করুন'],['No evidence yet','अभी साक्ष्य नहीं है','এখনও প্রমাণ নেই']);
const messages = Object.fromEntries(entries.map(([en, hi, bn]) => [en, { en, hi, bn }]));
export const learningCopy = locale => (key, params = {}) =>
 (messages[key]?.[locale] || guideCopy(locale)(key)).replace(/\{(\w+)\}/g, (match, name) => String(params[name] ?? match));

/** Imported dates must not break the saved-work view. */
export function learningDate(value, locale = 'en') {
 const date = typeof value === 'string' || typeof value === 'number' ? new Date(value) : null;
 if (!date || !Number.isFinite(date.getTime())) return learningCopy(locale)('Unavailable');
 return new Intl.DateTimeFormat(['en', 'hi', 'bn'].includes(locale) ? locale : 'en', { dateStyle: 'medium' }).format(date);
}
