import { learningCopy } from './learningCopy.js';
const entries = [
 ['Learn','सीखें','শিখুন'],
 ['Follow your curiosity. Understand an idea, then put it to work.','जिज्ञासा का अनुसरण करें। विचार समझें, फिर काम में लाएँ।','কৌতূহল অনুসরণ করুন। ধারণা বুঝে কাজে লাগান।'],
 ['Add topic','विषय जोड़ें','বিষয় যোগ করুন'],
 ['Loading your lessons','आपके पाठ खोल रहे हैं','আপনার পাঠ খোলা হচ্ছে'],
 ['Your lessons could not be loaded.','आपके पाठ नहीं खुल सके।','আপনার পাঠ খোলা যায়নি।'],
 ['Try again','फिर प्रयास करें','আবার চেষ্টা করুন'],
 ['Learning area','अध्ययन क्षेत्र','শেখার ক্ষেত্র'],
 ['Explore in 3D · Interactive example','3D में खोजें · इंटरैक्टिव उदाहरण','3D-তে অন্বেষণ করুন · ইন্টারঅ্যাক্টিভ উদাহরণ'],
 ['See how a small change grows.','देखें छोटा बदलाव कैसे बढ़ता है।','দেখুন ছোট পরিবর্তন কীভাবে বাড়ে।'],
 ['Rotate a cube, change its size, and discover volume.','घन घुमाएँ, आकार बदलें और आयतन खोजें।','ঘনক ঘোরান, আকার বদলান ও আয়তন জানুন।'],
 ['Open lab →','प्रयोगशाला खोलें →','ল্যাব খুলুন →'],
 ['Search topics','विषय खोजें','বিষয় খুঁজুন'],
 ['Topic status','विषय की स्थिति','বিষয়ের অবস্থা'],
 ['No matching topics','मिलते विषय नहीं हैं','মেলা বিষয় নেই'],
 ['Make room for your next discovery','अगली खोज के लिए जगह बनाएँ','পরের আবিষ্কারের জন্য জায়গা করুন'],
 ['Try a different search or filter. Save a topic from its lesson to find it here.','अन्य खोज या फ़िल्टर आज़माएँ। पाठ से विषय सहेजकर यहाँ देखें।','অন্য অনুসন্ধান বা ছাঁকনি চেষ্টা করুন। পাঠ থেকে বিষয় সংরক্ষণ করে এখানে দেখুন।'],
 ['Add a topic you want to explore. Your class assignments remain in Classes, alongside your personal learning.','जिस विषय को खोजना चाहते हैं उसे जोड़ें। व्यक्तिगत अध्ययन के साथ कक्षा के असाइनमेंट Classes में रहते हैं।','অন্বেষণ করতে চান এমন বিষয় যোগ করুন। ব্যক্তিগত শেখার পাশাপাশি ক্লাসের অ্যাসাইনমেন্ট Classes-এ থাকে।'],
 ['Add a learning area in Profile to get started.','शुरू करने के लिए Profile में अध्ययन क्षेत्र जोड़ें।','শুরু করতে Profile-এ শেখার ক্ষেত্র যোগ করুন।'],
 ['Go to classes','कक्षाओं में जाएँ','ক্লাসে যান'],
 ['Open profile','प्रोफ़ाइल खोलें','প্রোফাইল খুলুন'],
 ['Add a topic','विषय जोड़ें','বিষয় যোগ করুন'],
 ['Topic name','विषय का नाम','বিষয়ের নাম'],
 ['For example, quadratic equations','जैसे, द्विघात समीकरण','যেমন, দ্বিঘাত সমীকরণ'],
 ['Topic link','विषय का लिंक','বিষয়ের লিঙ্ক'],
 ['Practice this topic','इस विषय का अभ्यास करें','এই বিষয় অনুশীলন করুন'],
 ['Reviewed questions are not available here yet','यहाँ समीक्षित प्रश्न अभी उपलब्ध नहीं हैं','এখানে পর্যালোচিত প্রশ্ন এখনও নেই'],
 ['This topic link has no reviewed question set in the current learning path, so opening it creates no new practice result. If you saved it earlier, you can find it in previous topics.','वर्तमान अध्ययन पथ में इस लिंक का समीक्षित प्रश्न सेट नहीं है, इसलिए खोलने से नया अभ्यास परिणाम नहीं बनता। पहले सहेजा हो तो पिछले विषयों में देखें।','বর্তমান শেখার পথে এই লিঙ্কের পর্যালোচিত প্রশ্ন নেই, তাই খুললে নতুন অনুশীলনের ফল হয় না। আগে সংরক্ষণ করলে আগের বিষয়গুলিতে দেখুন।'],
 ['Open my saved practice queue','मेरी सहेजी अभ्यास सूची खोलें','আমার সংরক্ষিত অনুশীলনের তালিকা খুলুন'],
 ['Save a question in Ask','Ask में प्रश्न सहेजें','Ask-এ প্রশ্ন সংরক্ষণ করুন'],
 ['Open previous topics','पिछले विषय खोलें','আগের বিষয়গুলি খুলুন'],
 ['Your subject','आपका विषय','আপনার বিষয়'],
 ['Your topic','आपका अध्ययन विषय','আপনার শেখার বিষয়'],
 ['Try an idea for yourself. Understand the why—not just the answer.','विचार स्वयं आज़माएँ। उत्तर के साथ उसका कारण समझें।','ধারণা নিজে চেষ্টা করুন। উত্তরের সঙ্গে কারণ বুঝুন।'],
 ['Personalized practice for this topic becomes available when the AI model is connected. The geometry example below is ready to try now.','इस विषय का व्यक्तिगत अभ्यास AI मॉडल जुड़ने पर उपलब्ध होगा। नीचे का ज्यामिति उदाहरण अभी आज़माएँ।','AI মডেল যুক্ত হলে এই বিষয়ে ব্যক্তিগত অনুশীলন পাওয়া যাবে। নিচের জ্যামিতির উদাহরণ এখন চেষ্টা করুন।'],
 ['Keep a question about this topic','इस विषय का प्रश्न रखें','এই বিষয়ে প্রশ্ন রাখুন'],
 ['Ready-to-try example · 3 questions','तैयार उदाहरण · 3 प्रश्न','প্রস্তুত উদাহরণ · 3টি প্রশ্ন'],
 ['Think in three dimensions','तीन आयामों में सोचें','তিন মাত্রায় ভাবুন'],
 ['Use what you discover in the cube lab to check your understanding of volume. Review an explanation for every answer.','घन प्रयोगशाला की खोज से आयतन की समझ जाँचें। हर उत्तर की व्याख्या देखें।','ঘনকের ল্যাবে যা জানলেন তা দিয়ে আয়তনের বোঝাপড়া যাচাই করুন। প্রতিটি উত্তরের ব্যাখ্যা দেখুন।'],
 ['Start practice','अभ्यास शुरू करें','অনুশীলন শুরু করুন'],
 ['Explore the lab first','पहले प्रयोगशाला खोजें','আগে ল্যাব অন্বেষণ করুন'],
 ['Apply it in a project','प्रोजेक्ट में लागू करें','প্রকল্পে প্রয়োগ করুন'],
 ['From your learning','आपके अध्ययन से','আপনার শেখা থেকে'],
 ['Loading topics…','विषय खोल रहे हैं…','বিষয় খোলা হচ্ছে…'],
 ['Could not load topics.','विषय नहीं खुल सके।','বিষয় খোলা যায়নি।'],
 ['· Review the idea','· विचार देखें','· ধারণা দেখুন'],
 ['Authored mathematics sample','लिखित गणित नमूना','রচিত গণিতের নমুনা'],
 ['Practice cube volume in your lesson','अपने पाठ में घन के आयतन का अभ्यास करें','আপনার পাঠে ঘনকের আয়তন অনুশীলন করুন'],
 ['Explore cube volume in your lesson','अपने पाठ में घन का आयतन खोजें','আপনার পাঠে ঘনকের আয়তন অন্বেষণ করুন'],
 ['The cube model, explanation, questions, attempts and project stay with one saved concept. This sample is not official curriculum coverage.','घन मॉडल, व्याख्या, प्रश्न, प्रयास और प्रोजेक्ट एक सहेजी अवधारणा के साथ रहते हैं। नमूना आधिकारिक पाठ्यक्रम कवरेज नहीं है।','ঘনকের মডেল, ব্যাখ্যা, প্রশ্ন, প্রচেষ্টা ও প্রকল্প একই সংরক্ষিত ধারণার সঙ্গে থাকে। নমুনা সরকারি পাঠ্যক্রমের পূর্ণ পরিসর নয়।'],
 ['Your earlier saved work remains available.','आपका पहले सहेजा कार्य उपलब्ध है।','আপনার আগের সংরক্ষিত কাজ উপলব্ধ।'],
 ['Continue the saved cube activity','सहेजी घन गतिविधि जारी करें','সংরক্ষিত ঘনকের কার্যকলাপ চালিয়ে যান'],
 ['Start the cube activity','घन गतिविधि शुरू करें','ঘনকের কার্যকলাপ শুরু করুন'],
 ['Change the model’s side length and rotation, read its description, then check understanding one question at a time. Exploring the model alone adds no assessment evidence.','मॉडल की भुजा और घुमाव बदलें, विवरण पढ़ें, फिर एक-एक प्रश्न से समझ जाँचें। केवल मॉडल खोजने से आकलन साक्ष्य नहीं जुड़ता।','মডেলের বাহু ও ঘূর্ণন বদলান, বিবরণ পড়ুন, তারপর একবারে একটি প্রশ্নে বোঝাপড়া যাচাই করুন। শুধু মডেল অন্বেষণে মূল্যায়নের প্রমাণ যোগ হয় না।'],
 ['Continue saved activity','सहेजी गतिविधि जारी करें','সংরক্ষিত কার্যকলাপ চালিয়ে যান'],
 ['Open authored activity','लिखित गतिविधि खोलें','রচিত কার্যকলাপ খুলুন'],
 ['This authored school activity is available in a student workspace.','यह लिखित विद्यालय गतिविधि छात्र कार्यक्षेत्र में उपलब्ध है।','এই রচিত বিদ্যালয়ের কার্যকলাপ শিক্ষার্থীর কর্মক্ষেত্রে উপলব্ধ।'],
 ['Previous local activity','पिछली स्थानीय गतिविधि','আগের স্থানীয় কার্যকলাপ'],
 ['Earlier lab and three-question results are still available in their original view. They are separate from the current concept’s assessment record.','पहली प्रयोगशाला और तीन-प्रश्न के परिणाम मूल दृश्य में उपलब्ध हैं। ये वर्तमान अवधारणा के आकलन रिकॉर्ड से अलग हैं।','আগের ল্যাব ও তিন প্রশ্নের ফল মূল দৃশ্যে আছে। এগুলি বর্তমান ধারণার মূল্যায়নের রেকর্ড থেকে আলাদা।'],
 ['Open previous practice example','पिछला अभ्यास उदाहरण खोलें','আগের অনুশীলনের উদাহরণ খুলুন'],
 ['Open previous cube lab','पिछली घन प्रयोगशाला खोलें','আগের ঘনকের ল্যাব খুলুন'],
 ['Practice with purpose','उद्देश्य के साथ अभ्यास करें','উদ্দেশ্য নিয়ে অনুশীলন করুন'],
 ['Guided journeys','निर्देशित यात्राएँ','নির্দেশিত যাত্রা'],
 ['Curated interactive examples · English, हिन्दी, বাংলা','चुने इंटरैक्टिव उदाहरण · English, हिन्दी, বাংলা','বাছা ইন্টারঅ্যাক্টিভ উদাহরণ · English, हिन्दी, বাংলা'],
 ['Why this?','यह क्यों?','এটি কেন?'],
 ['Open with Guide','Guide के साथ खोलें','Guide-এর সঙ্গে খুলুন'],
 ['Open lesson','पाठ खोलें','পাঠ খুলুন'],
 ['Ask','पूछें','জিজ্ঞাসা করুন'],
 ['All topics','सभी विषय','সব বিষয়'],
 ['In progress','जारी है','চলছে'],
 ['Saved','सहेजे','সংরক্ষিত'],
 ['{count} topics','{count} विषय','{count}টি বিষয়'],
 ['{count} practice sessions','{count} अभ्यास सत्र','{count}টি অনুশীলনের সেশন'],
 ['Keep track of a concept you want to learn in {subject}.','{subject} में सीखना चाही अवधारणा रखें।','{subject}-এ শিখতে চান এমন ধারণা রাখুন।'],
 ['Ask about {title}','{title} के बारे में पूछें','{title} সম্পর্কে জিজ্ঞাসা করুন'],
 ['Practice {title}','{title} का अभ्यास करें','{title} অনুশীলন করুন'],
 ['Question {number}','प्रश्न {number}','প্রশ্ন {number}'],
 ['{correct} of {total} correct','{total} में से {correct} सही','{total}টির মধ্যে {correct}টি সঠিক'],
 ['grid view','ग्रिड दृश्य','গ্রিড দৃশ্য'],
 ['list view','सूची दृश्य','তালিকার দৃশ্য'],
 ['Correct','सही','সঠিক'],
 ['Let’s look at the reasoning','तर्क देखें','যুক্তি দেখুন'],
 ['Practice result saved. This short check does not establish overall mastery.','अभ्यास परिणाम सहेजा है। यह छोटी जाँच पूरी दक्षता नहीं स्थापित करती।','অনুশীলনের ফল সংরক্ষিত। এই ছোট যাচাই সামগ্রিক দক্ষতা প্রতিষ্ঠা করে না।'],
 ['Saved topics are unavailable. Your topics and bookmarks have not been changed.','सहेजे विषय उपलब्ध नहीं हैं। आपके विषय और बुकमार्क नहीं बदले गए।','সংরক্ষিত বিষয় অনুপলব্ধ। আপনার বিষয় ও বুকমার্ক বদলায়নি।'],
 ['Retry saved topics','सहेजे विषय फिर खोलें','সংরক্ষিত বিষয় আবার খুলুন'],
 ['Add a topic in Learn to keep your practice and learning together.','अभ्यास और अध्ययन साथ रखने के लिए Learn में विषय जोड़ें।','অনুশীলন ও শেখা একসঙ্গে রাখতে Learn-এ বিষয় যোগ করুন।'],
];
entries.push(['Loading saved topics…','सहेजे विषय खोल रहे हैं…','সংরক্ষিত বিষয় খোলা হচ্ছে…'],['Saved topic count unavailable','सहेजे विषयों की संख्या अनुपलब्ध','সংরক্ষিত বিষয়ের সংখ্যা অনুপলব্ধ'],['Opening…','खोल रहे हैं…','খোলা হচ্ছে…']);
entries.push(['Your lessons','आपके पाठ','আপনার পাঠ']);
entries.push(...[["Loading lesson","पाठ खोल रहे हैं","পাঠ খোলা হচ্ছে"],["Your lesson could not be loaded.","आपका पाठ नहीं खुल सका।","আপনার পাঠ খোলা যায়নি।"],["This topic is unavailable","यह विषय उपलब्ध नहीं है","এই বিষয় অনুপলব্ধ"],["It may have been removed or belong to a different learning workspace.","यह हटाया गया हो सकता है या अन्य अध्ययन कार्यक्षेत्र का है।","এটি মুছে যেতে পারে বা অন্য শেখার কর্মক্ষেত্রের হতে পারে।"],["Back to Learn","Learn पर लौटें","Learn-এ ফিরুন"],["Your learning workspace","आपका अध्ययन कार्यक्षेत्र","আপনার শেখার কর্মক্ষেত্র"],["Explore cube volume in 3D","3D में घन का आयतन खोजें","3D-তে ঘনকের আয়তন অন্বেষণ করুন"],["Change the side length and see how volume changes in three dimensions.","भुजा बदलें और तीन आयामों में आयतन का बदलाव देखें।","বাহু বদলে তিন মাত্রায় আয়তনের পরিবর্তন দেখুন।"],["Open interactive lab","इंटरैक्टिव प्रयोगशाला खोलें","ইন্টারঅ্যাক্টিভ ল্যাব খুলুন"],["Keep learning","सीखना जारी रखें","শেখা চালিয়ে যান"],["Ask a question","प्रश्न पूछें","প্রশ্ন করুন"],["Start a project","प्रोजेक्ट शुरू करें","প্রকল্প শুরু করুন"],["Subject lessons","विषय के पाठ","বিষয়ের পাঠ"],["In this subject","इस विषय में","এই বিষয়ে"],["Lesson","पाठ","পাঠ"],["Stop reading","पढ़ना रोकें","পড়া বন্ধ করুন"],["Read lesson aloud","पाठ बोलकर पढ़ें","পাঠ পড়ে শোনান"],["Read aloud","बोलकर पढ़ें","পড়ে শোনান"],["Remove bookmark","बुकमार्क हटाएँ","বুকমার্ক সরান"],["Bookmark lesson","पाठ बुकमार्क करें","পাঠ বুকমার্ক করুন"],["Exit focus mode","फ़ोकस मोड से बाहर आएँ","ফোকাস মোড থেকে বের হন"],["Enter focus mode","फ़ोकस मोड खोलें","ফোকাস মোড খুলুন"],["Exit focus mode (Esc)","फ़ोकस मोड से बाहर आएँ (Esc)","ফোকাস মোড থেকে বের হন (Esc)"],["Focus mode","फ़ोकस मोड","ফোকাস মোড"],["Preparing an explanation","व्याख्या तैयार कर रहे हैं","ব্যাখ্যা তৈরি হচ্ছে"],["Your topic is ready to explore","आपका विषय खोजने के लिए तैयार है","আপনার বিষয় অন্বেষণের জন্য প্রস্তুত"],["Published lesson content will appear here when available. Keep a question, connect with your class, or request an explanation.","पाठ की सामग्री उपलब्ध होने पर यहाँ दिखेगी। प्रश्न रखें, कक्षा से जुड़ें या व्याख्या माँगें।","পাঠের বিষয়বস্তু উপলব্ধ হলে এখানে দেখা যাবে। প্রশ্ন রাখুন, ক্লাসে যুক্ত হন বা ব্যাখ্যা চান।"],["Request explanation","व्याख्या माँगें","ব্যাখ্যা চান"],["Next topic →","अगला विषय →","পরের বিষয় →"],["All lessons →","सभी पाठ →","সব পাঠ →"],["Keep a question for later","बाद के लिए प्रश्न रखें","পরে দেখার জন্য প্রশ্ন রাখুন"],["What would you like to understand?","आप क्या समझना चाहते हैं?","আপনি কী বুঝতে চান?"],["Save question","प्रश्न सहेजें","প্রশ্ন সংরক্ষণ করুন"],["Question saved.","प्रश्न सहेजा है।","প্রশ্ন সংরক্ষিত।"],["Open this question in Ask","यह प्रश्न Ask में खोलें","এই প্রশ্ন Ask-এ খুলুন"],["Retry question recovery","प्रश्न की रिकवरी फिर करें","প্রশ্ন ফেরানো আবার চেষ্টা করুন"],["Back to previous topics","पिछले विषयों पर लौटें","আগের বিষয়গুলিতে ফিরুন"],["Previous interactive lab · Geometry","पिछली इंटरैक्टिव प्रयोगशाला · ज्यामिति","আগের ইন্টারঅ্যাক্টিভ ল্যাব · জ্যামিতি"],["Small change. Another dimension.","छोटा बदलाव। एक और आयाम।","ছোট পরিবর্তন। আরেকটি মাত্রা।"],["If you double a cube’s side, does its volume double too? Move the slider and discover why.","घन की भुजा दोगुनी होने पर क्या आयतन भी दोगुना होता है? स्लाइडर बदलें और कारण खोजें।","ঘনকের বাহু দ্বিগুণ হলে আয়তনও কি দ্বিগুণ হয়? স্লাইডার সরিয়ে কারণ জানুন।"],["Side length","भुजा की लंबाई","বাহুর দৈর্ঘ্য"],["Rotate the cube","घन घुमाएँ","ঘনক ঘোরান"],["Volume = side × side × side","आयतन = भुजा × भुजा × भुजा","আয়তন = বাহু × বাহু × বাহু"],["cubic units","घन इकाई","ঘন একক"],["A cube grows in three directions. Doubling the side makes the volume 2 × 2 × 2 = 8 times larger.","घन तीन दिशाओं में बढ़ता है। भुजा दोगुनी करने पर आयतन 2 × 2 × 2 = 8 गुना होता है।","ঘনক তিন দিকে বাড়ে। বাহু দ্বিগুণ করলে আয়তন 2 × 2 × 2 = 8 গুণ হয়।"],["Reset view","दृश्य रीसेट करें","দৃশ্য রিসেট করুন"],["Added to Learn","Learn में जोड़ा गया","Learn-এ যোগ হয়েছে"],["Add to my learning","मेरे अध्ययन में जोड़ें","আমার শেখায় যোগ করুন"],["Ask about this idea","इस विचार के बारे में पूछें","এই ধারণা সম্পর্কে জিজ্ঞাসা করুন"],["Build with this idea","इस विचार से बनाएँ","এই ধারণা দিয়ে তৈরি করুন"],["Added to your previous Geometry topics in Learn. Exploration does not count as assessed mastery.","Learn के पिछले ज्यामिति विषयों में जोड़ा है। अन्वेषण आकलित दक्षता नहीं गिना जाता।","Learn-এ আগের জ্যামিতির বিষয়ে যোগ হয়েছে। অন্বেষণ মূল্যায়িত দক্ষতা হিসেবে গণ্য হয় না।"],["{side} units","{side} इकाई","{side} একক"],["A cube with side {side} units and volume {volume} cubic units, rotated {rotation} degrees.","{side} इकाई भुजा और {volume} घन इकाई आयतन वाला घन, {rotation} डिग्री घूमा है।","{side} একক বাহু ও {volume} ঘন একক আয়তনের ঘনক, {rotation} ডিগ্রি ঘুরেছে।"],["Filter by subject","विषय से फ़िल्टर करें","বিষয় দিয়ে ছাঁকুন"]]);
const messages = Object.fromEntries(entries.map(([en, hi, bn]) => [en, { en, hi, bn }]));
export const legacyLearningCopy = locale => (key, params = {}) =>
 (messages[key]?.[locale] || learningCopy(locale)(key)).replace(/\{(\w+)\}/g, (match, name) => String(params[name] ?? match));
