const hi={
 'Your profile':'आपकी प्रोफ़ाइल',
 'One account with separate workspaces and preferences.':'एक खाते में अलग कार्यक्षेत्र और प्राथमिकताएँ।',
 'Unfinished profile edits recovered from this workspace and tab. Review them before saving.':'इस कार्यक्षेत्र और टैब के अधूरे प्रोफ़ाइल बदलाव वापस मिले हैं। सहेजने से पहले उन्हें देखें।',
 'Account display name':'खाते में दिखने वाला नाम',
 'Teaching language:':'पढ़ाने की भाषा:',
 'Your display name applies to this account. Language and learning areas belong to the active workspace.':'दिखने वाला नाम पूरे खाते पर लागू होता है। भाषा और सीखने के क्षेत्र वर्तमान कार्यक्षेत्र के हैं।',
 'Display name':'दिखने वाला नाम',
 'Saving…':'सहेज रहे हैं…',
 'Save profile':'प्रोफ़ाइल सहेजें',
 'A different display name is saved':'एक अलग नाम सहेजा गया है',
 'Current saved name:':'अभी सहेजा नाम:',
 'Your edits remain here. Export them or explicitly load the latest saved name.':'आपके बदलाव यहाँ हैं। उन्हें निर्यात करें या नवीनतम सहेजा नाम लोड करें।',
 'Learning areas':'सीखने के क्षेत्र',
 'Add a subject, skill or interest. This creates a personal learning-area record; reviewed curriculum content remains separate.':'विषय, कौशल या रुचि जोड़ें। इससे आपका निजी सीखने का क्षेत्र दर्ज होगा; समीक्षा की गई पाठ्यक्रम सामग्री अलग रहती है।',
 'Reading learning areas…':'सीखने के क्षेत्र पढ़ रहे हैं…',
 'Learning areas could not be read. Your draft remains here.':'सीखने के क्षेत्र पढ़े नहीं जा सके। आपका ड्राफ़्ट यहाँ है।',
 'Retry learning areas':'सीखने के क्षेत्र फिर पढ़ें',
 'No personal learning areas yet.':'अभी कोई निजी सीखने का क्षेत्र नहीं है।',
 'New learning area':'नया सीखने का क्षेत्र',
 'Add area':'क्षेत्र जोड़ें',
 'Export profile edits':'प्रोफ़ाइल बदलाव निर्यात करें',
 'Discard edits and load saved profile':'बदलाव हटाएँ और सहेजी प्रोफ़ाइल लोड करें',
 'Connections and requests':'संपर्क और अनुरोध',
 'Language and appearance settings':'भाषा और रूप की सेटिंग',
 'Display name saved for this account on this device.':'इस खाते का नाम इस डिवाइस पर सहेजा गया।',
 'Your learning-area draft remains here.':'आपके सीखने के क्षेत्र का ड्राफ़्ट यहाँ है।',
 'The earlier editor backup remains; export it before replacing it.':'पहले का संपादन बैकअप रखा गया है; उसे बदलने से पहले निर्यात करें।',
 'Learning area added. Open Learn to continue. No curriculum, activity or mastery was generated.':'सीखने का क्षेत्र जोड़ा गया। आगे बढ़ने के लिए सीखें खोलें। कोई पाठ्यक्रम, गतिविधि या दक्षता नहीं बनाई गई।',
 'Latest saved name loaded. Unfinished profile and learning-area edits were discarded.':'नवीनतम सहेजा नाम लोड हुआ। अधूरे प्रोफ़ाइल और सीखने के क्षेत्र के बदलाव हटा दिए गए।',
 'Profile edits exported. This does not save your name or add a learning area.':'प्रोफ़ाइल बदलाव निर्यात किए गए। इससे नाम सहेजा या सीखने का क्षेत्र जोड़ा नहीं जाता।',
 'Profile recovery is incomplete. Original edits were kept.':'प्रोफ़ाइल की बहाली अधूरी है। मूल बदलाव रखे गए हैं।',
 'Use a student or professional workspace to add a learning area.':'सीखने का क्षेत्र जोड़ने के लिए छात्र या पेशेवर कार्यक्षेत्र खोलें।',
 'Existing learning areas are unavailable. Retry reading them before adding another.':'पहले के सीखने के क्षेत्र उपलब्ध नहीं हैं। नया जोड़ने से पहले उन्हें फिर पढ़ें।',
 'This learning area is already in your workspace.':'यह सीखने का क्षेत्र आपके कार्यक्षेत्र में पहले से है।',
 'The signed-in account changed. Current edits were kept.':'साइन इन किया खाता बदल गया। वर्तमान बदलाव रखे गए हैं।',
 student:'छात्र कार्यक्षेत्र',teacher:'शिक्षक कार्यक्षेत्र',parent:'अभिभावक कार्यक्षेत्र',professional:'पेशेवर कार्यक्षेत्र',organization:'संगठन कार्यक्षेत्र'
};
const bn={
 'Your profile':'আপনার প্রোফাইল',
 'One account with separate workspaces and preferences.':'একটি অ্যাকাউন্টে আলাদা কর্মক্ষেত্র ও পছন্দ।',
 'Unfinished profile edits recovered from this workspace and tab. Review them before saving.':'এই কর্মক্ষেত্র ও ট্যাবের অসমাপ্ত প্রোফাইল পরিবর্তন ফিরে পাওয়া গেছে। সংরক্ষণের আগে দেখে নিন।',
 'Account display name':'অ্যাকাউন্টে দেখানো নাম',
 'Teaching language:':'পড়ানোর ভাষা:',
 'Your display name applies to this account. Language and learning areas belong to the active workspace.':'দেখানো নাম পুরো অ্যাকাউন্টে প্রযোজ্য। ভাষা ও শেখার ক্ষেত্র বর্তমান কর্মক্ষেত্রের।',
 'Display name':'দেখানো নাম',
 'Saving…':'সংরক্ষণ করা হচ্ছে…',
 'Save profile':'প্রোফাইল সংরক্ষণ করুন',
 'A different display name is saved':'অন্য একটি নাম সংরক্ষিত আছে',
 'Current saved name:':'বর্তমানে সংরক্ষিত নাম:',
 'Your edits remain here. Export them or explicitly load the latest saved name.':'আপনার পরিবর্তন এখানে আছে। সেগুলি রপ্তানি করুন বা সর্বশেষ সংরক্ষিত নাম লোড করুন।',
 'Learning areas':'শেখার ক্ষেত্র',
 'Add a subject, skill or interest. This creates a personal learning-area record; reviewed curriculum content remains separate.':'বিষয়, দক্ষতা বা আগ্রহ যোগ করুন। এতে ব্যক্তিগত শেখার ক্ষেত্র নথিভুক্ত হয়; পর্যালোচিত পাঠ্যক্রমের বিষয়বস্তু আলাদা থাকে।',
 'Reading learning areas…':'শেখার ক্ষেত্র পড়া হচ্ছে…',
 'Learning areas could not be read. Your draft remains here.':'শেখার ক্ষেত্র পড়া যায়নি। আপনার খসড়া এখানে আছে।',
 'Retry learning areas':'শেখার ক্ষেত্র আবার পড়ুন',
 'No personal learning areas yet.':'এখনও কোনো ব্যক্তিগত শেখার ক্ষেত্র নেই।',
 'New learning area':'নতুন শেখার ক্ষেত্র',
 'Add area':'ক্ষেত্র যোগ করুন',
 'Export profile edits':'প্রোফাইলের পরিবর্তন রপ্তানি করুন',
 'Discard edits and load saved profile':'পরিবর্তন বাদ দিয়ে সংরক্ষিত প্রোফাইল লোড করুন',
 'Connections and requests':'সংযোগ ও অনুরোধ',
 'Language and appearance settings':'ভাষা ও চেহারার সেটিংস',
 'Display name saved for this account on this device.':'এই অ্যাকাউন্টের নাম এই ডিভাইসে সংরক্ষিত হয়েছে।',
 'Your learning-area draft remains here.':'আপনার শেখার ক্ষেত্রের খসড়া এখানে আছে।',
 'The earlier editor backup remains; export it before replacing it.':'আগের সম্পাদনার ব্যাকআপ রাখা আছে; বদলানোর আগে রপ্তানি করুন।',
 'Learning area added. Open Learn to continue. No curriculum, activity or mastery was generated.':'শেখার ক্ষেত্র যোগ হয়েছে। এগোতে শিখুন খুলুন। কোনো পাঠ্যক্রম, কাজ বা দক্ষতা তৈরি হয়নি।',
 'Latest saved name loaded. Unfinished profile and learning-area edits were discarded.':'সর্বশেষ সংরক্ষিত নাম লোড হয়েছে। অসমাপ্ত প্রোফাইল ও শেখার ক্ষেত্রের পরিবর্তন বাদ দেওয়া হয়েছে।',
 'Profile edits exported. This does not save your name or add a learning area.':'প্রোফাইলের পরিবর্তন রপ্তানি হয়েছে। এতে নাম সংরক্ষণ বা শেখার ক্ষেত্র যোগ হয় না।',
 'Profile recovery is incomplete. Original edits were kept.':'প্রোফাইলের পুনরুদ্ধার অসম্পূর্ণ। মূল পরিবর্তন রাখা হয়েছে।',
 'Use a student or professional workspace to add a learning area.':'শেখার ক্ষেত্র যোগ করতে ছাত্র বা পেশাদার কর্মক্ষেত্র খুলুন।',
 'Existing learning areas are unavailable. Retry reading them before adding another.':'আগের শেখার ক্ষেত্র পাওয়া যাচ্ছে না। নতুন ক্ষেত্র যোগ করার আগে আবার পড়ুন।',
 'This learning area is already in your workspace.':'এই শেখার ক্ষেত্র আপনার কর্মক্ষেত্রে আগেই আছে।',
 'The signed-in account changed. Current edits were kept.':'সাইন ইন করা অ্যাকাউন্ট বদলেছে। বর্তমান পরিবর্তন রাখা হয়েছে।',
 student:'ছাত্র কর্মক্ষেত্র',teacher:'শিক্ষক কর্মক্ষেত্র',parent:'অভিভাবক কর্মক্ষেত্র',professional:'পেশাদার কর্মক্ষেত্র',organization:'সংগঠনের কর্মক্ষেত্র'
};
export function profileText(locale,text){return ({hi,bn})[locale]?.[text]||text;}
