const translations={
 hi:{
  'Previous appearance — shown as Vision Boy':'पिछला रूप — Vision Boy के रूप में दिखता है',
  'The account accent changed in another tab. Your choice is still here.':'दूसरे टैब में खाते का रंग बदला है। आपका चयन यहाँ रखा गया है।', 'Use saved account accent':'सहेजा गया रंग उपयोग करें',
  'Make Guide work for you':'Guide को अपनी ज़रूरत के अनुसार बनाएँ',
  'Your preferences have a purpose and a visible scope. This is a local preview, not verified cloud security.':'आपकी प्राथमिकताएँ इस कार्यक्षेत्र पर लागू होती हैं। यह स्थानीय पूर्वावलोकन है; क्लाउड सुरक्षा का सत्यापन नहीं हुआ है।',
  'Language and accessibility':'भाषा और सुलभता', 'Teaching language':'शिक्षण की भाषा', 'Interface language':'इंटरफ़ेस की भाषा',
  'Guide appearance':'Guide का रूप', 'Vision Boy — the sky sphere':'Vision Boy — नीला गोला', 'Vision Girl — the glowing bars':'Vision Girl — चमकती पट्टियाँ', 'Orb':'गोला', 'Voice':'आवाज़',
  'Open the Guide control to preview either visual style and see the microphone state. The styles share the same conversations and learning.':'Guide खोलकर रूप और माइक्रोफ़ोन की स्थिति देखें। सभी रूपों में बातचीत और अध्ययन एक ही रहता है।',
  'Teaching content is translated for curated journeys. Interface translation is being completed; unsupported labels remain in English.':'चुने गए अध्ययन में अनुवादित सामग्री उपलब्ध है। इंटरफ़ेस का अनुवाद जारी है; बाकी लेबल अंग्रेज़ी में रहते हैं।',
  'Show source-language explanation alongside teaching':'शिक्षण के साथ स्रोत की भाषा में व्याख्या दिखाएँ', 'Prefer text alternatives':'पाठ के विकल्पों को प्राथमिकता दें', 'Use my explicit preferences for personalization':'निजीकरण के लिए मेरी चुनी हुई प्राथमिकताएँ उपयोग करें',
  'Audio interaction: speak with Visionary and hear replies. The Guide panel shows listening and speaking states when audio is active. Text remains available when audio is off or unavailable.':'ऑडियो संवाद: Visionary से बात करें और उत्तर सुनें। ऑडियो चालू होने पर Guide सुनने और बोलने की स्थिति दिखाता है। ऑडियो बंद या अनुपलब्ध होने पर पाठ उपलब्ध रहता है।',
  'What Guide remembers':'Guide क्या याद रखता है', 'Source: preferences you selected · Scope: this workspace. No sensitive personality or ability inferences are created.':'स्रोत: आपकी चुनी हुई प्राथमिकताएँ · दायरा: यह कार्यक्षेत्र। व्यक्तित्व या क्षमता के संवेदनशील अनुमान नहीं बनाए जाते।',
  'Reset personalization':'निजीकरण रीसेट करें', 'Preference saved on this device.':'प्राथमिकता इस उपकरण पर सहेजी गई।', 'Guide appearance saved on this device.':'Guide का रूप इस उपकरण पर सहेजा गया।',
  'Personalization preferences reset. Conversations and learning evidence were kept.':'निजीकरण की प्राथमिकताएँ रीसेट हुईं। बातचीत और अध्ययन के रिकॉर्ड रखे गए।',
  'Account appearance':'खाते का रूप', 'This account accent applies to supported learning views. Language and Guide preferences above apply to the current workspace.':'खाते का रंग समर्थित अध्ययन दृश्यों पर लागू होता है। ऊपर की भाषा और Guide प्राथमिकताएँ वर्तमान कार्यक्षेत्र पर लागू होती हैं।',
  'Choose an account accent':'खाते का रंग चुनें', 'Saving…':'सहेजा जा रहा है…', 'Save account accent':'खाते का रंग सहेजें', 'Account accent saved on this device.':'खाते का रंग इस उपकरण पर सहेजा गया।',
  'Account accent could not be saved. Your selection remains here for retry.':'खाते का रंग नहीं सहेजा जा सका। फिर प्रयास करने के लिए आपका चयन यहाँ रखा गया है।',
  blue:'नीला',green:'हरा',red:'लाल',amber:'अंबर',purple:'बैंगनी',teal:'नीलहरा',
 },
 bn:{
  'Previous appearance — shown as Vision Boy':'আগের রূপ — Vision Boy হিসেবে দেখা যায়',
  'The account accent changed in another tab. Your choice is still here.':'অন্য ট্যাবে অ্যাকাউন্টের রং বদলেছে। আপনার নির্বাচন এখানে রাখা আছে।', 'Use saved account accent':'সংরক্ষিত রং ব্যবহার করুন',
  'Make Guide work for you':'Guide-কে নিজের প্রয়োজন অনুযায়ী সাজান',
  'Your preferences have a purpose and a visible scope. This is a local preview, not verified cloud security.':'আপনার পছন্দ এই কর্মক্ষেত্রে প্রযোজ্য। এটি স্থানীয় প্রিভিউ; ক্লাউড নিরাপত্তা যাচাই করা হয়নি।',
  'Language and accessibility':'ভাষা ও প্রবেশগম্যতা', 'Teaching language':'শিক্ষণের ভাষা', 'Interface language':'ইন্টারফেসের ভাষা',
  'Guide appearance':'Guide-এর রূপ', 'Vision Boy — the sky sphere':'Vision Boy — নীল গোলক', 'Vision Girl — the glowing bars':'Vision Girl — উজ্জ্বল দণ্ড', 'Orb':'গোলক', 'Voice':'কণ্ঠ',
  'Open the Guide control to preview either visual style and see the microphone state. The styles share the same conversations and learning.':'রূপ ও মাইক্রোফোনের অবস্থা দেখতে Guide খুলুন। সব রূপে একই কথোপকথন ও শেখা থাকে।',
  'Teaching content is translated for curated journeys. Interface translation is being completed; unsupported labels remain in English.':'নির্বাচিত অধ্যয়নে অনূদিত বিষয়বস্তু আছে। ইন্টারফেসের অনুবাদ চলছে; বাকি লেবেল ইংরেজিতে থাকে।',
  'Show source-language explanation alongside teaching':'শিক্ষণের সঙ্গে উৎসের ভাষায় ব্যাখ্যা দেখান', 'Prefer text alternatives':'পাঠ্য বিকল্পকে অগ্রাধিকার দিন', 'Use my explicit preferences for personalization':'ব্যক্তিগতকরণের জন্য আমার নির্বাচিত পছন্দ ব্যবহার করুন',
  'Audio interaction: speak with Visionary and hear replies. The Guide panel shows listening and speaking states when audio is active. Text remains available when audio is off or unavailable.':'অডিও কথোপকথন: Visionary-র সঙ্গে কথা বলুন ও উত্তর শুনুন। অডিও সক্রিয় হলে Guide শোনা ও বলার অবস্থা দেখায়। অডিও বন্ধ বা অনুপলব্ধ হলে পাঠ্য থাকে।',
  'What Guide remembers':'Guide কী মনে রাখে', 'Source: preferences you selected · Scope: this workspace. No sensitive personality or ability inferences are created.':'উৎস: আপনার নির্বাচিত পছন্দ · পরিধি: এই কর্মক্ষেত্র। ব্যক্তিত্ব বা সক্ষমতার সংবেদনশীল অনুমান তৈরি হয় না।',
  'Reset personalization':'ব্যক্তিগতকরণ রিসেট করুন', 'Preference saved on this device.':'পছন্দ এই ডিভাইসে সংরক্ষিত হয়েছে।', 'Guide appearance saved on this device.':'Guide-এর রূপ এই ডিভাইসে সংরক্ষিত হয়েছে।',
  'Personalization preferences reset. Conversations and learning evidence were kept.':'ব্যক্তিগতকরণের পছন্দ রিসেট হয়েছে। কথোপকথন ও শেখার রেকর্ড রাখা হয়েছে।',
  'Account appearance':'অ্যাকাউন্টের রূপ', 'This account accent applies to supported learning views. Language and Guide preferences above apply to the current workspace.':'অ্যাকাউন্টের রং সমর্থিত শেখার দৃশ্যে প্রযোজ্য। উপরের ভাষা ও Guide পছন্দ বর্তমান কর্মক্ষেত্রে প্রযোজ্য।',
  'Choose an account accent':'অ্যাকাউন্টের রং বেছে নিন', 'Saving…':'সংরক্ষণ হচ্ছে…', 'Save account accent':'অ্যাকাউন্টের রং সংরক্ষণ করুন', 'Account accent saved on this device.':'অ্যাকাউন্টের রং এই ডিভাইসে সংরক্ষিত হয়েছে।',
  'Account accent could not be saved. Your selection remains here for retry.':'অ্যাকাউন্টের রং সংরক্ষণ করা যায়নি। আবার চেষ্টা করার জন্য আপনার নির্বাচন এখানে রাখা আছে।',
  blue:'নীল',green:'সবুজ',red:'লাল',amber:'অ্যাম্বার',purple:'বেগুনি',teal:'নীলসবুজ',
 },
};
export const settingsCopy=locale=>value=>translations[locale]?.[value]||value;
