import fs from 'node:fs';const p='src/pages/dashboard/LearningWorkspace.jsx';let s=fs.readFileSync(p,'utf8').replace("import {requireBridgeObjective}","import {requireBridgeObjective,getCurriculumBridge,startReviewedBridgeObjective}").replace("import { useEffect, useState }", "import { useEffect, useMemo, useRef, useState }");const start=s.indexOf('function BridgeObjectiveEntry('),end=s.indexOf('function CurriculumLearningWorkspace(',start);
s=s.slice(0,start)+`function BridgeObjectiveEntry({transitionId,conceptId}) {
 const {ctx,revision,error:workspaceError}=useWorkspace(),[,setParams]=useSearchParams();
 const [error,setError]=useState(''),[retry,setRetry]=useState(0),[busy,setBusy]=useState(false);
 const request=useRef(null);
 useEffect(()=>()=>{request.current?.abort();},[ctx?.personId,ctx?.workspaceId,ctx?.locale,transitionId,conceptId]);
 const view=useMemo(()=>{if(!ctx)return null;try{const target=requireBridgeObjective(ctx,transitionId,conceptId);const plan=getCurriculumBridge(ctx,transitionId);const units=getLearningWorkspace(ctx).units;return {target,originals:plan.rows.filter(row=>row.status==='equivalent'&&row.target?.id===conceptId).map(row=>({...row,unit:units.find(unit=>unit.id===row.unitId)}))};}catch(failure){return {error:failure.message};}},[ctx?.personId,ctx?.workspaceId,ctx?.locale,revision,transitionId,conceptId,retry]);
 async function start(){if(busy)return;const controller=new AbortController();request.current=controller;setBusy(true);setError('');try{const unit=await startReviewedBridgeObjective({...ctx,signal:controller.signal},transitionId,conceptId);if(!controller.signal.aborted)setParams({unit:unit.id},{replace:true});}catch(failure){if(!controller.signal.aborted)setError(failure.message);}finally{if(!controller.signal.aborted)setBusy(false);}}
 if(workspaceError||view?.error)return <div className="v-page"><h1 className="v-title">Bridge activity unavailable</h1><p role="alert" className="v-notice v-error">{workspaceError||view.error}</p><button className="v-button mt-3" onClick={()=>setRetry(value=>value+1)}>Retry bridge activity</button><Link className="v-button mt-3" to="/dashboard/home">Return Home</Link></div>;
 if(!view)return <div className="v-page" role="status">Reading the sourced bridge objective…</div>;
 return <div className="v-page"><header><h1 className="v-title">Continue across curriculum sources</h1><p className="v-muted mt-2">{view.target.title} · {view.target.source?.provider} · version {view.target.source?.version}</p></header>
 <section className="v-card"><h2 className="text-lg font-medium">Your original work is retained</h2><p className="v-muted mt-2">Resume its saved explanation, check, practice or project on the original source. Recorded answers and review dates are not moved to the new curriculum.</p>{view.originals.length?view.originals.map(row=><article className="mt-4 rounded-xl border p-3" key={row.unitId}><h3 className="font-medium">{row.title}</h3><p className="v-muted mt-2">Saved step: {row.unit?.stage} · {row.reason}</p><Link className="v-button mt-3" to={row.originalPath}>Resume original work<span className="sr-only">: {row.title}</span></Link></article>):<p className="v-muted mt-3">No reviewed equivalent original activity is available for this objective. Your other saved work remains accessible from Home.</p>}</section>
 <section className="v-card"><h2 className="text-lg font-medium">Open the reviewed objective</h2><p className="v-muted mt-2">New-source work starts with its own explanation and checks. An existing unfinished activity on this exact source resumes its saved step. Prior mastery, answers, question drafts and project reviews are not copied.</p>{view.target.prerequisites.length>0&&<ul className="mt-3 list-disc space-y-2 pl-5">{view.target.prerequisites.map(item=><li key={item.id}>{item.title} · {item.priorReadiness?'Prior recorded readiness; review remains available':'Review this prerequisite before starting'}</li>)}</ul>}<button className="v-button primary mt-4" disabled={busy} onClick={start}>{busy?'Opening reviewed objective…':'Start or resume reviewed objective'}</button>{error&&<p className="v-notice v-error mt-3" role="alert">{error}</p>}</section><Link className="v-button" to="/dashboard/home">Return Home</Link></div>;
}
`+s.slice(end);fs.writeFileSync(p,s);
