import fs from 'node:fs';
const milestone=`

## 2026-10-02 — Canonical sharing, expiry integrity, activity-view export and Profile languages

Privacy now links to the canonical Connections center instead of exposing a second request/accept/revoke workflow. Existing records remain intact; the center retains scopes, approvers, lifecycle/history and actual mutation outcomes. A shared derived expiry state distinguishes unavailable metadata from expired permissions without inventing a transition or repairing bytes. Unreadable/blank/non-string dates block approval and summary/resource/organization access, including legacy readers. Explicit decline/cancel/revoke remains available for affected open records; original date fields are retained. Children shows the unavailable state without a report link or Invalid Date and allows closing before a new learner-approved request. Billing requests with invalid deadlines cannot activate a plan; this does not merge billing with learning consent.

An already-open learning activity's recovery export is now production-browser verified: visible question/options/current selection only, no assessment keys, no replacement of unreadable storage and no scored evidence. Restoring a valid saved copy and retrying restores the saved selection. Profile labels, accessible names and recovery/success messages now have Hindi/Bengali copy driven by interfaceLocale. User learning-area titles stay unchanged; teaching language remains independently scoped. Unmapped service errors retain their English fallback; no full translation claim.

316/316 full service tests and 6/6 focused connection-integrity tests pass. Final production build, both typechecks and scoped lint pass. Production browser checks pass for Privacy link/export/no permission mutation, valid request acceptance, unavailable legacy/v2 records and explicit close/date retention/refresh; parent blank-expiry report denial/close/renewal, malformed billing denial/Leave/date retention; already-open activity export/retry; Hindi/Bengali Profile draft recovery/export/name save/area duplicate/discard at 320px. Zero page errors/document overflow in these scenarios. A first parent browser run used the wrong /plans test URL; the corrected /subscription final run passes. Standard lint retains only the existing scripts-tmp/copyaudit/scan.js:84 parser error.

Evidence: scripts-tmp/connection-final-tests.txt, connection-integrity-focused.txt, connection-access-build.txt, connection-final-typecheck.txt, connection-final-lint.txt, connection-final-lint-full.txt, connection-integrity-browser.txt, parent-access-integrity-final-browser.txt, learning-view-export-browser.txt, profile-language-browser.txt. The shared expiry projection adds no storage namespace or fabricated lifecycle history. Broader curriculum/category/state/language/assistive-technology/native-device and full frontend gates remain open; no backend or founder-book request yet.
`;
for(const path of ['STATUS.md','QA.md','SHARED_ACCEPTANCE.md','AGI_LAUNCH_SEQUENCE.md'])fs.appendFileSync('docs/visionary/'+path,milestone);
fs.appendFileSync('docs/visionary/LOCAL_STORE_INVENTORY.md','\n\n2026-10-02 connection integrity: derived unavailable/expired states are read-only, add no namespace and do not rewrite imported dates. Explicit lifecycle closures retain original expiry fields. Profile translations and activity-view downloads add no persistence. Existing source ownership/schema/migration gates remain open.\n');
for(const role of ['parent','student'])fs.appendFileSync('docs/visionary/roles/'+role+'.md',milestone);
const path='docs/visionary/CURRENT_PRODUCT_STATUS.md';let s=fs.readFileSync(path,'utf8');s=s.replace('Next: broader content/category fixtures and remaining role/shared acceptance.','Completed and verified: canonical Privacy-to-Connections flow, malformed expiry/access denial and explicit closure, parent/billing recovery, already-open activity-view export, Hindi/Bengali Profile recovery. Next: structured curriculum authoring/distribution and broader content/category/role/shared acceptance.');s=s.replace('310/310 full service tests','316/316 full service tests');s=s.replace('Final build/typechecks/scoped lint pass. Standard lint','Production connection/parent/billing expiry-integrity, activity-view export and Hindi/Bengali Profile checks also pass. Final build/typechecks/scoped lint pass. Standard lint');s=s.replace('broader legacy consent/history reconciliation','broader legacy consent/history reconciliation');s=s.replace('1. Expand reviewed content/category fixtures and remaining connected-role/shared acceptance; verify current-view recovery export.','1. Build structured curriculum/objective authoring and scoped fixed distribution, then expand content/category and remaining connected-role/shared acceptance. Current-view recovery export is verified.');fs.writeFileSync(path,s);
