// Privacy body v2: each numbered section = text column + contained tinted
// visual panel (the live policies.google pattern), prose trimmed.
import { readFileSync, writeFileSync } from "node:fs";
const f = "src/pages/landing/PrivacyPage.jsx";
let s = readFileSync(f, "utf8");

const start = s.indexOf("        {/* DOCUMENT BODY */}");
const end = s.indexOf("        {/* KEY TERMS */}");
if (start === -1 || end === -1) { console.log("ANCHOR-MISS"); process.exit(1); }

const L = (a) => a.join("\n");
const body = L([
"        {/* DOCUMENT BODY — text column + contained visual panel per section */}",
"        <article className=\"px-6 pb-8 pt-14 sm:px-8\">",
"          <div className=\"mx-auto w-full max-w-[1040px]\">",
"            {/* 01 */}",
"            <section className=\"grid items-start gap-10 lg:grid-cols-[1fr_360px] lg:gap-16\">",
"              <div>",
"                <SectionHead id=\"what-we-collect\" kicker=\"01\" title=\"What we collect\" sub=\"The types of information Visionary collects as you use the service.\" />",
"                <H3>Things you create or provide</H3>",
"                <UL",
"                  items={[",
"                    \"Account details — your name, email address, role, and language.\",",
"                    \"The questions you ask and the content you provide while learning, teaching, or building.\",",
"                    \"Your learning activity — progress, practice results, projects, and feedback.\",",
"                  ]}",
"                />",
"                <H3>Information needed for the service to work</H3>",
"                <UL",
"                  items={[",
"                    \"Device and browser type, and basic usage information.\",",
"                    \"Service logs used to prevent abuse and diagnose problems.\",",
"                  ]}",
"                />",
"                <Detail title=\"What we do not collect\">",
"                  <p className=\"text-[14.5px] leading-[1.7]\" style={{ color: COLORS.grey }}>",
"                    No advertising identifiers. No tracking pixels. No behavioural profiles for advertising. Cookies on the public site are essential-only — the cookie policy lists every one of them.",
"                  </p>",
"                </Detail>",
"              </div>",
"              <Visual subject=\"learn\" tint=\"blueT\" />",
"            </section>",
"",
"            {/* 02 */}",
"            <section className=\"grid items-start gap-10 pt-14 lg:grid-cols-[1fr_360px] lg:gap-16\">",
"              <div>",
"                <SectionHead id=\"why-we-use-it\" kicker=\"02\" title=\"Why we use it\" sub=\"For the things you are trying to do — and very little else.\" />",
"                <UL",
"                  items={[",
"                    \"Provide Visionary — answer questions, guide practice, and keep your work in one place.\",",
"                    \"Keep your learning connected — carry understanding across sessions, devices, and years.\",",
"                    \"Maintain and improve the service — fix problems, and understand what is helping.\",",
"                    \"Protect people and the service — prevent misuse, and keep accounts safe.\",",
"                    \"Communicate with you — service updates, and the updates you choose to receive.\",",
"                  ]}",
"                />",
"                <P>Never by selling data or following people around the web.</P>",
"              </div>",
"              <Visual subject=\"practice\" tint=\"greenT\" />",
"            </section>",
"",
"            {/* 03 */}",
"            <section className=\"grid items-start gap-10 pt-14 lg:grid-cols-[1fr_360px] lg:gap-16\">",
"              <div>",
"                <SectionHead id=\"what-we-share\" kicker=\"03\" title=\"What we share\" sub=\"Your information is not sold, and it is not used for advertising. It depends on the relationship:\" />",
"                <div className=\"mt-5 overflow-hidden rounded-[12px] border\" style={{ borderColor: COLORS.mist }}>",
"                  {[",
"                    [\"Student\", \"Class-level progress is visible to the teacher of that class. Conversations stay private to the account.\"],",
"                    [\"Teacher\", \"Sees their classes. Never another class's data.\"],",
"                    [\"Parent\", \"Progress and activity — not private conversations.\"],",
"                    [\"Institution\", \"Aggregated, role-appropriate views only.\"],",
"                    [\"Service providers\", \"Only the processors that run the service — bound by contract to this page.\"],",
"                  ].map(([who, what], i, arr) => (",
"                    <div key={who} className={`px-5 py-4 ${i < arr.length - 1 ? \"border-b\" : \"\"}`} style={{ borderColor: COLORS.mist }}>",
"                      <p className=\"text-[14.5px] font-medium\" style={{ color: COLORS.ink }}>{who}</p>",
"                      <p className=\"mt-1 text-[14px] leading-[1.65]\" style={{ color: COLORS.grey }}>{what}</p>",
"                    </div>",
"                  ))}",
"                </div>",
"                <P>We may also share information to meet legal obligations under Indian law, handled through the grievance process below.</P>",
"              </div>",
"              <Visual subject=\"community\" tint=\"yellowT\" />",
"            </section>",
"",
"            {/* 04 */}",
"            <section className=\"grid items-start gap-10 pt-14 lg:grid-cols-[1fr_360px] lg:gap-16\">",
"              <div>",
"                <SectionHead id=\"your-controls\" kicker=\"04\" title=\"Your controls\" sub=\"See, manage, export, and delete your information — and change your mind at any time.\" />",
"                <UL",
"                  items={[",
"                    \"View — your account and learning history are visible to you at any time.\",",
"                    \"Manage — cookie preferences on the cookie policy page; email choices from any update.\",",
"                    \"Export — request a copy of your account information from the grievance officer.\",",
"                    \"Delete — request account deletion, and we will confirm what is removed.\",",
"                  ]}",
"                />",
"                <div className=\"mt-6 flex flex-wrap items-center gap-x-6 gap-y-3\">",
"                  <Link to=\"/cookies\" className=\"inline-flex items-center gap-2 text-[14.5px] font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#4285F4] rounded-sm\" style={{ color: COLORS.blue }}>",
"                    Manage cookie preferences",
"                    <ArrowRight className=\"h-4 w-4\" strokeWidth={1.8} />",
"                  </Link>",
"                  <Link to=\"/security\" className=\"inline-flex items-center gap-2 text-[14.5px] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#4285F4] rounded-sm\" style={{ color: COLORS.grey }}>",
"                    Review security practices",
"                    <ArrowRight className=\"h-4 w-4\" strokeWidth={1.8} />",
"                  </Link>",
"                </div>",
"              </div>",
"              <Visual subject=\"download\" tint=\"blueT\" />",
"            </section>",
"",
"            {/* 05 */}",
"            <section className=\"grid items-start gap-10 pt-14 lg:grid-cols-[1fr_360px] lg:gap-16\">",
"              <div>",
"                <SectionHead id=\"security\" kicker=\"05\" title=\"Security\" sub=\"Privacy needs security behind it.\" />",
"                <P>Visionary uses appropriate technical and organizational safeguards — including encryption in transit and access controls — to protect information against unauthorized access, alteration, deletion, or misuse.</P>",
"                <P>If something ever goes wrong, we will tell you what happened, what was affected, and what we did — through the grievance channel below.</P>",
"                <LearnMore to=\"/security\">How security works at Visionary</LearnMore>",
"              </div>",
"              <Visual subject=\"shield\" tint=\"greenT\" />",
"            </section>",
"",
"            {/* 06 */}",
"            <section className=\"grid items-start gap-10 pt-14 lg:grid-cols-[1fr_360px] lg:gap-16\">",
"              <div>",
"                <SectionHead id=\"retention\" kicker=\"06\" title=\"Retention\" sub=\"Keep what you need. Remove what you don't.\" />",
"                <P>Learning records are kept while your account is active — that continuity is the product. When information is no longer needed, it is deleted or anonymized.</P>",
"                <Detail title=\"What deletion covers\">",
"                  <UL",
"                    items={[",
"                      \"Account details and login records.\",",
"                      \"Learning activity, progress, and projects.\",",
"                      \"Conversations and the personal memory built from them.\",",
"                    ]}",
"                  />",
"                  <p className=\"mt-4 text-[14px] leading-[1.7]\" style={{ color: COLORS.grey }}>",
"                    Some records are kept where the law requires it — for example, billing records — for the period the law sets.",
"                  </p>",
"                </Detail>",
"              </div>",
"              <Visual subject=\"history\" tint=\"redT\" />",
"            </section>",
"",
"            {/* 07 */}",
"            <section className=\"grid items-start gap-10 pt-14 lg:grid-cols-[1fr_360px] lg:gap-16\">",
"              <div>",
"                <SectionHead id=\"younger-learners\" kicker=\"07\" title=\"Younger learners\" sub=\"Extra care for students who are children.\" />",
"                <P>Where a learner is a child under the DPDP Act, we process their information only with the consent of their parent or guardian, given through their school or directly to us.</P>",
"                <UL",
"                  items={[",
"                    \"Never used for advertising, never profiled for marketing.\",",
"                    \"Never shared beyond what is needed to provide the service.\",",
"                    \"Parents can review and delete through the grievance process.\",",
"                  ]}",
"                />",
"                <LearnMore to=\"/safety\">How safety works for younger learners</LearnMore>",
"              </div>",
"              <Visual subject=\"safety\" tint=\"yellowT\" />",
"            </section>",
"",
"            {/* 08 */}",
"            <section className=\"grid items-start gap-10 pt-14 lg:grid-cols-[1fr_360px] lg:gap-16\">",
"              <div>",
"                <SectionHead id=\"grievance-officer\" kicker=\"08\" title=\"Grievance officer\" sub=\"Under the DPDP Act, 2023, a named person answers privacy requests.\" />",
"                <div className=\"rounded-[12px] border p-6\" style={{ borderColor: COLORS.mist }}>",
"                  <p className=\"text-[14.5px] leading-[1.7]\" style={{ color: COLORS.grey }}>",
"                    {GRIEVANCE_OFFICER.role}: <strong style={{ color: COLORS.ink }}>{GRIEVANCE_OFFICER.name}</strong>",
"                  </p>",
"                  <p className=\"mt-3\">",
"                    <a href={`mailto:${GRIEVANCE_OFFICER.email}`} className=\"inline-flex items-center gap-2 text-[15px] font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#4285F4] rounded-sm\" style={{ color: COLORS.blue }}>",
"                      {GRIEVANCE_OFFICER.email}",
"                      <ArrowRight className=\"h-4 w-4\" strokeWidth={1.8} />",
"                    </a>",
"                  </p>",
"                  <p className=\"mt-3 text-[14px] leading-[1.7]\" style={{ color: COLORS.grey }}>{GRIEVANCE_OFFICER.response}</p>",
"                </div>",
"                <P>Not satisfied with the outcome? You can escalate to the Data Protection Board under the Act.</P>",
"              </div>",
"              <Visual subject=\"mail\" tint=\"greenT\" />",
"            </section>",
"          </div>",
"        </article>",
"",
"        ",
]);
s = s.slice(0, start) + body + s.slice(end);

// Visual panel helper (after LearnMore definition)
if (!s.includes("function Visual(")) {
  s = s.replace(
    "export default function PrivacyPage()",
    L([
      "function Visual({ subject, tint }) {",
      "  return (",
      "    <div className=\"overflow-hidden rounded-[20px] border lg:sticky lg:top-24\" style={{ borderColor: COLORS.mist }}>",
      "      <div style={{ backgroundColor: `var(--pt, #F1F3F4)` }}>",
      "        <SpotIllustration subject={subject} className=\"aspect-[4/3] w-full\" />",
      "      </div>",
      "    </div>",
      "  );",
      "}",
      "",
      "export default function PrivacyPage()",
    ])
  );
}
// SpotIllustration import
if (!s.includes("SpotIllustration")) {
  s = s.replace(
    'import { LEGAL_META, GRIEVANCE_OFFICER } from "@/data/legalMeta";',
    'import { LEGAL_META, GRIEVANCE_OFFICER } from "@/data/legalMeta";\nimport SpotIllustration from "@/components/landing/SpotIllustration";'
  );
}
// tint backgrounds: pass style tint directly via prop map
s = s.replace(
  /<Visual subject="([a-z]+)" tint="([a-zA-Z]+)" \/>/g,
  '<Visual subject="$1" tint={COLORS.$2} />'
);
s = s.replace(
  "      <div style={{ backgroundColor: `var(--pt, #F1F3F4)` }}>",
  "      <div style={{ backgroundColor: tint }}>"
);
writeFileSync(f, s);
console.log("privacy body v2 with visual panels written");
