const { chromium } = await import('playwright-core');
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--no-proxy-server'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
await context.addInitScript(`(() => {
  const user = { id: 'demo-teacher', email: 'teacher@visionary.test', full_name: 'Dev', identity: 'teacher', onboarding_complete: true, age_band: 'adult', roles: ['teacher'] };
  localStorage.setItem('visionary_users', JSON.stringify([user]));
  localStorage.setItem('visionary_sessions', JSON.stringify([{ token: 'qa-view-token', userId: user.id, email: user.email, expiresAt: Date.now() + 86400000, createdAt: Date.now() }]));
  localStorage.setItem('visionary_session_token', 'qa-view-token');
  const wsId = 'demo-teacher:teacher';
  const learnerWsId = 'demo-minor-cbse:student';
  const parentWsId = 'demo-parent:parent';
  const emptyData = { conversations: [], sessions: [], artifacts: [], resources: [], notifications: [], audit: [], preferences: { locale: 'en', interfaceLocale: 'en', bilingual: false, lowBandwidth: false, notifications: 'weekly', memory: true, voice: true }, subscription: { plan: 'Free', state: 'active', invoices: [], usage: 0, usageDay: '2026-09-26' }, legacyImported: false };
  const db = { version: 2, people: [{ id: 'demo-teacher', email: 'teacher@visionary.test', name: 'Dev', ageBand: 'adult', roles: ['teacher'] }, { id: 'demo-minor-cbse', email: 'minor-cbse@visionary.test', name: 'Aarav', ageBand: 'minor', roles: ['student'], learningContext: { classLevel: '7', subjects: ['Mathematics'] } }, { id: 'demo-parent', email: 'parent@visionary.test', name: 'Anika', ageBand: 'adult', roles: ['parent'] }], workspaces: [{ id: wsId, personId: 'demo-teacher', role: 'teacher', name: 'Teacher space', lastPath: '/dashboard/home' }, { id: learnerWsId, personId: 'demo-minor-cbse', role: 'student', name: 'Learner space', lastPath: '/dashboard/home' }, { id: parentWsId, personId: 'demo-parent', role: 'parent', name: 'Parent space', lastPath: '/dashboard/reports' }], active: { 'demo-teacher': wsId, 'demo-minor-cbse': learnerWsId, 'demo-parent': parentWsId }, relationships: [{ id: 'demo-parent:demo-minor-cbse', from: 'demo-parent', to: 'demo-minor-cbse', type: 'guardian', status: 'active', scope: ['progress-summary'] }], data: { [wsId]: { ...emptyData }, [learnerWsId]: { ...emptyData }, [parentWsId]: { ...emptyData } } };
  localStorage.setItem('visionary_workspace_v2', JSON.stringify(db));
  localStorage.setItem('visionary_entity_Classroom', JSON.stringify([{ id: 'demo-class-cube', name: 'Space, shape and reasoning', subject: 'Geometry', teacher_email: 'teacher@visionary.test', teacher_id: 'demo-teacher', teacher_name: 'Dev', join_code: 'DEMO-CUBE', color: '#1967d2', createdAt: Date.now() }]));
  localStorage.setItem('visionary_entity_Enrollment', JSON.stringify([{ id: 'qa-enrollment-aarav', class_id: 'demo-class-cube', student_email: 'minor-cbse@visionary.test', student_id: 'demo-minor-cbse', student_name: 'Aarav', status: 'active', createdAt: Date.now() }]));
})()`);
const page = await context.newPage();
const errors = [];
page.on('pageerror', e => errors.push(String(e).slice(0, 120)));
await page.goto('http://127.0.0.1:4187/dashboard/class/demo-class-cube', { waitUntil: 'networkidle', timeout: 30000 });
await page.waitForTimeout(2000);
await page.getByText('Record class promotion').first().click();
await page.getByLabel('Next class level').fill('8');
await page.getByLabel('Promotion reason').fill('End of year promotion');
await page.getByRole('button', { name: 'Record promotion' }).click();
await page.waitForTimeout(600);
const summary = await page.getByText(/learner moved to class 8/).count();
console.log(`promotion: summaryVisible=${summary > 0} errors=${errors.length}`);
if (!summary || errors.length) throw new Error(`Promotion browser check failed: summary=${summary}, errors=${errors.join('; ')}`);
await page.screenshot({ path: 'docs/visionary/baseline/design-2026-09-27/teacher-promotion.png', clip: { x: 0, y: 60, width: 1440, height: 500 } });
const promotedState = await context.storageState();
async function openParent(state) {
  const parentContext = await browser.newContext({ storageState: state, viewport: { width: 390, height: 844 } });
  await parentContext.addInitScript(() => {
    const parent = { id: 'demo-parent', email: 'parent@visionary.test', full_name: 'Anika', identity: 'parent', onboarding_complete: true, age_band: 'adult', roles: ['parent'] };
    const users = JSON.parse(localStorage.getItem('visionary_users') || '[]');
    localStorage.setItem('visionary_users', JSON.stringify([...users, parent]));
    const sessions = JSON.parse(localStorage.getItem('visionary_sessions') || '[]');
    localStorage.setItem('visionary_sessions', JSON.stringify([...sessions, { token: 'parent-qa-token', userId: parent.id, email: parent.email, expiresAt: Date.now() + 86400000, createdAt: Date.now() }]));
    localStorage.setItem('visionary_session_token', 'parent-qa-token');
  });
  const parentPage = await parentContext.newPage();
  parentPage.on('pageerror', e => errors.push(String(e).slice(0, 120)));
  await parentPage.goto('http://127.0.0.1:4187/dashboard/reports?child=demo-minor-cbse', { waitUntil: 'networkidle' });
  return { parentContext, parentPage };
}
const { parentContext: promotedParentContext, parentPage: promotedParentPage } = await openParent(promotedState);
await promotedParentPage.getByText('Moved from Class 7 to Class 8.').waitFor();
await promotedParentPage.screenshot({ path: 'docs/visionary/baseline/design-2026-09-27/parent-promotion-mobile.png' });
await promotedParentContext.close();
const learnerContext = await browser.newContext({ storageState: promotedState, viewport: { width: 390, height: 844 } });
await learnerContext.addInitScript(() => {
  const learner = { id: 'demo-minor-cbse', email: 'minor-cbse@visionary.test', full_name: 'Aarav', identity: 'student', onboarding_complete: true, age_band: 'minor', roles: ['student'], grade_level: '7' };
  const users = JSON.parse(localStorage.getItem('visionary_users') || '[]');
  localStorage.setItem('visionary_users', JSON.stringify([...users, learner]));
  const sessions = JSON.parse(localStorage.getItem('visionary_sessions') || '[]');
  localStorage.setItem('visionary_sessions', JSON.stringify([...sessions, { token: 'learner-qa-token', userId: learner.id, email: learner.email, expiresAt: Date.now() + 86400000, createdAt: Date.now() }]));
  localStorage.setItem('visionary_session_token', 'learner-qa-token');
});
const learnerPage = await learnerContext.newPage();
learnerPage.on('pageerror', e => errors.push(String(e).slice(0, 120)));
await learnerPage.goto('http://127.0.0.1:4187/dashboard/home', { waitUntil: 'networkidle' });
await learnerPage.getByRole('heading', { name: 'Your stage changed' }).waitFor();
await learnerPage.reload({ waitUntil: 'networkidle' });
await learnerPage.getByRole('heading', { name: 'Your stage changed' }).waitFor();
await learnerPage.screenshot({ path: 'docs/visionary/baseline/design-2026-09-27/learner-promotion-mobile.png' });
await learnerPage.goto('http://127.0.0.1:4187/dashboard/learn', { waitUntil: 'networkidle' });
await learnerPage.getByRole('button', { name: 'Try authored learning sample' }).click();
await learnerPage.getByRole('heading', { name: 'Mathematics' }).waitFor();
await learnerPage.getByRole('region', { name: 'Subject chapters' }).getByRole('button').first().click();
await learnerPage.locator('section[aria-label$="learning path"]').getByRole('button', { name: /^Start / }).first().click();
await learnerPage.getByRole('heading', { name: 'Understand one idea' }).waitFor();
const laterUnitId = await learnerPage.evaluate(() => JSON.parse(localStorage.getItem('visionary_learning_pipeline_v1')).spaces['demo-minor-cbse:student'].units[0].id);
await learnerPage.goto('http://127.0.0.1:4187/dashboard/home', { waitUntil: 'networkidle' });
await learnerPage.getByRole('button', { name: 'Undo this change' }).click();
await learnerPage.reload({ waitUntil: 'networkidle' });
const restoredLevel = await learnerPage.evaluate(() => JSON.parse(localStorage.getItem('visionary_workspace_v2')).people.find(person => person.id === 'demo-minor-cbse').learningContext.classLevel);
const retainedUnit = await learnerPage.evaluate(id => JSON.parse(localStorage.getItem('visionary_learning_pipeline_v1')).spaces['demo-minor-cbse:student'].units.some(unit => unit.id === id), laterUnitId);
const noticeCount = await learnerPage.getByRole('heading', { name: 'Your stage changed' }).count();
if (restoredLevel !== '7' || !retainedUnit || noticeCount || errors.length) throw new Error(`Paired promotion failed: level=${restoredLevel}, retainedUnit=${retainedUnit}, notice=${noticeCount}, errors=${errors.join('; ')}`);
console.log('learner: notice survives refresh, later learning work stays, Undo restores class 7');
const undoneState = await learnerContext.storageState();
const { parentContext: undoneParentContext, parentPage: undoneParentPage } = await openParent(undoneState);
await undoneParentPage.getByText('The move to Class 8 was undone. Current class: Class 7.').waitFor();
await undoneParentPage.goto('http://127.0.0.1:4187/dashboard/child', { waitUntil: 'networkidle' });
await undoneParentPage.getByRole('button', { name: 'Stop sharing' }).click();
await undoneParentPage.goto('http://127.0.0.1:4187/dashboard/reports?child=demo-minor-cbse', { waitUntil: 'networkidle' });
await undoneParentPage.getByRole('heading', { name: 'This report is no longer shared' }).waitFor();
if (errors.length) throw new Error(`Cross-role browser journey had page errors: ${errors.join('; ')}`);
console.log('parent: stage update, Undo status and revocation verified in the rendered report');
await undoneParentContext.close();
await learnerContext.close();
await browser.close();
