const { chromium } = await import('playwright-core');
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--no-proxy-server'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
await context.addInitScript(`(() => {
  const user = { id: 'demo-teacher', email: 'teacher@visionary.test', full_name: 'Dev', identity: 'teacher', onboarding_complete: true, age_band: 'adult', roles: ['teacher'] };
  localStorage.setItem('visionary_users', JSON.stringify([user]));
  localStorage.setItem('visionary_sessions', JSON.stringify([{ token: 'qa-view-token', userId: user.id, email: user.email, expiresAt: Date.now() + 86400000, createdAt: Date.now() }]));
  localStorage.setItem('visionary_session_token', 'qa-view-token');
  const wsId = 'demo-teacher:teacher';
  const learnerWsId = 'demo-minor-cbse:student';
  const emptyData = { conversations: [], sessions: [], artifacts: [], resources: [], notifications: [], audit: [], preferences: { locale: 'en', interfaceLocale: 'en', bilingual: false, lowBandwidth: false, notifications: 'weekly', memory: true, voice: true }, subscription: { plan: 'Free', state: 'active', invoices: [], usage: 0, usageDay: '2026-09-26' }, legacyImported: false };
  const db = { version: 2, people: [{ id: 'demo-teacher', email: 'teacher@visionary.test', name: 'Dev', ageBand: 'adult', roles: ['teacher'] }, { id: 'demo-minor-cbse', email: 'minor-cbse@visionary.test', name: 'Aarav', ageBand: 'minor', roles: ['student'] }], workspaces: [{ id: wsId, personId: 'demo-teacher', role: 'teacher', name: 'Teacher space', lastPath: '/dashboard/home' }, { id: learnerWsId, personId: 'demo-minor-cbse', role: 'student', name: 'Learner space', lastPath: '/dashboard/home' }], active: { 'demo-teacher': wsId, 'demo-minor-cbse': learnerWsId }, relationships: [], data: { [wsId]: { ...emptyData }, [learnerWsId]: { ...emptyData } } };
  localStorage.setItem('visionary_workspace_v2', JSON.stringify(db));
  localStorage.setItem('visionary_entity_Classroom', JSON.stringify([{ id: 'demo-class-cube', name: 'Space, shape and reasoning', subject: 'Geometry', teacher_email: 'teacher@visionary.test', teacher_id: 'demo-teacher', teacher_name: 'Dev', join_code: 'DEMO-CUBE', color: '#1967d2', createdAt: Date.now() }]));
  localStorage.setItem('visionary_entity_Enrollment', JSON.stringify([{ id: 'qa-enrollment-aarav', class_id: 'demo-class-cube', student_email: 'minor-cbse@visionary.test', student_id: 'demo-minor-cbse', student_name: 'Aarav', status: 'active', createdAt: Date.now() }]));
})()`);
const page = await context.newPage();
const errors = [];
page.on('pageerror', e => errors.push(String(e).slice(0, 120)));
await page.goto('http://localhost:4173/dashboard/class/demo-class-cube', { waitUntil: 'networkidle', timeout: 30000 }).catch(() => {});
await page.waitForTimeout(2000);
await page.getByText('Record class promotion').first().click();
await page.getByLabel('Next class level').fill('8');
await page.getByLabel('Promotion reason').fill('End of year promotion');
await page.getByRole('button', { name: 'Record promotion' }).click();
await page.waitForTimeout(600);
const summary = await page.getByText(/learner moved to class 8/).count();
console.log(`promotion: summaryVisible=${summary > 0} errors=${errors.length}`);
await page.screenshot({ path: 'scripts-tmp/promotion-teacher.png', clip: { x: 0, y: 60, width: 1440, height: 500 } });
await browser.close();
