import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useWorkspace} from '@/hooks/useWorkspace';
import {visibleRelationships,requestRelationship,changeRelationship} from '@/services/workspaceService';
export default function Children(){
 const {ctx,data}=useWorkspace();const [email,setEmail]=useState('');const [notice,setNotice]=useState('');if(!ctx||!data)return <div className="v-page" role="status">Opening family workspace…</div>;
 const relationships=visibleRelationships(ctx).filter(r=>r.type==='guardian'&&r.from===ctx.personId);
 return <div className="v-page"><header><h1 className="v-title">Your children</h1><p className="v-muted mt-2">A separate, permission-based connection for each learner.</p></header><section className="v-card"><h2 className="text-lg font-medium">Request progress sharing</h2><p className="v-muted mt-3">The learner’s local account must accept before summaries appear. This preview does not verify guardianship. Do not enter real child information.</p><form className="mt-5 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();try{requestRelationship(ctx,email,'guardian');setEmail('');setNotice('Local request saved. No email or verification service was contacted.');}catch(e){setNotice(e.message);}}}><label className="min-w-0 flex-1"><span className="sr-only">Learner demo email</span><input type="email" className="v-field" required placeholder="learner@visionary.test" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="v-button">Request sharing</button></form></section>{notice&&<p role="status" className="v-notice">{notice}</p>}<section className="v-card">{relationships.length?relationships.map(r=><div className="v-list-row" key={r.id}><div className="min-w-0"><h2 className="text-base font-medium break-words">{r.name}</h2><p className="v-muted">{r.status} · Progress summaries only</p></div><div className="flex flex-wrap gap-2">{r.status==='active'&&<Link className="v-button" to={`/dashboard/reports?child=${encodeURIComponent(r.to)}`}>View report</Link>}{['active','pending'].includes(r.status)&&<button className="v-button" onClick={()=>{try{changeRelationship(ctx,r.id,'revoked');setNotice('Sharing stopped. The learner’s own work is retained.');}catch(e){setNotice(e.message);}}}>{r.status==='pending'?'Cancel request':'Stop sharing'}</button>}</div></div>):<p className="v-muted">No connected learners yet. Personal conversations, project drafts, and billing membership are never included in progress access.</p>}</section><Link className="text-sm text-[#4285F4] underline" to="/dashboard/privacy">Review consent history and privacy</Link></div>;
}
