import {useEffect,useState,useRef} from 'react';
import {Link} from 'react-router-dom';
import {useWorkspace} from '@/hooks/useWorkspace';
import {classworkTranslator} from '@/lib/classworkCopy';
import {getClassworkActivity,submitClassworkActivity,classworkActivityRevision} from '@/services/classworkPlayerService';
import {readClassworkDrafts,saveClassworkDraft,classworkDraftRevision,classworkDraftKey} from '@/services/classworkDraftService';
import {assignmentAcceptsResponses} from '@/lib/assignmentAvailability';
import {downloadText} from '@/lib/downloadText';
import ClassworkProjectSubmission from '@/components/dashboard/ClassworkProjectSubmission';
import LessonObjectivePreview from '@/components/dashboard/LessonObjectivePreview';
import {classworkResponseText} from '@/services/classroomService';
import CriterionFeedback from '@/components/dashboard/CriterionFeedback';

export default function ClassworkLearningPlayer({assignmentId}){
 const {ctx,data,error:workspaceError}=useWorkspace();const locale=data?.preferences.interfaceLocale||'en',t=classworkTranslator(locale);const [activity,setActivity]=useState(null);const [draft,setDraft]=useState({});const [stage,setStage]=useState('understand');const [busy,setBusy]=useState(true);const [error,setError]=useState('');const [draftError,setDraftError]=useState('');const [retry,setRetry]=useState(0);const [refreshing,setRefreshing]=useState(false);const base=useRef('null');const readable=useRef(false);const draftWorkspace=useRef(null);
 useEffect(()=>{let live=true;setActivity(null);setRefreshing(false);setError('');setBusy(true);if(!ctx)return;(async()=>{const view=await getClassworkActivity(ctx,assignmentId);let restored={};try{restored=readClassworkDrafts(ctx)[assignmentId]||{};readable.current=true;if(live)setDraftError('');}catch(failure){readable.current=false;if(live)setDraftError(failure.message);}if(view.submission?.status==='revision_requested'&&restored.revisionAttempt!==(view.submission.attempt||1))restored={...restored,text:classworkResponseText(view.assignment,view.submission),answers:Object.fromEntries((view.submission.responses||[]).map(answer=>[answer.questionId,answer.text])),revisionAttempt:view.submission.attempt||1,selfReview:view.submission.self_review||{}};if(live){draftWorkspace.current=ctx.workspaceId;base.current=classworkDraftRevision(readable.current?readClassworkDrafts(ctx)[assignmentId]:null);setDraft(restored);setStage(['understand','respond','review'].includes(restored.playerStage)?restored.playerStage:'understand');setActivity({...view,workspaceId:ctx.workspaceId});}})().catch(failure=>{if(live)setError(failure.message);}).finally(()=>{if(live)setBusy(false);});return()=>{live=false;};},[ctx?.workspaceId,assignmentId,retry]);
 useEffect(()=>{if(!ctx)return;let live=true;let sequence=0;const refresh=()=>{const current=++sequence;setRefreshing(true);getClassworkActivity(ctx,assignmentId).then(view=>{if(live&&current===sequence){setActivity({...view,workspaceId:ctx.workspaceId});setError('');}}).catch(failure=>{if(live&&current===sequence){setActivity(null);setError(failure.message);}}).finally(()=>{if(live&&current===sequence)setRefreshing(false);});};window.addEventListener('storage',refresh);window.addEventListener('visionary:workspace-change',refresh);return()=>{live=false;window.removeEventListener('storage',refresh);window.removeEventListener('visionary:workspace-change',refresh);};},[ctx?.workspaceId,assignmentId]);
 function edit(patch){const next={...draft,...patch};setDraft(next);if(!readable.current){setDraftError(t("Older saved drafts remain unreadable. Keep this page open and export your current response."));return;}try{saveClassworkDraft(ctx,assignmentId,next,base.current);base.current=classworkDraftRevision(next);setDraftError('');}catch(failure){setDraftError(failure.message);}}
 function move(next){setStage(next);edit({playerStage:next});}
 function exportCurrent(){const checks=activity?.assignment.checks||[];const response=checks.length?checks.map(item=>`${item.prompt}\n${draft.answers?.[item.id]||''}`).join('\n\n'):draft.text||Object.values(draft.answers||{}).join('\n\n');const criteria=activity?.assignment.objective_snapshot?.criteria||[];const notes=criteria.length?criteria.map(item=>`${item.label}: ${draft.selfReview?.[item.id]||t("Not reviewed yet")}`):Object.entries(draft.selfReview||{}).map(([id,note])=>`${id}: ${note}`);downloadText(`visionary-classwork-${assignmentId}.txt`,response+(notes.length?`\n\n${t("Current criterion notes")}\n${notes.join('\n\n')}`:''));}
 function saved(submission){setActivity(current=>({...activity,...current,submission}));try{saveClassworkDraft(ctx,assignmentId,null,base.current);base.current='null';setDraft({});setDraftError('');}catch(failure){setDraftError(`${t("Your response was submitted.")} ${failure.message}`);}window.dispatchEvent(new CustomEvent('visionary:workspace-change'));}
 async function submit(){setBusy(true);setError('');try{const checks=activity.assignment.checks||[];saved(await submitClassworkActivity(ctx,{assignmentId,expectedRevision:classworkActivityRevision(activity.assignment),text:draft.text||'',responses:checks.map(item=>({questionId:item.id,text:draft.answers?.[item.id]||''})),selfReview:draft.selfReview||{}}));}catch(failure){setError(failure.message);}finally{setBusy(false);}}
 if(!ctx||workspaceError)return <div lang={locale} className="v-page" role={workspaceError?'alert':'status'}>{workspaceError||t("Opening your workspace…")}</div>;
 if(!activity||activity.workspaceId!==ctx.workspaceId)return <div lang={locale} className="v-page"><h1 className="v-title">{t("Class activity")}</h1>{busy||!error?<p role="status">{t("Opening the saved assignment…")}</p>:<><p role="alert" className="v-notice v-error">{error}</p><button className="v-button mt-4" onClick={()=>setRetry(value=>value+1)}>{t("Retry activity")}</button>{draftWorkspace.current===ctx.workspaceId&&(draft.text||Object.keys(draft.answers||{}).length||Object.keys(draft.selfReview||{}).length)&&<button className="v-button mt-4" onClick={exportCurrent}>{t("Export current response")}</button>}</>}<Link className="v-button mt-4" to="/dashboard/classes">{t("Open my classes")}</Link></div>;
 const {assignment,classroom,submission}=activity;const checks=assignment.checks||[];const returned=submission&&submission.status!=='revision_requested';const ready=checks.length?checks.every(item=>draft.answers?.[item.id]?.trim()):Boolean(draft.text?.trim());const open=assignmentAcceptsResponses(assignment);const criteria=assignment.objective_snapshot?.criteria||[];const reviewed=criteria.every(item=>draft.selfReview?.[item.id]?.trim());
 return <div lang={locale} className="v-page" aria-busy={refreshing}><header><Link className="v-button" to={`/dashboard/classes?class=${encodeURIComponent(classroom.id)}`}>{t("Back to classwork")}</Link><p className="v-home-eyebrow mt-5">{classroom.name} · {t("Teacher-authored activity")}</p><h1 lang={assignment.objective_snapshot?.locale} className="v-title mt-2">{assignment.title}</h1><p className="v-muted mt-3">{assignment.points||100} {t("points")}{assignment.due_date?` · ${t("Due")} ${assignment.due_date}`:''} . {t("Saved on this device. Your teacher reviews written responses; this activity does not automatically score understanding or establish mastery.")}</p>{assignment.source_version&&<p className="v-muted mt-2 break-all">{t("Assigned source version")}: {assignment.source_version}</p>}<div className="mt-4 flex flex-wrap gap-2"><Link className="v-button" to={`/dashboard/ask?assignment=${encodeURIComponent(assignmentId)}`}>{t("Ask about this assignment")}</Link><Link className="v-button" to={`/dashboard/practice?assignment=${encodeURIComponent(assignmentId)}`}>{t("Rehearse this objective")}</Link></div></header>
 {refreshing&&<p role="status" className="v-muted">{t("Checking class access and refreshing the saved activity…")}</p>}{error&&<p role="alert" className="v-notice v-error">{error}</p>}{draftError&&<div role="alert" className="v-notice v-error">{draftError}<div className="mt-3 flex flex-wrap gap-2"><button className="v-button" onClick={exportCurrent}>{t("Export current response")}</button><button className="v-button" onClick={()=>downloadText('visionary-saved-classwork-drafts.txt',localStorage.getItem(classworkDraftKey(ctx))||'')}>{t("Export saved drafts backup")}</button><button className="v-button" onClick={()=>{try{const latest=readClassworkDrafts(ctx)[assignmentId]||{};setDraft(latest);base.current=classworkDraftRevision(Object.keys(latest).length?latest:null);readable.current=true;setDraftError('');setStage(['understand','respond','review'].includes(latest.playerStage)?latest.playerStage:'understand');}catch(failure){setDraftError(failure.message);}}}>{t("Discard current edits and load latest draft")}</button></div></div>}
 {returned?<section className="v-card"><h2 className="text-lg font-medium">{submission.status==='graded'?t("Returned by your teacher"):t("Submitted for review")}</h2>{submission.status==='graded'&&<p className="mt-3">{submission.grade}/{assignment.points||100} {t("points")}</p>}{submission.feedback&&<p className="mt-3 whitespace-pre-wrap">{submission.feedback}</p>}<CriterionFeedback criteria={criteria} feedback={submission.criterion_feedback}/><details className="mt-4"><summary className="cursor-pointer">{t("Your submitted copy")}</summary><p className="mt-3 whitespace-pre-wrap break-words">{submission.text}</p></details><button className="v-button mt-4" onClick={()=>setRetry(value=>value+1)}>{t("Refresh feedback")}</button></section>:<>
 {submission?.status==='revision_requested'&&<p className="v-notice" role="status">{t("Revision requested")} · {t("Attempt")} {submission.attempt||1}: {submission.feedback}</p>}
 <CriterionFeedback criteria={criteria} feedback={submission?.status==='revision_requested'?submission.criterion_feedback:{}}/><nav className="v-learning-stages" aria-label={t("Class activity stages")}>{[['understand',t("Understand")],['respond',t("Respond")],['review',t("Review")]].map(([id,label],index)=><button key={id} className={stage===id?'v-button primary':'v-button'} aria-current={stage===id?'step':undefined} disabled={busy} onClick={()=>move(id)}>{index+1}. {label}</button>)}</nav>
 {stage==='understand'&&<section className="v-card"><h2 className="text-lg font-medium">{t("Understand the assigned activity")}</h2><p lang={assignment.description?assignment.objective_snapshot?.locale:locale} className="mt-4 whitespace-pre-wrap leading-8">{assignment.description||t("Your teacher has not supplied an explanation. Review the assignment title and ask your teacher for clarification before responding.")}</p>{assignment.objective_snapshot?<LessonObjectivePreview objective={assignment.objective_snapshot} preferText={Boolean(data?.preferences.lowBandwidth)} value={draft.objectiveRevision===JSON.stringify(assignment.objective_snapshot)?draft.objectiveView:undefined} onChange={patch=>edit({objectiveRevision:JSON.stringify(assignment.objective_snapshot),objectiveView:{...(draft.objectiveRevision===JSON.stringify(assignment.objective_snapshot)?draft.objectiveView:{}),...patch}})}/>:<p className="v-muted mt-4">{t("No reviewed interactive representation or objective mapping was attached to this assignment. The saved instructions remain available; visual or model-generated content has not been invented.")}</p>}<button className="v-button primary mt-5" onClick={()=>move('respond')}>{t("Continue to response")}</button></section>}
 {stage==='respond'&&<section className="v-card"><h2 className="text-lg font-medium">{t("Explain in your own words")}</h2>{checks.length?checks.map((item,index)=><label className="mt-4 block text-sm" key={item.id}>{index+1}. {item.prompt}<textarea aria-label={`${index+1}. ${item.prompt}`} maxLength={5000} className="v-field mt-2 min-h-28" value={draft.answers?.[item.id]||''} onChange={event=>edit({answers:{...draft.answers,[item.id]:event.target.value}})} disabled={busy||!open}/></label>):<><textarea aria-label={t("Class activity response")} className="v-field mt-4 min-h-36" maxLength={50000} value={draft.text||''} disabled={busy||!open} onChange={event=>edit({text:event.target.value})}/>{open&&<div className="mt-4"><ClassworkProjectSubmission ctx={ctx} artifacts={data?.artifacts} assignment={{...assignment,revisionRequested:submission?.status==='revision_requested'}} onSubmitted={saved}/></div>}</>}{!!criteria.length&&<section className="mt-5"><h3 className="font-medium">{t("Review the assigned criteria")}</h3><p className="v-muted mt-2">{t("These notes go to your teacher with the response. They are your self-review, not an automatic grade.")}</p>{criteria.map(item=><label className="mt-4 block text-sm" key={item.id}><span lang={assignment.objective_snapshot?.locale}>{item.label}: {item.prompt}</span><textarea aria-label={`${t("Criterion review")}: ${item.label}`} className="v-field mt-2" maxLength={2000} value={draft.selfReview?.[item.id]||''} disabled={busy||!open} onChange={event=>edit({selfReview:{...draft.selfReview,[item.id]:event.target.value}})}/></label>)}</section>}<button className="v-button primary mt-5" disabled={!ready||!reviewed||busy} onClick={()=>move('review')}>{t("Review my response")}</button></section>}
 {stage==='review'&&<section className="v-card"><h2 className="text-lg font-medium">{t("Review the copy your teacher will receive")}</h2><p className="v-muted mt-3">{t("Submitting sends this response to your class teacher. Private learning notes and project drafts are excluded. An earlier attempt stays in the response history.")}</p>{checks.length?checks.map(item=><div className="mt-4" key={item.id}><p className="font-medium">{item.prompt}</p><p className="mt-2 whitespace-pre-wrap break-words">{draft.answers?.[item.id]||t("No response yet")}</p></div>):<p className="mt-4 whitespace-pre-wrap break-words">{draft.text||t("No response yet")}</p>}{!!criteria.length&&<section className="mt-4"><h3 className="font-medium">{t("Criterion self-review included in this copy")}</h3>{criteria.map(item=><p className="mt-3 whitespace-pre-wrap" key={item.id}>{item.label}: {draft.selfReview?.[item.id]||t("Not reviewed yet")}</p>)}</section>}<div className="mt-5 flex flex-wrap gap-3"><button className="v-button" onClick={()=>move('respond')}>{t("Edit response")}</button><button className="v-button primary" disabled={!ready||!reviewed||busy||refreshing||!open} onClick={submit}>{busy?t("Submitting…"):submission?.status==='revision_requested'?t("Resubmit to teacher"):t("Submit to teacher")}</button><button className="v-button" onClick={exportCurrent}>{t("Export current response")}</button></div></section>}
 {!open&&!refreshing&&<p role="status" className="v-notice">{t("Submissions are closed. Your draft remains saved. Your teacher can reopen this activity.")}</p>}
 </>}{!!submission?.revision_history?.length&&<details className="v-card"><summary className="cursor-pointer">{t("Previous attempts and feedback")}</summary>{submission.revision_history.map((attempt,index)=><div className="mt-4" key={index}><h3 className="font-medium">{t("Attempt")} {attempt.attempt}</h3><p className="mt-2 whitespace-pre-wrap">{attempt.text}</p><p className="mt-2 whitespace-pre-wrap">{t("Feedback")}: {attempt.feedback}</p><CriterionFeedback criteria={criteria} feedback={attempt.criterion_feedback}/></div>)}</details>}</div>;
}
