import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {Plus,Users} from 'lucide-react';
import {useWorkspace} from '@/hooks/useWorkspace';
import {organizationRoster,saveCohort} from '@/services/classroomService';
import {archiveResource} from '@/services/workspaceService';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';

export default function Cohorts(){
 const {ctx,data,revision,error:workspaceError}=useWorkspace();const [draft,setDraft]=useState(null);const [query,setQuery]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const {data:roster,isPending,error,refetch}=useQuery({queryKey:['workspace','organization-roster',ctx?.personId,ctx?.workspaceId,revision],enabled:!!ctx,queryFn:()=>organizationRoster(ctx),retry:false});
 if(workspaceError)return <div className="v-page" role="alert">{workspaceError}</div>;
 if(!data)return <div className="v-page" role="status">Opening organization…</div>;
 const rows=data.resources.filter(r=>r.kind==='cohort'&&r.title.toLowerCase().includes(query.toLowerCase()));
 const staleMembers=(draft?.members||[]).filter(email=>!roster?.members.some(member=>member.email===email));
 const staleClasses=(draft?.classIds||[]).filter(id=>!roster?.classes.some(classroom=>classroom.id===id));
 function toggle(key,value){setDraft(d=>({...d,[key]:d[key].includes(value)?d[key].filter(v=>v!==value):[...d[key],value]}));}
 async function save(){setBusy(true);try{await saveCohort(ctx,draft);setDraft(null);setNotice('Cohort saved. Membership does not grant access to personal learning.');}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 return <div className="v-page"><header className="flex flex-wrap justify-between gap-4"><div><h1 className="v-title">Cohorts</h1><p className="v-muted mt-2">Give a connected group a shared purpose, without merging their personal work.</p></div><button className="v-button primary" onClick={()=>{setDraft({title:'',body:'',members:[],classIds:[],status:'draft'});setNotice('');}}><Plus size={18}/>Create cohort</button></header>
 {isPending?<p role="status">Loading accepted members and linked classes…</p>:error?<p role="alert" className="v-notice v-error">{error.message}<button className="v-button ml-3" onClick={()=>refetch()}>Retry</button></p>:<p className="v-notice">{roster.members.length} accepted members · {roster.classes.length} explicitly linked classes. <Link className="underline" to="/dashboard/people">Manage people</Link><button className="ml-3 underline" onClick={()=>refetch()}>Refresh roster</button></p>}
 <label><span className="sr-only">Search cohorts</span><input className="v-field max-w-md" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cohorts"/></label>
 <section className="v-card">{rows.length?rows.map(r=><div className="v-list-row" key={r.id}><button className="min-w-0 flex-1 text-left" onClick={()=>{setDraft({...r,members:r.members||[],classIds:r.classIds||[]});setNotice('');}}><h2 className="text-base font-medium break-words">{r.title}</h2><p className="v-muted">{r.status} · {(r.members||[]).filter(email=>roster?.members.some(m=>m.email===email)).length} connected members · {(r.classIds||[]).filter(id=>roster?.classes.some(c=>c.id===id)).length} linked classes</p></button><button className="v-button" onClick={()=>{try{archiveResource(ctx,r.id);}catch(e){setNotice(e.message);}}}>{r.status==='archived'?'Restore':'Archive'}</button></div>):<div className="py-8"><Users className="mb-4 text-[#4285F4]"/><h2 className="text-lg font-medium">{query?'No matching cohorts':'Start with one learning group'}</h2><p className="v-muted mt-3">Connect people, choose a clear purpose, and link the classes that support it.</p></div>}</section>{notice&&<p role="status" className="v-notice">{notice}</p>}
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null);}}><DialogContent className="max-h-[85dvh] overflow-y-auto sm:max-w-2xl"><DialogTitle>{draft?.id?'Edit cohort':'Create cohort'}</DialogTitle><DialogDescription>Only accepted members and explicitly organization-linked classes are available. No private notes or conversations are included.</DialogDescription>{draft&&<><label className="text-sm">Name<input className="v-field mt-2" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="text-sm">Purpose and curriculum objectives<textarea className="v-field mt-2" rows={3} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><fieldset><legend className="mb-3 text-sm font-medium">Connected people</legend>{roster?.members.length?roster.members.map(m=><label key={m.id} className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={draft.members.includes(m.email)} onChange={()=>toggle('members',m.email)}/><span className="break-all">{m.email} · {m.role}</span></label>):<p className="v-muted">Invite people and wait for acceptance in People.</p>}{staleMembers.map(email=><label key={email} className="flex min-h-11 items-center gap-3 text-sm text-[#b3261e]"><input type="checkbox" checked onChange={()=>toggle('members',email)}/><span className="break-all">{email} · no longer connected — remove to save</span></label>)}</fieldset><fieldset><legend className="mb-3 text-sm font-medium">Linked classes</legend>{roster?.classes.length?roster.classes.map(c=><label key={c.id} className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={draft.classIds.includes(c.id)} onChange={()=>toggle('classIds',c.id)}/>{c.name}</label>):<p className="v-muted">An accepted teacher can link a class when creating it.</p>}{staleClasses.map(id=><label key={id} className="flex min-h-11 items-center gap-3 text-sm text-[#b3261e]"><input type="checkbox" checked onChange={()=>toggle('classIds',id)}/><span className="break-all">Previously linked class · no longer available — remove to save</span></label>)}</fieldset>{notice&&<p role="status" className="v-notice">{notice}</p>}<button className="v-button primary" disabled={busy||isPending||!!error||!draft.title.trim()} onClick={save}>{busy?'Saving…':'Save cohort'}</button></>}</DialogContent></Dialog></div>;
}
