import { lazy,Suspense,useEffect,useRef,useState } from 'react';
import { Link,useLocation,useSearchParams } from 'react-router-dom';
import { ArrowUp,BookOpen,History,Plus,Sparkles,Square,ArrowUpRight } from 'lucide-react';
import { useWorkspace } from '@/hooks/useWorkspace';
import { selectConversation,newConversation,sendMessage,startJourney,updateSession,updateConversation,removeConversation,roleActions,roleNames } from '@/services/workspaceService';
import { listJourneys } from '@/services/journeys';
import GuideActivity from '@/components/dashboard/GuideActivity';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
const WorkspaceTools=lazy(()=>import('./WorkspaceTools'));
const Cohorts=lazy(()=>import('./Cohorts'));
const Learners=lazy(()=>import('./Learners'));
const TeacherClasses=lazy(()=>import('./role/TeacherHome'));
const RoleWorkspace=lazy(()=>import('./RoleWorkspace'));
const ArtifactStudio=lazy(()=>import('./ArtifactStudio'));

export default function Guide(){
 const {ctx,data,person,error:loadError}=useWorkspace();const location=useLocation();const [params]=useSearchParams();const [selected,setSelected]=useState(()=>data?.activeConversationId||null);const [input,setInput]=useState(location.state?.initialQuestion|| (params.get('topic')?`Help me understand ${params.get('topic')}.`:''));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [history,setHistory]=useState(false);const [deleting,setDeleting]=useState(null);const [pane,setPane]=useState('conversation');const [focus,setFocus]=useState(false);const abort=useRef(null);const field=useRef(null);
 useEffect(()=>()=>abort.current?.abort(),[]);
 const [canvasPath,setCanvasPath]=useState(()=>data?.conversations.find(c=>c.id===data.activeConversationId)?.canvasPath||'');const queryOpened=useRef('');
 useEffect(()=>{const journeyId=params.get('journey');if(!journeyId||!ctx||!data)return;const key=ctx.workspaceId+location.key;if(queryOpened.current===key)return;queryOpened.current=key;try{const previous=data.sessions.find(s=>s.journeyId===journeyId);const c=previous?data.conversations.find(c=>c.id===previous.conversationId):newConversation(ctx);if(!c)return;setSelected(c.id);selectConversation(ctx,c.id);setCanvasPath('');const s=startJourney(ctx,c.id,journeyId);if(params.get('stage')==='practicing')updateSession(ctx,s.id,{stage:'practicing',position:0});setPane('activity');}catch(e){setError(e.message);}},[ctx?.workspaceId,data,location.key]);
 useEffect(()=>{setInput(location.state?.initialQuestion||(params.get('topic')?`Help me understand ${params.get('topic')}.`:data?.conversations.find(c=>c.id===selected)?.draft||''));},[location.key]);
 const conversation=data?.conversations.find(c=>c.id===selected);const session=data?.sessions.find(s=>s.id===conversation?.sessionId);
 function ensureConversation(){if(conversation)return conversation;const c=newConversation(ctx);setSelected(c.id);return c;}
 async function send(e){e?.preventDefault();if(!input.trim()||busy||!ctx)return;setError('');setBusy(true);const controller=new AbortController();abort.current=controller;try{const c=ensureConversation();updateConversation(ctx,c.id,{draft:input});await sendMessage({...ctx,signal:controller.signal},c.id,input);setInput('');}catch(e){if(e.name!=='AbortError')setError(e.message);}finally{setBusy(false);}}
 function openActivity(journeyId){try{const c=ensureConversation();startJourney(ctx,c.id,journeyId);setCanvasPath('');setPane('activity');setError('');}catch(e){setError(e.message);}}
 function openCanvas(path){try{const c=ensureConversation();updateConversation(ctx,c.id,{canvasPath:path});setCanvasPath(path);setPane('activity');setFocus(false);}catch(e){setError(e.message);}}
 function chooseConversation(c){abort.current?.abort();setSelected(c.id);selectConversation(ctx,c.id);setInput(c.draft);setCanvasPath(c.canvasPath||'');setHistory(false);setPane(c.sessionId||c.canvasPath?'activity':'conversation');setError('');}
 if(loadError)return <div role="alert" className="v-page"><h1 className="v-title">Your workspace needs attention</h1><p>{loadError}</p><button className="v-button" onClick={()=>window.location.reload()}>Retry</button></div>;
 if(!ctx||!data)return <div className="v-page" role="status">Preparing your workspace…</div>;
 const recent=data.conversations[0];const suggestions=ctx.role==='student'?listJourneys(ctx.locale):ctx.role==='professional'?[listJourneys(ctx.locale)[2]]:[];
 const hasActivity=Boolean(session||canvasPath);
 return <><div className="guide-mobile-tabs" role="tablist" aria-label="Workspace view"><button className="v-button" role="tab" aria-selected={pane==='conversation'} onClick={()=>setPane('conversation')}>Conversation</button><button className="v-button" role="tab" aria-selected={pane==='activity'} disabled={!hasActivity} onClick={()=>setPane('activity')}>Activity{hasActivity?' · Saved':''}</button></div><div className={`guide-shell ${hasActivity?'has-activity':''} ${focus?'focus-activity':''}`}>
  <section aria-label="Guide conversation" className={`guide-conversation ${pane!=='conversation'&&hasActivity?'hidden-pane':''}`}>
   <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 text-xs text-[#5f6368]">{roleNames[ctx.role]} workspace</p><h1 className="flex items-center gap-2 text-lg font-medium"><Sparkles className="text-blue-700" size={20}/>Visionary Guide</h1></div><div className="flex gap-2"><button className="v-button !px-3" aria-label="Conversation history" onClick={()=>setHistory(true)}><History size={18}/></button><button className="v-button !px-3" aria-label="New conversation" onClick={()=>{abort.current?.abort();selectConversation(ctx,null);setSelected(null);setCanvasPath('');setInput('');setError('');setPane('conversation');}}><Plus size={18}/></button></div></header>
   <div className="guide-messages" aria-live="polite" aria-busy={busy}>
    {!conversation?.messages.length?<div className={`flex flex-1 flex-col justify-center ${session?'py-5':'py-8 sm:py-12'}`}><p className="mb-4 text-sm text-[#5f6368]">Hello, {person?.name?.split(' ')[0]||'there'}.</p><h2 className="max-w-xl text-[32px] font-medium leading-[1.25] tracking-tight">{ctx.role==='teacher'?'What will you help someone understand?':ctx.role==='parent'?'Let’s find a helpful next step.':ctx.role==='organization'?'What needs your attention today?':'What would you like to understand or build?'}</h2><p className="v-muted mt-4 max-w-lg">{ctx.role==='organization'?'Plan, review, and coordinate in one place. You approve every change.':ctx.role==='parent'?'Understand shared progress, with clear boundaries and practical support.':'Start with an idea. Explore it together, put it into practice, and make something of your own.'}</p>
     <div className="mt-7 flex flex-wrap gap-2">{suggestions.map(j=><button className="v-button" key={j.id} onClick={()=>openActivity(j.id)}><BookOpen size={16}/><span lang={ctx.locale}>{j.title}</span></button>)}{ctx.role!=='student'&&roleActions[ctx.role].slice(0,3-suggestions.length).map(a=><button className="v-button" key={a.path} onClick={()=>{setInput(a.label);field.current?.focus();}}>{a.label}<ArrowUpRight size={16}/></button>)}</div>
     {!selected&&recent&&<button className="mt-8 flex items-center gap-3 rounded-xl border border-[#dadce0] p-4 text-left text-sm" onClick={()=>chooseConversation(recent)}><History size={18}/><span className="min-w-0"><span className="block text-xs text-[#5f6368]">Continue where you left off</span><span className="mt-1 block truncate">{recent.title}</span></span></button>}
    </div>:conversation.messages.map(message=><div key={message.id} className={`guide-message ${message.role==='user'?'user':''}`}>{message.role==='guide'&&<p className="mb-2 flex items-center gap-2 text-xs font-medium text-blue-700"><Sparkles size={14}/>Visionary Guide · Demo response</p>}{message.blocks.map((block,i)=>block.type==='text'?<p key={i} className="whitespace-pre-wrap">{block.text}</p>:block.type==='activity'?<button key={i} className="v-button mr-2 mt-3" onClick={()=>openActivity(block.journeyId)}><BookOpen size={16}/>{block.label}</button>:<button className="v-button mt-3" key={i} onClick={()=>openCanvas(block.path)}>{block.label}<ArrowUpRight size={16}/></button>)}</div>)}
   </div>
   {busy&&<p role="status" className="v-muted">Preparing a demo response…</p>}{error&&<div role="alert" className="v-notice v-error">{error}<Link className="ml-2 underline" to="/dashboard/subscription">Plans & usage</Link></div>}
   <form onSubmit={send} className="guide-composer"><label className="sr-only" htmlFor="guide-input">Message Visionary Guide</label><textarea id="guide-input" ref={field} value={input} maxLength={6000} onChange={e=>setInput(e.target.value)} onBlur={()=>{if(conversation)try{updateConversation(ctx,conversation.id,{draft:input});}catch(e){setError(e.message);}}} placeholder="Ask in your own words…"/><div className="mt-3 flex items-center justify-between gap-3"><span className="text-xs text-[#5f6368]">{ctx.locale==='hi'?'हिन्दी':ctx.locale==='bn'?'বাংলা':'English'} · Private to this workspace</span>{busy?<button type="button" className="v-button" onClick={()=>abort.current?.abort()}><Square size={16}/>Stop</button>:<button className="v-button primary !px-3" disabled={!input.trim()} aria-label="Send message"><ArrowUp size={20}/></button>}</div></form>
   <p className="text-center text-[11px] leading-5 text-[#5f6368]">Curated demo responses. No live model, cloud sync, or real student records. <Link to="/dashboard/support" className="underline">About this preview</Link></p>
  </section>
  {hasActivity&&<aside aria-label="Activity canvas" className={`guide-canvas ${pane!=='activity'?'hidden-pane':''}`}>{canvasPath?<><div className="flex flex-wrap justify-between gap-2"><button className="v-button" onClick={()=>setFocus(v=>!v)}>{focus?'Show conversation':'Focus activity'}</button><Link className="v-button" to={canvasPath}>Open full page<ArrowUpRight size={16}/></Link></div><Suspense fallback={<p role="status">Opening activity…</p>}><ContextActivity path={canvasPath}/></Suspense></>:<GuideActivity key={session.id} ctx={ctx} session={session} onFocus={()=>setFocus(v=>!v)} onAsk={()=>{setPane('conversation');setFocus(false);setInput(ctx.locale==='en'?`Help me understand ${getJourneyTitle(session.journeyId)}.`:'');field.current?.focus();}}/>}</aside>}
 </div><Dialog open={history} onOpenChange={setHistory}><DialogContent className="max-h-[80dvh] overflow-y-auto"><DialogTitle>Your conversations</DialogTitle><DialogDescription>Only conversations in this workspace appear here.</DialogDescription>{data.conversations.length?data.conversations.map(c=><div className="v-list-row" key={c.id}><button className="min-w-0 flex-1 text-left text-sm" onClick={()=>chooseConversation(c)}>{c.title}</button><button className="text-xs text-red-700 underline" onClick={()=>setDeleting(c.id)}>Delete</button></div>):<p className="v-muted">Your first conversation will appear here.</p>}</DialogContent></Dialog><Dialog open={!!deleting} onOpenChange={()=>setDeleting(null)}><DialogContent><DialogTitle>Delete this conversation?</DialogTitle><DialogDescription>This removes its local messages and linked lesson session. Projects you saved in Build remain available.</DialogDescription><button className="v-button" onClick={()=>setDeleting(null)}>Keep conversation</button><button className="v-button" onClick={()=>{removeConversation(ctx,deleting);if(selected===deleting)setSelected(null);setDeleting(null);}}>Delete conversation</button></DialogContent></Dialog></>;
}
function getJourneyTitle(id){return listJourneys().find(j=>j.id===id)?.title||'this idea';}
function ContextActivity({path}){const area=path.split('/').pop();if(area==='cohorts')return <Cohorts/>;if(area==='learners')return <Learners/>;if(area==='classes')return <TeacherClasses/>;if(area==='build')return <ArtifactStudio/>;if(['people','analytics','learners'].includes(area))return <RoleWorkspace area={area==='learners'?'insights':area}/>;return <WorkspaceTools area={area==='child'?'privacy':area}/>;}
