import { lazy,Suspense,useEffect,useRef,useState } from 'react';
import { Link,useLocation,useSearchParams } from 'react-router-dom';
import { ArrowUp,BookOpen,History,Plus,Sparkles,Square,ArrowUpRight } from 'lucide-react';
import { useWorkspace } from '@/hooks/useWorkspace';
import { selectConversation,newConversation,sendMessage,startJourney,updateConversation,removeConversation,roleActions,roleNames } from '@/services/workspaceService';
import { listJourneys } from '@/services/journeys';
import { openGuideEntry,saveAskContext,suggestedJourneys,defaultAskContext } from '@/services/guideEntryService';
import GuideEntry from '@/components/dashboard/GuideEntry';
import GuideActivity from '@/components/dashboard/GuideActivity';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
const WorkspaceTools=lazy(()=>import('./WorkspaceTools'));
const Children=lazy(()=>import('./Children'));
const Cohorts=lazy(()=>import('./Cohorts'));
const Learners=lazy(()=>import('./Learners'));
const TeacherClasses=lazy(()=>import('./role/TeacherHome'));
const RoleWorkspace=lazy(()=>import('./RoleWorkspace'));
const ArtifactStudio=lazy(()=>import('./ArtifactStudio'));

export default function Guide(){
 const {ctx,data,error:loadError}=useWorkspace();const location=useLocation();const [params]=useSearchParams();const [selected,setSelected]=useState(()=>data?.activeConversationId||null);const [input,setInput]=useState(location.state?.initialQuestion|| (params.get('topic')?`Help me understand ${params.get('topic')}.`:''));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [history,setHistory]=useState(false);const [deleting,setDeleting]=useState(null);const [pane,setPane]=useState('conversation');const [focus,setFocus]=useState(false);const abort=useRef(null);const field=useRef(null);
 useEffect(()=>()=>abort.current?.abort(),[]);
 const historyTrigger=useRef(null);const historyTitle=useRef(null);const deleteTrigger=useRef(null);const conversationTab=useRef(null);const activityTab=useRef(null);
 function switchTab(event){if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?'conversation':event.key==='End'?(session||canvasPath?'activity':'conversation'):pane==='conversation'&&(session||canvasPath)?'activity':'conversation';setPane(next);(next==='activity'?activityTab:conversationTab).current?.focus();}
 const [canvasPath,setCanvasPath]=useState(()=>data?.conversations.find(c=>c.id===data.activeConversationId)?.canvasPath||'');const queryOpened=useRef('');
 useEffect(()=>{const journeyId=params.get('journey');const sessionId=params.get('session');if((!journeyId&&!sessionId)||!ctx||!data)return;const key=ctx.workspaceId+location.key;if(queryOpened.current===key)return;queryOpened.current=key;try{const {conversation:c}=openGuideEntry(ctx,{journeyId,sessionId,practice:params.get('stage')==='practicing'});setSelected(c.id);setCanvasPath('');setPane('activity');}catch(e){setSelected(null);setCanvasPath('');setError(e.message);}},[ctx?.workspaceId,data,location.key]);
 useEffect(()=>{setInput(location.state?.initialQuestion||(params.get('topic')?`Help me understand ${params.get('topic')}.`:data?.conversations.find(c=>c.id===selected)?.draft||''));},[location.key]);
 const conversation=data?.conversations.find(c=>c.id===selected);const session=data?.sessions.find(s=>s.id===conversation?.sessionId);
 useEffect(()=>{if(pane==='activity'&&window.matchMedia('(max-width: 1199px)').matches&&document.activeElement?.closest('#guide-conversation-panel'))activityTab.current?.focus();},[pane]);
 function ensureConversation(){if(conversation)return conversation;const c=newConversation(ctx);setSelected(c.id);return c;}
 async function send(e){e?.preventDefault();if(!input.trim()||busy||!ctx)return;setError('');setBusy(true);const controller=new AbortController();abort.current=controller;try{const c=ensureConversation();updateConversation(ctx,c.id,{draft:input});await sendMessage({...ctx,locale:session?.locale||ctx.locale,signal:controller.signal},c.id,input);setInput('');}catch(e){if(e.name!=='AbortError')setError(e.message);}finally{setBusy(false);}}
 function openActivity(journeyId){try{const c=ensureConversation();startJourney(ctx,c.id,journeyId);setCanvasPath('');setPane('activity');setError('');}catch(e){setError(e.message);}}
 function openCanvas(path){try{const c=ensureConversation();updateConversation(ctx,c.id,{canvasPath:path});setCanvasPath(path);setPane('activity');setFocus(false);}catch(e){setError(e.message);}}
 function chooseConversation(c){abort.current?.abort();setSelected(c.id);selectConversation(ctx,c.id);setInput(c.draft);setCanvasPath(c.canvasPath||'');setHistory(false);setPane(c.sessionId||c.canvasPath?'activity':'conversation');setError('');}
 function askAboutActivity(){const text=session.locale==='hi'?'इस गतिविधि को समझने में मेरी मदद करें।':session.locale==='bn'?'এই কার্যকলাপটি বুঝতে আমাকে সাহায্য করুন।':`Help me understand ${getJourneyTitle(session.journeyId)}.`;setPane('conversation');setFocus(false);setInput(text);try{updateConversation(ctx,conversation.id,{draft:text});}catch(e){setError(e.message);}requestAnimationFrame(()=>field.current?.focus());}
 if(loadError)return <div role="alert" className="v-page"><h1 className="v-title">Your workspace needs attention</h1><p>{loadError}</p><button className="v-button" onClick={()=>window.location.reload()}>Retry</button></div>;
 if(!ctx||!data)return <div className="v-page" role="status">Preparing your workspace…</div>;
 const recent=data.conversations[0];const suggestions=suggestedJourneys(ctx);
 const hasActivity=Boolean(session||canvasPath);
 return <><div className="guide-mobile-tabs" role="tablist" aria-label="Workspace view" onKeyDown={switchTab}><button ref={conversationTab} id="guide-conversation-tab" aria-controls="guide-conversation-panel" tabIndex={pane==='conversation'||!hasActivity?0:-1} className="v-button" role="tab" aria-selected={pane==='conversation'||!hasActivity} onClick={()=>setPane('conversation')}>Conversation</button><button ref={activityTab} id="guide-activity-tab" aria-controls="guide-activity-panel" tabIndex={pane==='activity'&&hasActivity?0:-1} className="v-button" role="tab" aria-selected={pane==='activity'&&hasActivity} disabled={!hasActivity} onClick={()=>setPane('activity')}>Activity{hasActivity?' · Saved':''}</button></div><div className={`guide-shell ${hasActivity?'has-activity':''} ${focus?'focus-activity':''}`}>
  <section id="guide-conversation-panel" role="tabpanel" aria-label="Guide conversation" className={`guide-conversation ${pane!=='conversation'&&hasActivity?'hidden-pane':''}`}>
   <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 text-xs text-[#5f6368]">{roleNames[ctx.role]} workspace</p><h1 className="flex items-center gap-2 text-lg font-medium"><Sparkles aria-hidden="true" className="text-blue-700" size={20}/>Visionary Guide</h1></div><div className="flex gap-2"><button ref={historyTrigger} className="v-button !px-3" aria-label="Conversation history" onClick={()=>setHistory(true)}><History aria-hidden="true" size={18}/></button><button className="v-button !px-3" aria-label="New conversation" onClick={()=>{abort.current?.abort();selectConversation(ctx,null);setSelected(null);setCanvasPath('');setInput('');setError('');setPane('conversation');}}><Plus aria-hidden="true" size={18}/></button></div></header>
   <div className="guide-messages" aria-busy={busy}>
    {!conversation?.messages.length?<div className={`flex flex-1 flex-col justify-center ${session?'py-5':'py-8'}`}><GuideEntry role={ctx.role} value={conversation?.ask||defaultAskContext} onChange={value=>{try{saveAskContext(ctx,ensureConversation().id,value);}catch(e){setError(e.message);}}}/>
     <div className="mt-7 flex flex-wrap gap-2">{suggestions.map(j=><button className="v-button" key={j.id} onClick={()=>openActivity(j.id)}><BookOpen size={16}/><span lang={ctx.locale}>{j.title}</span></button>)}{ctx.role!=='student'&&roleActions[ctx.role].slice(0,3-suggestions.length).map(a=><Link className="v-button" key={a.path} to={a.path}>{a.label}<ArrowUpRight size={16}/></Link>)}</div>
     {!selected&&recent&&<button className="mt-8 flex items-center gap-3 rounded-xl border border-[#dadce0] p-4 text-left text-sm" onClick={()=>chooseConversation(recent)}><History size={18}/><span className="min-w-0"><span className="block text-xs text-[#5f6368]">Continue where you left off</span><span className="mt-1 block truncate">{recent.title}</span></span></button>}
    </div>:conversation.messages.map(message=><div key={message.id} className={`guide-message ${message.role==='user'?'user':''}`}>{message.role==='guide'&&<p className="mb-2 flex items-center gap-2 text-xs font-medium text-blue-700"><Sparkles size={14}/>Visionary Guide · Demo response</p>}{message.blocks.map((block,i)=>block.type==='text'?<p key={i} className="whitespace-pre-wrap">{block.text}</p>:block.type==='activity'?<button key={i} className="v-button mr-2 mt-3" onClick={()=>openActivity(block.journeyId)}><BookOpen size={16}/>{block.label}</button>:<button className="v-button mt-3" key={i} onClick={()=>openCanvas(block.path)}>{block.label}<ArrowUpRight size={16}/></button>)}</div>)}
   </div>
   {!!conversation?.messages.length && <GuideEntry compact role={ctx.role} value={conversation.ask||defaultAskContext} onChange={value=>{try{saveAskContext(ctx,conversation.id,value);}catch(e){setError(e.message);}}}/>}
   <p role="status" className={busy?'v-muted':'sr-only'}>{busy?'Preparing a demo response…':conversation?.messages.at(-1)?.role==='guide'?'Demo response ready. Review it above.':''}</p>{error&&<div role="alert" className="v-notice v-error">{error}<p>Your saved work is kept. You can retry your question or return Home.</p><Link className="underline" to="/dashboard/home">Return Home</Link></div>}
   <form onSubmit={send} className="guide-composer"><label className="guide-entry-label" htmlFor="guide-input">Message Visionary Guide</label><textarea id="guide-input" lang={session?.locale||ctx.locale} aria-describedby="guide-input-help" ref={field} value={input} maxLength={6000} onChange={e=>{setInput(e.target.value);try{const c=ensureConversation();updateConversation(ctx,c.id,{draft:e.target.value});}catch(error){setError(error.message);}}} onBlur={()=>{if(conversation)try{updateConversation(ctx,conversation.id,{draft:input});}catch(e){setError(e.message);}}} placeholder="Ask in your own words…"/><div className="mt-3 flex items-center justify-between gap-3"><span id="guide-input-help" className="text-xs text-[#5f6368]"><span lang={session?.locale||ctx.locale}>{(session?.locale||ctx.locale)==='hi'?'हिन्दी':(session?.locale||ctx.locale)==='bn'?'বাংলা':'English'}</span> · Private to this workspace</span>{busy?<button type="button" className="v-button" onClick={()=>abort.current?.abort()}><Square aria-hidden="true" size={16}/>Stop</button>:<button className="v-button primary !px-3" disabled={!input.trim()} aria-label="Send message"><ArrowUp aria-hidden="true" size={20}/></button>}</div></form>
   <p className="text-center text-[11px] leading-5 text-[#5f6368]">Curated demo responses. No live model, cloud sync, or real student records. <Link to="/dashboard/support" className="underline">About this preview</Link></p>
  </section>
  {hasActivity&&<aside id="guide-activity-panel" role="tabpanel" aria-label="Activity canvas" className={`guide-canvas ${pane!=='activity'?'hidden-pane':''}`}><h1 className={focus?'sr-only':'sr-only min-[1200px]:hidden'}>Visionary Guide activity</h1>{canvasPath?<><div className="flex flex-wrap justify-between gap-2"><button className="v-button" onClick={()=>setFocus(v=>!v)}>{focus?'Show conversation':'Focus activity'}</button><Link className="v-button" to={canvasPath}>Open full page<ArrowUpRight size={16}/></Link></div><Suspense fallback={<p role="status">Opening activity…</p>}><ContextActivity path={canvasPath}/></Suspense></>:<GuideActivity key={session.id} ctx={ctx} session={session} onFocus={()=>setFocus(v=>!v)} onAsk={askAboutActivity}/>}</aside>}
 </div><Dialog open={history} onOpenChange={setHistory}><DialogContent onCloseAutoFocus={event=>{event.preventDefault();const target=pane==='activity'&&hasActivity&&window.matchMedia('(max-width: 1199px)').matches?activityTab.current:historyTrigger.current;target?.focus();}} className="max-h-[80dvh] overflow-y-auto"><DialogTitle ref={historyTitle} tabIndex={-1}>Your conversations</DialogTitle><DialogDescription>Only conversations in this workspace appear here.</DialogDescription>{data.conversations.length?data.conversations.map(c=><div className="v-list-row" key={c.id}><button className="v-button min-w-0 flex-1 text-left text-sm" onClick={()=>chooseConversation(c)}>{c.title}</button><button className="v-button text-xs text-red-700 underline" aria-label={`Delete conversation: ${c.title}`} onClick={event=>{deleteTrigger.current=event.currentTarget;setDeleting(c.id);}}>Delete</button></div>):<p className="v-muted">Your first conversation will appear here.</p>}</DialogContent></Dialog><Dialog open={!!deleting} onOpenChange={()=>setDeleting(null)}><DialogContent onCloseAutoFocus={event=>{event.preventDefault();(deleteTrigger.current?.isConnected?deleteTrigger.current:historyTitle.current)?.focus();}}><DialogTitle>Delete this conversation?</DialogTitle>{error&&<p role="alert" className="v-notice v-error">{error}</p>}<DialogDescription>This removes its local messages and linked lesson session. Projects you saved in Build remain available.</DialogDescription><button className="v-button" onClick={()=>setDeleting(null)}>Keep conversation</button><button className="v-button" onClick={()=>{try{removeConversation(ctx,deleting);if(selected===deleting){setSelected(null);setCanvasPath('');setInput('');}setDeleting(null);setError('');}catch(e){setError(e.message);}}}>Delete conversation</button></DialogContent></Dialog></>;
}
function getJourneyTitle(id){return listJourneys().find(j=>j.id===id)?.title||'this idea';}
function ContextActivity({path}){const area=path.split('/').pop();if(area==='child')return <Children/>;if(area==='cohorts')return <Cohorts/>;if(area==='learners')return <Learners/>;if(area==='classes')return <TeacherClasses/>;if(area==='build')return <ArtifactStudio/>;if(['people','analytics','learners'].includes(area))return <RoleWorkspace area={area==='learners'?'insights':area}/>;return <WorkspaceTools area={area==='child'?'privacy':area}/>;}
