import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2 } from 'lucide-react';
import { useAuth } from '@/lib/AuthContext';
import { useWorkspace } from '@/hooks/useWorkspace';
import { getContentRepository, SAMPLE_SELECTION, PROFESSIONAL_SAMPLE_SELECTION } from '@/services/contentRepository';
import { getStudentState, getStudentClassLearningContext } from '@/services/mentorStateService';
import { getLearningWorkspace, getLearningUnit, selectLearningSyllabus, startLearningUnit, requestUnitTeaching, beginComprehension, answerLearningQuestion, nextLearningQuestion, createLearningProject, flushLearningOutcome, updateLearningLanguage } from '@/services/learningPipelineService';

const languageNames = { en: 'English', hi: 'Hindi', bn: 'Bengali' };

export default function LearningWorkspace({practice=false,unitIdOverride}) {
 const {ctx,error:workspaceError}=useWorkspace();const {user}=useAuth();const [params,setParams]=useSearchParams();
 const [selection,setSelection]=useState(()=>ctx?getLearningWorkspace(ctx).selection||{board:user?.board||'',classLevel:user?.grade_level||'',subject:Array.isArray(user?.subjects)?user.subjects[0]||'':''}:{board:'',classLevel:'',subject:''});
 const [syllabus,setSyllabus]=useState(null);const [chapter,setChapter]=useState(null);const [topics,setTopics]=useState([]);const [unit,setUnit]=useState(null);const [concept,setConcept]=useState(null);
 const [classContext,setClassContext]=useState(null);
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [answer,setAnswer]=useState('');const [rename,setRename]=useState('');
 const [renderedWorkspaceId,setRenderedWorkspaceId]=useState(ctx?.workspaceId||'');
 const unitId=unitIdOverride||params.get('unit');
 const chapterId=params.get('chapter');const fromClassId=params.get('fromClass');
 useEffect(()=>{let live=true;if(!ctx)return;setError('');setBusy(true);setUnit(null);setConcept(null);setSyllabus(null);setChapter(null);setTopics([]);setClassContext(null);(async()=>{if(unitId){const saved=flushLearningOutcome(ctx,unitId);const content=await getContentRepository({...ctx,locale:saved.locale}).getConcept(saved.conceptId);if(!content)throw Error('This concept is unavailable. Your saved activity remains intact.');if(live){setUnit(saved);setConcept(content);setAnswer(saved.answer?String(saved.answer.index):'');}}else{const profile={board:user?.board||'',classLevel:user?.grade_level||'',subject:Array.isArray(user?.subjects)?user.subjects[0]||'':''};const connected=fromClassId?getStudentClassLearningContext(ctx,fromClassId):null;const saved=connected?{...profile,subject:connected.subject}:getLearningWorkspace(ctx).selection||profile;if(saved.subject){const outline=await selectLearningSyllabus(ctx,saved);let selected=null;let rows=[];if(chapterId){selected=outline.chapters.find(item=>item.id===chapterId);if(!selected)throw Error('This chapter is not in your current learning outline.');const repo=getContentRepository(ctx);const chaptersTopics=await repo.getTopics(selected.id);rows=await Promise.all(chaptersTopics.map(async topic=>({...topic,concepts:await repo.getConcepts(topic.id)})));}if(live){setSelection(saved);setSyllabus(outline);setClassContext(connected);setChapter(selected);setTopics(rows);setRename(selected?.status==='provisional'?selected.title:'');}}else if(live){setSelection(saved);setClassContext(connected);}}})().catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live){setBusy(false);setRenderedWorkspaceId(ctx.workspaceId);}});return()=>{live=false;};},[ctx?.workspaceId,ctx?.locale,unitId,chapterId,fromClassId]);
 async function run(work){setBusy(true);setError('');try{await work();}catch(e){setError(e.message);}finally{setBusy(false);}}
 function openOutline(value){run(async()=>{const result=await selectLearningSyllabus(ctx,value);setSelection(value);setSyllabus(result);setChapter(null);setTopics([]);setClassContext(null);setParams({});});}
 function openChapter(value){setParams({...(fromClassId?{fromClass:fromClassId}:{}),chapter:value.id});}
 async function openConcept(id){const activity=await startLearningUnit(ctx,id,fromClassId||undefined);setParams({...(fromClassId?{fromClass:fromClassId}:{}),...(chapter?{chapter:chapter.id}:{}),unit:activity.id});}
 async function changeUnit(work){const next=await work();setUnit(next);setAnswer(next.answer?String(next.answer.index):'');}
 if(workspaceError||!ctx)return <div className="v-page" role={workspaceError?'alert':'status'}>{workspaceError||'Opening your learning workspace…'}</div>;
 if(renderedWorkspaceId!==ctx.workspaceId)return <div className="v-page" role="status" aria-busy="true">Opening this workspace…</div>;
 if(unitId&&unit?.id!==unitId&&busy)return <div className="v-page" role="status" aria-busy="true">Restoring your saved learning activity…</div>;
 if(!unitId&&unit)return <div className="v-page" role="status" aria-busy="true">Opening your learning outline…</div>;
 const professional=ctx.role==='professional';const state=getStudentState(ctx);const evidence=unit?state.concepts.find(c=>c.conceptId===unit.conceptId):null;
 const outlineQuery=new URLSearchParams({...(fromClassId?{fromClass:fromClassId}:{}),...(chapterId?{chapter:chapterId}:{})}).toString();
 const outlineUrl=`/dashboard/learn${outlineQuery?`?${outlineQuery}`:''}`;
 const saved=getLearningWorkspace(ctx).units;
 const chapterConcepts=topics.flatMap(topic=>topic.concepts);
 const startedConcepts=chapterConcepts.filter(item=>saved.some(activity=>activity.conceptId===item.id)).length;
 const nextConcept=chapterConcepts.find(item=>saved.some(activity=>activity.conceptId===item.id&&activity.stage!=='completed'))||chapterConcepts.find(item=>!saved.some(activity=>activity.conceptId===item.id))||chapterConcepts[0];
 const status=<>{busy&&<p role="status" className="v-muted">Saving your place…</p>}{error&&<div role="alert" className="v-notice v-error">{error} Your saved work is kept. {!unitId&&(chapterId||fromClassId)&&<button className="v-button ml-3" onClick={()=>setParams({})}>Open my outline</button>}</div>}</>;
 if(unit&&concept)return <div className="v-page">
  <header><Link className="v-button" to={outlineUrl}><ArrowLeft size={16}/>Learning outline</Link><p className="v-home-eyebrow mt-5">{concept.status==='sample'?'Authored sample · Not official curriculum':concept.status==='provisional'?'Provisional learning outline':concept.provenance?`Sourced curriculum · ${concept.provenance.provider} · version ${concept.provenance.version}`:'Saved curriculum · source details unavailable'}</p><h1 className="v-title mt-2" lang={concept.locale||undefined}>{concept.title}</h1><p className="v-muted mt-3">Your place is saved locally. Understanding is checked before guided practice and building.</p><label className="mt-4 block max-w-xs text-sm">Teaching language<select className="v-field mt-2" value={unit.locale} disabled={busy} onChange={e=>run(async()=>{const next=await updateLearningLanguage(ctx,unit.id,e.target.value);const translated=await getContentRepository({...ctx,locale:next.locale}).getConcept(next.conceptId);setUnit(next);setConcept(translated);})}><option value="en">English</option><option value="hi">हिन्दी</option><option value="bn">বাংলা</option></select></label>{concept.languageUnavailable&&<p className="v-notice mt-4" role="status">This concept’s saved teaching content is not loaded in {languageNames[unit.locale]}. {concept.locale?`The outline text is in ${languageNames[concept.locale]}. `:''}Your place and evidence remain saved. You can ask in {languageNames[unit.locale]}; a teaching response requires the connected model.</p>}</header>
  {status}
  <nav className="flex flex-wrap gap-2" aria-label="Learning unit stages">{[['explain','Understand'],['check','Check'],['practice','Practice'],['build','Build']].map(([id,label])=><span className="v-evidence" key={id} aria-current={unit.stage===id?'step':undefined}>{unit.stage===id?'• ':''}{label}</span>)}</nav>
  {unit.response&&<p role="status" className={`v-notice ${unit.response.status==='blocked'?'v-error':''}`} lang={unit.response.status==='not_connected'?'en':unit.locale}>{unit.response.status==='ready'?'Teaching service response received.':unit.response.text}</p>}
   {unit.stage==='explain'&&<section className="v-card"><h2 className="text-lg font-medium">Understand one idea</h2>{unit.explanation?<><p className="mt-4 whitespace-pre-wrap leading-8" lang={unit.response?.status==='ready'?unit.locale:concept.locale||unit.locale}>{unit.explanation}</p><p className="v-muted mt-3">{unit.response?.status==='ready'?'Source: connected teaching adapter.':concept.status==='sample'?'Source: explicitly authored sample content, not a generated model answer.':concept.provenance?`Source: ${concept.provenance.provider} · version ${concept.provenance.version}.`:'Source details are unavailable for this saved content.'}</p><button className="v-button primary mt-5" disabled={busy||unit.response?.status==='blocked'} onClick={()=>run(()=>changeUnit(()=>beginComprehension(ctx,unit.id)))}>Check my understanding<ArrowRight size={16}/></button></>:<><p className="v-muted mt-3">Request an explanation in your selected teaching language. If the service is disconnected, available authored sample content can still be used.</p><button className="v-button primary mt-5" disabled={busy} onClick={()=>run(()=>changeUnit(()=>requestUnitTeaching(ctx,unit.id,'explanation')))}>Start this learning unit</button></>}
   {concept.representations.length>0&&<details className="mt-5"><summary>Visual and accessible alternatives</summary>{concept.representations.map(r=><div className="mt-4" key={r.id}><p className="v-muted">{r.alternative}</p>{r.kind==='cube'&&<Link className="v-button mt-3" to="/dashboard/explore">Open existing cube lab</Link>}{!['text','cube'].includes(r.kind)&&<p className="v-muted mt-2">{r.kind} renderer: not connected. The text alternative remains available.</p>}</div>)}</details>}
  </section>}
  {['check','practice'].includes(unit.stage)&&<section className="v-card"><h2 className="text-lg font-medium">{unit.stage==='check'?'Check understanding':'Practice one step at a time'}</h2><p className="v-muted mt-2">Difficulty {unit.difficulty} / 5 · {evidence?`${evidence.correct}/${evidence.total} recorded correct answers`:'No assessment evidence yet'}</p>
   {unit.question&&unit.response?.status!=='blocked'?<><fieldset className="mt-5" disabled={busy||!!unit.answer}><legend className="mb-4 text-base leading-7" lang={unit.response?.status==='ready'?unit.locale:concept.locale||unit.locale}>{unit.question.prompt}</legend>{unit.question.options.map((option,index)=><label className="v-list-row justify-start gap-3" key={index}><input type="radio" name="concept-answer" value={index} checked={answer===String(index)} onChange={e=>setAnswer(e.target.value)}/><span lang={unit.response?.status==='ready'?unit.locale:concept.locale||unit.locale}>{option}</span></label>)}</fieldset>{!unit.answer?<button className="v-button primary mt-5" disabled={busy||answer===''} onClick={()=>run(()=>changeUnit(()=>answerLearningQuestion(ctx,unit.id,Number(answer))))}>Check answer</button>:<div className="mt-5" role="status"><p>{unit.answer.correct?'Correct for this recorded check.':'Not yet. Review the idea and try a smaller step.'}</p><p className="v-muted mt-2">Accuracy is evidence, not a claim of overall mastery. {unit.question.source==='authored-sample'?'This check comes from the authored sample.':''}</p><div className="mt-4 flex flex-wrap gap-3"><button className="v-button" disabled={busy} onClick={()=>run(()=>changeUnit(()=>nextLearningQuestion(ctx,unit.id,unit.checkPassed)))}>{unit.checkPassed?'Continue practice':'Retry understanding check'}</button>{unit.practicePassed&&<button className="v-button primary" disabled={busy} onClick={()=>run(async()=>{await createLearningProject(ctx,unit.id);setUnit(getLearningUnit(ctx,unit.id));})}>Apply this in Build</button>}</div></div>}</>:<div className="mt-5"><p className="v-muted">No verifiable question is available yet. Your progress has not been advanced or scored.</p><button className="v-button mt-4" disabled={busy} onClick={()=>run(()=>changeUnit(()=>requestUnitTeaching(ctx,unit.id,'practice')))}>Retry teaching connection</button></div>}
  </section>}
  {['build','completed'].includes(unit.stage)&&<section className="v-card"><CheckCircle2 aria-hidden="true"/><h2 className="mt-3 text-lg font-medium">{unit.stage==='completed'?'Your application is recorded':'Put the idea to work'}</h2><p className="v-muted mt-3">{concept.project?.brief||'Define an outcome, create an artifact, and reflect on the evidence.'}</p><Link className="v-button primary mt-5" to={`/dashboard/build?artifact=${encodeURIComponent(unit.artifactId||'')}`}>Open your project</Link><button className="v-button ml-3 mt-5" disabled={busy} onClick={()=>run(()=>changeUnit(()=>requestUnitTeaching(ctx,unit.id,'project')))}>Request project guidance</button></section>}
  <div className="flex flex-wrap gap-3"><Link className="v-button" to={`/dashboard/ask?learning=${encodeURIComponent(unit.id)}`}>Ask a doubt · keep my place</Link><Link className="v-button" to="/dashboard/home">Save and return Home</Link></div>
 </div>;
 return <div className="v-page"><header><h1 className="v-title">{practice?'Your next practice':'Your learning outline'}</h1><p className="v-muted mt-2">{practice?'Revisit what you have already checked. Your results and next step stay connected to Learn.':professional?'Connect a skill goal to concepts, practice and portfolio work.':'Subjects become chapters, concepts, checks and projects—with your place kept at every step.'}</p></header>{status}
  {classContext&&<div className="v-notice flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">Learning alongside {classContext.name}</p><p className="v-muted mt-1 hidden sm:block">This outline uses your class subject. Assignments and teacher feedback remain in Classes.</p></div><Link className="v-button" to={`/dashboard/classes?class=${encodeURIComponent(classContext.id)}`}>Classwork</Link></div>}
  {practice&&<section className="v-card"><h2 className="text-lg font-medium">Ready to revisit</h2>{saved.filter(u=>u.checkPassed).length?saved.filter(u=>u.checkPassed).map(u=><div className="v-list-row" key={u.id}><span>{u.title}</span><button className="v-button" disabled={busy} onClick={()=>run(async()=>{await nextLearningQuestion(ctx,u.id,true);setParams({unit:u.id});})}>Practice</button></div>):<><p className="v-muted mt-3">Finish a comprehension check in Learn first. No weakness is inferred from an empty history.</p><Link className="v-button primary mt-5" to="/dashboard/learn">Start in Learn<ArrowRight size={16}/></Link></>}</section>}
  {!practice&&<details open={!syllabus} className="v-card"><summary className="cursor-pointer font-medium">{professional?'Choose a capability':'Choose a subject'}</summary><form className="mt-5 grid gap-4" onSubmit={e=>{e.preventDefault();openOutline(selection);}}><label className="max-w-xl text-sm">{professional?'Skill or capability (optional)':'Subject (optional)'}<input className="v-field mt-2" maxLength={100} placeholder={professional?'For example, data interpretation':'For example, mathematics'} value={selection.subject} onChange={e=>setSelection({...selection,subject:e.target.value})}/></label><details className="max-w-xl"><summary className="cursor-pointer text-sm text-[#1967d2]">{professional?'Add goal and level':'Add board and class'}</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">{[[ 'board',professional?'Goal or industry (optional)':'Board (optional)' ],['classLevel',professional?'Level (optional)':'Class / level (optional)']].map(([key,label])=><label className="text-sm" key={key}>{label}<input className="v-field mt-2" maxLength={100} value={selection[key]} onChange={e=>setSelection({...selection,[key]:e.target.value})}/></label>)}</div></details><div className="flex flex-wrap gap-3"><button className="v-button primary" disabled={busy}>Open my outline<ArrowRight size={16}/></button><button className="v-button" type="button" disabled={busy} onClick={()=>openOutline(professional?PROFESSIONAL_SAMPLE_SELECTION:SAMPLE_SELECTION)}>Try authored {professional?'workplace':'learning'} sample</button></div></form><p className="v-muted mt-4">No {professional?'capability':'subject'} yet? A numbered provisional outline keeps your place until sourced content is available. Teaching responses require a connected model.</p></details>}
  {!practice&&syllabus&&<><section aria-label="Subject chapters">
    <h2 className="text-xl font-medium">{syllabus.subject}</h2>
    <p className="v-muted mt-2">{syllabus.status==='provisional'?'Provisional · The database has no matching outline yet. Your place and data-gap request are saved locally.':syllabus.status==='sample'?`${syllabus.chapters.length} authored sample ${syllabus.chapters.length===1?'activity':'activities'} · not official content coverage.`:syllabus.provenance?`Sourced from ${syllabus.provenance.provider} · version ${syllabus.provenance.version}.`:'Saved curriculum · source details unavailable.'}</p>
    {syllabus.status==='official'&&syllabus.contentLocale!==ctx.locale&&<p className="v-notice mt-3">The saved outline is in {languageNames[syllabus.contentLocale]||'another language'}. Teaching content in {languageNames[ctx.locale]} is shown only when it is actually available.</p>}
    <div className="mt-4 flex flex-wrap gap-3">{syllabus.chapters.map(c=><button className="v-button" aria-pressed={chapter?.id===c.id} disabled={busy} key={c.id} onClick={()=>openChapter(c)}><BookOpen size={17}/>{c.title}</button>)}</div>
   </section>
   {chapter&&<section className="v-card" aria-label={`${chapter.title} learning path`}>
    <p className="v-home-eyebrow">Chapter learning path</p><h2 className="mt-2 text-lg font-medium">{chapter.title}</h2>
    <p className="v-muted mt-2">{startedConcepts} of {chapterConcepts.length} concepts started. This counts activity, not mastery.</p>
    {nextConcept&&<button className="v-button primary mt-5" disabled={busy} onClick={()=>run(()=>openConcept(nextConcept.id))}>{saved.some(activity=>activity.conceptId===nextConcept.id)?'Continue':'Start'} {nextConcept.title}<ArrowRight size={16}/></button>}
    {chapter.status==='provisional'&&<form className="mt-5 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();run(async()=>{await getContentRepository(ctx).renameProvisional(chapter.id,rename);const next={...chapter,title:rename};setChapter(next);setSyllabus({...syllabus,chapters:syllabus.chapters.map(c=>c.id===next.id?next:c)});});}}><label className="min-w-0 flex-1 text-sm">Optional chapter name<input className="v-field mt-2" value={rename} maxLength={120} onChange={e=>setRename(e.target.value)}/></label><button className="v-button self-end" disabled={busy}>Save name</button></form>}
    {topics.map(t=><div key={t.id} className="mt-6"><h3 className="text-sm font-medium">{t.title}</h3>{t.concepts.map(c=><div className="v-list-row" key={c.id}><div><p className="text-sm" lang={c.locale||undefined}>{c.title}</p><p className="v-muted">{state.concepts.find(s=>s.conceptId===c.id)?.stage||'No evidence yet'} · {c.languageUnavailable?`Teaching content not loaded in ${languageNames[ctx.locale]}`:c.prerequisiteIds.length?`${c.prerequisiteIds.length} prerequisites`:'Starting concept'}</p></div><button className="v-button" disabled={busy} onClick={()=>run(()=>openConcept(c.id))}>{saved.some(activity=>activity.conceptId===c.id)?'Continue':'Open'}</button></div>)}</div>)}
   </section>}
  </>}
  <Link className="v-button self-start" to={practice?'/dashboard/practice?legacy=1':'/dashboard/learn?legacy=1'}>Open previous saved topics and examples</Link>
 </div>;
}
