import {learningProgressText} from '@/lib/learningProgressCopy';
import {useState} from 'react';
import {Link} from 'react-router-dom';
import {getLearningProgress} from '@/services/learningProgressService';
import LearnerGoals from '@/components/dashboard/LearnerGoals';

export default function LearningProgress({ctx,data}){
 const locale=data.preferences.interfaceLocale||'en';const t=key=>learningProgressText(locale,key);
 const [period,setPeriod]=useState(7);const [query,setQuery]=useState('');const [retry,setRetry]=useState(0);
 if(ctx.role==='parent')return <div className="v-page"><h1 className="v-title">Learning evidence belongs to a learning workspace</h1><p className="v-muted mt-3">This parent workspace shows only accepted child summaries. Add or switch to a learner role to review your own learning evidence.</p><Link className="v-button mt-4" to="/dashboard/reports">Open child reports</Link></div>;
 let report;try{report=getLearningProgress(ctx,period);}catch(error){return <div lang={locale} className="v-page"><h1 className="v-title">{t("title")}</h1><p className="v-notice v-error" role="alert"><span lang="en">{error.message}</span></p><button className="v-button" onClick={()=>setRetry(retry+1)}>{t("retry")}</button></div>;}
 const rows=report.objectives.filter(row=>row.title.toLowerCase().includes(query.trim().toLowerCase()));
 return <div lang={locale} className="v-page"><header><h1 className="v-title">{t("title")}</h1><p className="v-muted mt-2">{t("intro")}</p></header><div lang="en"><LearnerGoals ctx={ctx} resources={data.resources}/></div><section className="v-card"><h2 className="text-lg font-medium">{t("overTime")}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm">{t("period")}<select aria-label={t("period")} className="v-field mt-2" value={period} onChange={event=>setPeriod(event.target.value==='all'?'all':Number(event.target.value))}><option value={7}>{t("seven")}</option><option value={30}>{t("thirty")}</option><option value="all">{t("all")}</option></select></label><label className="text-sm">{t("find")}<input aria-label={t("find")} className="v-field mt-2" value={query} onChange={event=>setQuery(event.target.value)}/></label></div><p className="v-muted mt-4">{t("policy")}</p><p className="v-muted mt-2">{t("sources")}</p><p className="v-muted mt-2">{t("asOf")} <time dateTime={report.asOf}>{new Date(report.asOf).toLocaleString(locale)}</time> · {t("local")}</p></section>
 {report.unavailable.length>0&&<section className="v-notice v-error" role="alert"><h2 className="text-base font-medium">{t("unavailable")}</h2>{report.unavailable.map(item=><p className="mt-2 text-sm" key={item.source}><span lang="en">{item.source}: {item.message}</span></p>)}<button className="v-button mt-3" onClick={()=>setRetry(retry+1)}>{t("retry")}</button></section>}
 {rows.length?rows.map(row=><section className="v-card" key={row.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 lang={row.titleLocale||"en"} className="text-lg font-medium">{row.title}</h2><p className="v-muted mt-1">{row.source==='guided'?t('guided'):t('journey')}</p></div><span className="v-evidence">{t(row.stage)}</span></div><dl className="mt-4 grid gap-4 sm:grid-cols-3">{[[t('answers'),row.total?`${row.correct}/${row.total} ${t('correct')}`:t('unmeasured')],[t('applications'),String(row.applications)],[t('review'),row.dueAt?new Date(row.dueAt).toLocaleDateString(locale):t('unscheduled')]].map(([label,value])=><div key={label}><dt className="v-muted">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>)}</dl><p className="v-muted mt-3">{t("accuracy")}</p><details className="mt-5"><summary className="cursor-pointer text-sm font-medium">{t("timeline")} ({row.events.length})</summary><ol className="mt-3 space-y-3">{row.events.map(event=><li className="rounded-xl border p-3 text-sm" key={event.id}><p className="font-medium">{event.kind==='retrieval'?t('retrieval'):event.kind==='application'?t('application'):event.kind==='check'?t('check'):t('practice')}</p><p className="v-muted mt-1"><time dateTime={event.at}>{new Date(event.at).toLocaleString(locale)}</time> · {event.measured?`${event.correct}/${event.total} ${t('recordedCorrect')}`:t('unverified')}</p>{event.sourceVersion&&<p lang="en" className="v-muted mt-1 break-words">{event.sourceVersion}</p>}{event.resumePath&&<Link className="v-button mt-3" to={event.resumePath}>{t("open")}<span lang="en" className="sr-only">: {event.activityTitle}</span></Link>}</li>)}</ol></details></section>):<section className="v-card"><h2 className="text-lg font-medium">{query?t('noMatch'):report.unavailable.length?t('emptyAvailable'):report.hasSavedEvidence?t('emptyPeriod'):t('start')}</h2><p className="v-muted mt-3">{query?t('tryTitle'):report.hasSavedEvidence?t('retained'):t('noKnowledge')}</p>{(query||period!=='all')&&<button className="v-button mt-4" onClick={()=>{setQuery('');setPeriod('all');}}>{t("showAll")}</button>}<Link className="v-button mt-4 ml-2" to="/dashboard/learn">{t("choose")}</Link></section>}
 </div>;
}
