import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {useWorkspace} from '@/hooks/useWorkspace';
import {teacherLearners} from '@/services/classroomService';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';

export default function Learners(){
 const {ctx}=useWorkspace();const [search,setSearch]=useState('');const [selected,setSelected]=useState(null);
 const {data=[],isPending,error,refetch}=useQuery({queryKey:['workspace','learners',ctx?.personId,ctx?.workspaceId],enabled:!!ctx,queryFn:()=>teacherLearners(ctx)});
 const rows=data.filter(r=>(r.name+' '+r.id).toLowerCase().includes(search.toLowerCase()));const learner=data.find(r=>r.id===selected);
 return <div className="v-page"><header><h1 className="v-title">Learners</h1><p className="v-muted mt-2">Classwork evidence you can act on. Personal conversations and independent learning are not included.</p></header><label><span className="sr-only">Find a learner</span><input className="v-field max-w-md" placeholder="Find a learner" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 {isPending?<p role="status">Loading your class roster…</p>:error?<p className="v-notice v-error" role="alert">{error.message}<button className="v-button ml-3" onClick={()=>refetch()}>Retry</button></p>:rows.length?<section className="v-card">{rows.map(r=><button className="v-list-row w-full text-left" key={r.id} onClick={()=>setSelected(r.id)}><div className="min-w-0"><h2 className="text-base font-medium break-words">{r.name}</h2><p className="v-muted">{r.classes.map(c=>c.name).join(' · ')}{r.tier && <span className="ml-2 rounded-full bg-[#e8f0fd] px-2 py-0.5 text-[11px] font-medium text-[#0b57d2]">{r.tierLabel}</span>}</p></div><span className="v-evidence shrink-0">{r.pending?`${r.pending} to review`:`${r.submitted} submissions`}</span></button>)}</section>:<section className="v-card"><h2 className="text-lg font-medium">{search?'No matching learners':'Your class connections start here'}</h2><p className="v-muted mt-3">{search?'Try a name or email.':'Invite learners to a class. Their submitted work appears here once they connect.'}</p><Link className="v-button mt-5" to="/dashboard/classes">Open classes</Link></section>}
 <Dialog open={!!learner} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="max-h-[85dvh] overflow-y-auto sm:max-w-2xl"><DialogTitle>{learner?.name}</DialogTitle><DialogDescription>Only submissions to your classes. A score is not a mastery judgment.</DialogDescription>{learner?.evidence.length?learner.evidence.map(e=><article key={e.id} className="v-card"><h3 className="text-base font-medium">{e.title}</h3><p className="v-muted mt-2">{e.status==='graded'?`Returned · ${e.grade}/${e.total}`:'Waiting for review'}</p><p className="mt-4 whitespace-pre-wrap text-sm">{e.response}</p>{e.feedback&&<p className="v-notice mt-4">{e.feedback}</p>}<Link className="v-button mt-4" to={`/dashboard/class/${e.classId}`}>Review in class</Link></article>):<p className="v-muted">No submitted classwork yet. This is not evidence of low ability.</p>}</DialogContent></Dialog></div>;
}
