import {useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {familyGoalSummaries,familyProjectSummaries,familyReports} from '@/services/workspaceService';
import {getParentSummary} from '@/services/mentorStateService';
import {getParentStageInsight} from '@/services/stageTransitionService';
import ParentClassworkDigest from '@/components/dashboard/ParentClassworkDigest';
import {parentCopy} from '@/lib/parentCopy';
export default function ParentReport({ctx,locale='en'}){
 const t=parentCopy(locale);const [params,setParams]=useSearchParams();const [,setRetry]=useState(0);const requested=params.get('child')||'',days=params.get('period')==='30'?30:7;
 let rows=[],readError='';try{rows=familyReports(ctx,days);}catch(error){readError=error.message;}
 if(readError)return <div className="v-page" lang={locale}><h1 className="v-title">{t('Shared report unavailable')}</h1><p className="v-notice v-error mt-4" role="alert" lang="en">{readError}</p><div className="mt-4 flex flex-wrap gap-3"><button className="v-button" onClick={()=>setRetry(value=>value+1)}>{t('Retry report')}</button><Link className="v-button" to="/dashboard/connections">{t('Review connections')}</Link></div></div>;
 const report=requested?rows.find(row=>row.id===requested):rows[0];let learning=null,learningError='',projects=[],projectsError='',goals=[],goalsError='';
 if(report)try{learning=getParentSummary(ctx,report.id,days);}catch{learningError='Guided-learning evidence could not be read on this device. Other shared sections remain available.';}
 if(report)try{projects=familyProjectSummaries(ctx,report.id);}catch{projectsError='Shared project summaries could not be read on this device.';}
 if(report)try{goals=familyGoalSummaries(ctx,report.id);}catch{goalsError='Shared learning goals could not be read on this device.';}
 const select=(child,period)=>setParams({child,period:String(period)});
 return <div className="v-page" lang={locale}><header><h1 className="v-title">{t('Their learning, in context')}</h1><p className="v-muted mt-2">{t('Shared learning summaries, not private conversations. This local report is updated when you open it.')}</p></header>{rows.length>0&&<div className="grid max-w-2xl gap-4 sm:grid-cols-2"><label className="text-sm">{t('Child')}<select aria-label={t('Child')} className="v-field mt-2" value={report?.id||''} onChange={event=>select(event.target.value,days)}>{!report&&<option value="">{t('Choose an available child')}</option>}{rows.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label className="text-sm">{t('Report period')}<select aria-label={t('Report period')} className="v-field mt-2" value={days} onChange={event=>select(report?.id||'',Number(event.target.value))}><option value={7}>{t('Last {days} days',{days:7})}</option><option value={30}>{t('Last {days} days',{days:30})}</option></select></label></div>}{report?<>{(learningError||projectsError||goalsError)&&<div className="v-notice" role="status"><p>{t('Some shared sections are unavailable. Retry after checking this device’s records.')}</p><button className="v-button mt-3" onClick={()=>setRetry(value=>value+1)}>{t('Retry report')}</button></div>}<section className="v-card"><p className="v-muted">{t('Last {days} days',{days})} · {t('Source: active progress-summary sharing on this device')}</p><h2 className="mt-2 text-lg font-medium">{t('{name}’s overview',{name:report.name})}</h2><p className="mt-3 text-base leading-7">{t(report.summary)}</p><p className="v-muted mt-3">{t('{count} completed guided-learning activities. Completion shows participation; it does not establish mastery.',{count:report.completed})}</p><Link className="v-button primary mt-5" to={`/dashboard/ask?child=${encodeURIComponent(report.id)}&period=${days}`}>{t('Ask about this report')}</Link></section>
 <section className="v-card"><h2 className="text-lg font-medium">{t('Progress and retention')}</h2><p className="v-muted mt-2">{t('Recorded checks and review evidence in this period. No activity is not a score for ability.')}</p>{learningError&&<p className="v-notice mt-3" role="status">{t(learningError)}</p>}{learning&&<><p className="mt-4 text-sm">{t('{correct} of {total} recorded answers correct across {concepts} concepts.',{correct:learning.concepts.reduce((sum,concept)=>sum+concept.correct,0),total:learning.concepts.reduce((sum,concept)=>sum+concept.total,0),concepts:learning.concepts.length})}</p>{report.objectives.length?report.objectives.map((objective,index)=><div className="v-list-row" key={`${objective.title}-${index}`}><span className="text-sm" lang={ctx.locale}>{objective.title}</span><span className="v-evidence">{t(objective.stage)}</span></div>):<p className="v-muted mt-3">{t('No guided journey was updated in this period.')}</p>}<h3 className="mt-5 text-sm font-medium">{t('Shared observations')}</h3>{learning.observations.length?<ul className="mt-2 list-disc pl-5 text-sm" lang="en">{learning.observations.map(item=><li key={item.id}>{item.text}</li>)}</ul>:<p className="v-muted mt-2">{t('No retained observations were shared for this period.')}</p>}</>}</section>
 <section className="v-card"><h2 className="text-lg font-medium">{t('Applications and projects')}</h2><p className="mt-3 text-sm">{learning?t('{count} completed guided applications in this period.',{count:learning.completedApplications}):t('Application count is temporarily unavailable.')}</p><p className="v-muted mt-2">{t('Only summaries the learner explicitly shared with this parent appear below. They are fixed copies and may predate the selected activity period. Project documents, drafts and personal notes remain private.')}</p>{projectsError&&<p className="v-notice mt-3" role="status">{t(projectsError)}</p>}{projects.length?projects.map(project=><article className="v-list-row block" key={project.id}><h3 className="text-sm font-medium">{project.title}</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm">{project.summary}</p><p className="v-muted mt-2">{t('Shared')} {new Date(project.sharedAt).toLocaleDateString(locale)} · {t('saved project copy')}</p></article>):!projectsError&&<p className="v-muted mt-3">{t('No project summary has been explicitly shared with this parent.')}</p>}</section>
 <section className="v-card"><h2 className="text-lg font-medium">{t('Assigned work and teacher updates')}</h2><p className="v-muted mt-2">{t('Returned-work titles and upcoming due dates only. Answers, grades and private feedback are excluded.')}</p><ParentClassworkDigest ctx={ctx} childId={report.id} days={days} locale={locale}/></section>
 <section className="v-card"><h2 className="text-lg font-medium">{t('Goals and transitions')}</h2><ParentStageInsight ctx={ctx} childId={report.id} days={days} locale={locale}/><p className="v-muted mt-3">{t('The learner chooses which goal summaries to share. These fixed copies may predate the selected activity period; private notes stay with the learner.')}</p>{goalsError&&<p className="v-notice mt-3" role="status">{t(goalsError)}</p>}{goals.length?goals.map(goal=><article className="v-list-row block" key={goal.id}><h3 className="text-sm font-medium">{goal.title}</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm">{goal.summary}</p><p className="v-muted mt-2">{t('Shared')} {new Date(goal.sharedAt).toLocaleDateString(locale)} · {t('saved goal copy')}</p></article>):!goalsError&&<p className="v-muted mt-3">{t('No learner goal has been explicitly shared with this parent workspace. Ask the learner what they would like support with.')}</p>}</section></>:<section className="v-card" role={requested?'alert':undefined}><h2 className="text-lg font-medium">{t(requested?'This report is no longer shared':'Connect before viewing progress')}</h2><p className="v-muted mt-3">{t(requested?'The requested child is not available under your current permission. Choose an available child or review your connections.':'Reports appear only after the appropriate sharing permission is active.')}</p><Link className="v-button mt-5" to="/dashboard/connections">{t('Review connections')}</Link></section>}</div>;
}
function ParentStageInsight({ctx,childId,days,locale}){
 const t=parentCopy(locale);let insight;try{insight=getParentStageInsight(ctx,childId,days);}catch{return <p role="status" className="v-notice mt-4">{t('The recent class update is unavailable. The shared report remains available.')}</p>;}if(!insight)return <p className="v-muted mt-3">{t('No class transition was shared in this period.')}</p>;
 const label=value=>/^\d+$/.test(value)?t('Class {level}',{level:value}):value;const params={from:label(insight.from),to:label(insight.to)};const message=t(insight.state==='applied'?'Moved from {from} to {to}.':insight.state==='postponed'?'The move to {to} was postponed. Current class: {from}.':'The move to {to} was undone. Current class: {from}.',params);
 return <aside className="v-notice mt-4" aria-label={t('Recent class update')}><h3 className="text-sm font-semibold">{t('Recent class update')}</h3><p className="mt-1 text-sm">{message}</p><p className="v-muted mt-2">{t('Shared through this active progress connection. The learner controls their own stage and work.')}</p></aside>;
}
