import { useState } from "react";
import { Check, Crown, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { PRODUCT_ACCESS } from "@/lib/productAccess";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";

export default function Subscription() {
  const [details, setDetails] = useState(false);
  return <div className="mx-auto max-w-[1100px] space-y-7 p-5 sm:p-8">
    <header><h1 className="text-2xl font-medium">Plans & usage</h1><p className="mt-2 text-sm text-[#5f6368]">One intelligence for learning and building. Choose how you use it.</p></header>
    <section className="flex flex-wrap items-center gap-5 rounded-2xl border border-[#dadce0] p-6"><div className="rounded-2xl bg-[#e8f0fd] p-3 text-[#4285F4]"><Crown className="h-6 w-6" /></div><div className="flex-1"><p className="text-xs text-[#5f6368]">Your current plan</p><h2 className="mt-1 text-xl font-medium">{PRODUCT_ACCESS.plan}</h2><p className="mt-2 text-sm text-[#5f6368]">Local preview · No active subscription or payment method</p></div><Link to="/dashboard/home" className="rounded-full border border-[#dadce0] px-5 py-2.5 text-sm text-[#4285F4]">Back to workspace</Link></section>
    <section className="rounded-2xl border border-[#dadce0] p-6"><h2 className="text-base font-medium">Your usage</h2><p className="mt-3 text-sm leading-6 text-[#5f6368]">AI usage metering is not connected. No quota has been consumed or billed in this preview.</p><dl className="mt-5 grid gap-4 sm:grid-cols-3">{[["AI usage","Not connected"],["Billing period","No active billing"],["Next payment","None"]].map(([label,value]) => <div key={label} className="rounded-xl bg-[#ffffff] p-4"><dt className="text-xs text-[#5f6368]">{label}</dt><dd className="mt-2 text-sm font-medium">{value}</dd></div>)}</dl></section>
    <div className="grid gap-5 md:grid-cols-2">
      {[{name:"Free",label:"Current preview",description:"An accessible place to learn and build, supported by ads at launch.",features:["Personal learning and project workspace","Connect with classes, family, and organizations","Planned ad-supported access; limits to be confirmed"]},{name:"Premium",label:"Planned",description:"A focused, ad-free experience with expanded access to Visionary PA.",features:["Everything in Free","Planned ad-free learning and building","Usage allowances and pricing to be confirmed"]}].map(plan => <section key={plan.name} className={`flex flex-col rounded-2xl border p-6 ${plan.name === "Premium" ? "border-[#dadce0] bg-[#ffffff]" : "border-[#dadce0]"}`}><span className="self-start rounded-full bg-[#e8f0fd] px-3 py-1 text-xs text-[#4285F4]">{plan.label}</span><h2 className="mt-5 text-2xl font-medium">{plan.name}</h2><p className="mt-3 text-sm leading-6 text-[#5f6368]">{plan.description}</p><ul className="my-6 space-y-4">{plan.features.map(f => <li key={f} className="flex gap-3 text-sm leading-6 text-[#5f6368]"><Check className="mt-1 h-4 w-4 shrink-0 text-[#137333]" />{f}</li>)}</ul>{plan.name === "Free" ? <span className="mt-auto rounded-full border border-[#dadce0] px-5 py-2.5 text-center text-sm text-[#5f6368]">Current plan</span> : <button onClick={() => setDetails(true)} className="mt-auto rounded-full bg-[#4285F4] px-5 py-2.5 text-sm font-medium text-white">About Premium availability</button>}</section>)}
    </div>
    <p className="flex items-start gap-3 text-xs leading-6 text-[#5f6368]"><ShieldCheck className="mt-1 h-4 w-4 shrink-0" />Payment processing, verified entitlements, and ad delivery are not enabled. No purchase is made from this page. Ad placement and age-appropriate protections must be reviewed before launch.</p>
    <Dialog open={details} onOpenChange={setDetails}><DialogContent className="rounded-2xl sm:max-w-md"><DialogTitle>Premium isn’t available for purchase yet</DialogTitle><DialogDescription className="leading-6">We’ll show confirmed pricing, usage allowances, renewal terms, and secure checkout when billing is connected. For now, keep exploring the Free preview.</DialogDescription><button onClick={() => setDetails(false)} className="mt-3 rounded-full bg-[#4285F4] px-5 py-2.5 text-sm text-white">Got it</button></DialogContent></Dialog>
  </div>;
}

