import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Users, BookOpen, BarChart3, ArrowRight } from "lucide-react";
import { appClient } from "@/api/appClient";
import { useAuth } from "@/lib/AuthContext";
export default function OrgHome() {
  const { user } = useAuth();
  const { data, isPending, error, refetch } = useQuery({ queryKey: ["workspace","organization",user.email], queryFn: async () => {
    const [people,classes,curriculum] = await Promise.all([appClient.entities.OrganizationInvite.filter({organization_email:user.email}),appClient.entities.Classroom.filter({organization_email:user.email}),appClient.entities.OrganizationCurriculum.filter({organization_email:user.email})]);
    return { people: people.filter(p => p.status === "active"), pending: people.filter(p => p.status === "pending"), classes, curriculum: curriculum.filter(c => c.status !== "archived") };
  }});
  return <div className="mx-auto max-w-[1100px] space-y-6 p-5 sm:p-8"><header><p className="text-sm text-[#5f6368]">Organization workspace</p><h1 className="mt-2 text-2xl font-medium">{user.org_name || "Your organization"}</h1><p className="mt-2 text-sm leading-6 text-[#5f6368]">Connect people and support learning—without replacing their individual space.</p></header><section className="rounded-2xl border border-[#dce6f5] bg-[#f6f9ff] p-6"><h2 className="text-xl font-medium">A shared place to grow</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#5f6368]">Invite your teachers, learners, and parents. Membership begins when each person accepts. Connected teachers can attach classes to this organization.</p><Link to="/dashboard/people" className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#1967d2] px-5 py-2.5 text-sm text-white">Manage people<ArrowRight className="h-4 w-4" /></Link></section>{isPending ? <p role="status">Loading organization…</p> : error ? <p role="alert">Could not load organization. <button onClick={() => refetch()} className="underline">Retry</button></p> : <dl className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[[data.people.length,"Connected people"],[data.pending.length,"Pending requests"],[data.classes.length,"Linked classes"],[data.curriculum.length,"Curriculum drafts"]].map(([value,label]) => <div key={label} className="rounded-2xl border border-[#dadce0] p-5"><dd className="text-2xl font-medium">{value}</dd><dt className="mt-2 text-sm text-[#5f6368]">{label}</dt></div>)}</dl>}<div className="grid gap-4 sm:grid-cols-3">{[["people","People",Users,"Memberships and connection requests"],["curriculum","Curriculum",BookOpen,"Learning goals and shared framework drafts"],["analytics","Analytics",BarChart3,"Activity from explicitly linked classes"]].map(([path,label,Icon,desc]) => <Link key={path} to={"/dashboard/" + path} className="rounded-2xl border border-[#dadce0] p-6 hover:bg-[#f8fafd]"><Icon className="mb-4 h-6 w-6 text-[#1967d2]" /><h2 className="font-medium">{label}</h2><p className="mt-2 text-sm leading-6 text-[#5f6368]">{desc}</p></Link>)}</div></div>;
}

