import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { HeartHandshake, ArrowRight } from "lucide-react";
import { useAuth } from "@/lib/AuthContext";
import { appClient } from "@/api/appClient";
import FamilyProgress from "@/components/dashboard/FamilyProgress";
export default function ParentHome() {
  const { user } = useAuth();
  const { data: links = [], isPending, error, refetch } = useQuery({ queryKey: ["workspace","family",user.email], queryFn: () => appClient.entities.FamilyLink.filter({ parent_email: user.email }) });
  return <div className="mx-auto max-w-[1100px] space-y-6 p-5 sm:p-8"><header><h1 className="text-2xl font-medium">Hello, {user.full_name?.split(" ")[0] || "there"}</h1><p className="mt-2 text-sm text-[#5f6368]">Support their curiosity. Give them room to grow.</p></header><section className="flex flex-wrap items-center gap-5 rounded-2xl border border-[#dce6f5] bg-[#f6f9ff] p-6"><HeartHandshake className="h-9 w-9 text-[#1967d2]" /><div className="flex-1"><h2 className="text-xl font-medium">Learning is better with support</h2><p className="mt-2 text-sm leading-6 text-[#5f6368]">Follow the progress your child shares, without accessing private questions or project notes.</p></div><Link to="/dashboard/child" className="rounded-full bg-[#1967d2] px-5 py-2.5 text-sm text-white">Manage children</Link></section>{isPending ? <p role="status">Loading shared progress…</p> : error ? <p role="alert">Could not load connections. <button onClick={() => refetch()} className="underline">Retry</button></p> : links.some(l => l.status === "active") ? <FamilyProgress links={links} /> : <section className="rounded-2xl border border-dashed border-[#bdc1c6] p-8"><h2 className="text-lg font-medium">{links.some(l => l.status === "pending") ? "Waiting for your child to accept" : "Connect your child to see shared progress"}</h2><p className="mt-2 text-sm leading-6 text-[#5f6368]">Your child reviews your request in Connections. Learning activity appears here after acceptance.</p><Link to="/dashboard/child" className="mt-4 inline-flex items-center gap-2 text-sm text-[#1967d2]">View family connections<ArrowRight className="h-4 w-4" /></Link></section>}<div className="grid gap-4 sm:grid-cols-2">{[["/dashboard/connections","Connect with a teacher","Manage your learning relationships."],["/dashboard/learn","Your own learning matters too","Explore your interests in a personal learning space."]].map(([to,title,desc]) => <Link key={to} to={to} className="rounded-2xl border border-[#dadce0] p-6"><h2 className="font-medium">{title}</h2><p className="mt-2 text-sm text-[#5f6368]">{desc}</p></Link>)}</div></div>;
}

