import {getStageProfile} from './stageTransitionService.ts';
const fields=['board','classLevel','institution','stage','exam','subjectsText'];
function key(ctx){getStageProfile(ctx);return `visionary_stage_editor_v1:${ctx.workspaceId}`;}
export function readStageEditorDraft(ctx){const raw=localStorage.getItem(key(ctx));if(!raw)return null;try{const value=JSON.parse(raw);if(value.version!==1||value.personId!==ctx.personId||typeof value.base!=='string'||!value.fields||fields.some(field=>typeof value.fields[field]!=='string'||value.fields[field].length>(field==='subjectsText'?500:100)))throw Error();return value;}catch{throw Error('Saved stage edits could not be read. Their original bytes are retained.');}}
export const stageEditorRevision=value=>JSON.stringify(value||null);
export function saveStageEditorDraft(ctx,draft,base,expected){const storageKey=key(ctx),saved=readStageEditorDraft(ctx);if(stageEditorRevision(saved)!==expected)throw Error('Stage edits changed in another tab. Export your current edits or reload the saved draft.');const value={version:1,personId:ctx.personId,base,fields:Object.fromEntries(fields.map(field=>[field,String(draft[field]||'')]))};if(value.base.length>10000||fields.some(field=>value.fields[field].length>(field==='subjectsText'?500:100)))throw Error('Keep stage fields within their limits.');try{localStorage.setItem(storageKey,JSON.stringify(value));}catch{throw Error('Stage edits could not be backed up. Keep this form open and export your edits.');}return value;}
export function clearStageEditorDraft(ctx,expected){const storageKey=key(ctx),saved=readStageEditorDraft(ctx);if(stageEditorRevision(saved)!==expected)throw Error('Your stage was saved, but newer editor edits were retained. Reload before editing again.');try{localStorage.removeItem(storageKey);}catch{throw Error('Your stage was saved, but its draft could not be cleared.');}}

export function readStageEditorBackup(ctx){return localStorage.getItem(key(ctx))||'';}
