import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {appClient} from '@/api/appClient';
import {assignReviewedLesson} from '@/services/classroomService';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function AssignLesson({ctx,resource}){
 const [open,setOpen]=useState(false);const [classId,setClassId]=useState('');const [dueDate,setDueDate]=useState('');const [points,setPoints]=useState(10);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 const {data:classes=[],isPending,error}=useQuery({queryKey:['workspace','assign-classes',ctx.personId,ctx.workspaceId],enabled:open,queryFn:()=>appClient.entities.Classroom.list()});
 async function assign(){setBusy(true);try{await assignReviewedLesson(ctx,{resourceId:resource.id,classId,dueDate,points});setNotice('Assigned. A reviewed copy is now available to this class. Later lesson edits do not change this copy.');setOpen(false);}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 return <><button type="button" className="v-button" onClick={()=>{setNotice('');setOpen(true);}}>Assign reviewed lesson</button>{notice&&<p className="v-notice" role="status">{notice}</p>}<Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogContent><DialogTitle>Assign {resource.title}</DialogTitle><DialogDescription>Share a copy of this reviewed lesson with an enrolled class. No private preparation notes outside this lesson are shared.</DialogDescription>{isPending?<p role="status">Loading classes…</p>:error?<p role="alert">Could not load your classes.</p>:classes.length?<><label className="text-sm">Class<select className="v-field mt-2" value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Choose a class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm">Due date (optional)<input className="v-field mt-2" type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label className="text-sm">Points<input className="v-field mt-2" type="number" min="1" max="10000" value={points} onChange={e=>setPoints(Number(e.target.value))}/></label><button className="v-button primary" disabled={busy||!classId} onClick={assign}>{busy?'Assigning…':'Confirm assignment'}</button></>:<Link className="v-button" to="/dashboard/classes?create=1">Create your first class</Link>}{notice&&<p role="status">{notice}</p>}</DialogContent></Dialog></>;
}
