import {useState} from 'react';import {useQuery} from '@tanstack/react-query';import {Link} from 'react-router-dom';
import {useWorkspace} from '@/hooks/useWorkspace';import {getAssignedCurriculumOutline} from '@/services/assignedCurriculumOutline';
const stateLabel={submitted:'Submitted for teacher review',graded:'Returned by teacher',revision_requested:'Revision requested','not-submitted':'No submitted response',returned:'Returned by teacher'};
export default function AssignedCurriculumOutline({classId}){
 const {ctx,revision}=useWorkspace();const [query,setQuery]=useState('');const {data,error,isPending,refetch}=useQuery({queryKey:['assigned-outline',ctx?.personId,ctx?.workspaceId,classId,revision],enabled:!!ctx,queryFn:()=>getAssignedCurriculumOutline(ctx,classId)});
 if(isPending)return <section className="v-card" role="status">Reading assigned chapters and objectives…</section>;
 if(error)return <section className="v-card"><h2 className="text-lg font-medium">Assigned outline unavailable</h2><p role="alert" className="v-notice v-error mt-3">{error.message}</p><button className="v-button mt-3" onClick={()=>refetch()}>Retry assigned outline</button></section>;
 if(!data)return null;const chapters=data.chapters.map(chapter=>({...chapter,objectives:chapter.objectives.filter(row=>[row.title,row.assignmentTitle,chapter.title].some(title=>title.toLowerCase().includes(query.trim().toLowerCase())))})).filter(chapter=>chapter.objectives.length);const unmapped=data.unmapped.filter(row=>row.title.toLowerCase().includes(query.trim().toLowerCase()));
 return <section className="v-card"><h2 className="text-lg font-medium">Your assigned learning outline</h2><p className="v-muted mt-2">Only source copies your teacher actually assigned are shown. This is not the full book or a claim that unassigned chapters are complete. Source versions stay separate; response and teacher-feedback status are not knowledge scores.</p><label className="mt-4 block text-sm">Find an assigned chapter or objective<input aria-label="Find an assigned chapter or objective" className="v-field mt-2" value={query} onChange={event=>setQuery(event.target.value)}/></label>{data.unavailableCount>0&&<p className="v-notice mt-3" role="status">{data.unavailableCount} assigned source {data.unavailableCount===1?'copy is':'copies are'} unreadable. Original records are retained.<button className="v-button mt-2" onClick={()=>refetch()}>Retry assigned sources</button></p>}
 {chapters.map(chapter=><article className="mt-5 rounded-xl border p-4" key={chapter.id}><h3 className="text-base font-medium" lang={chapter.locale}>{chapter.title}</h3><p className="v-muted mt-2">{chapter.selection.subject} · {chapter.selection.classLevel} · {chapter.source.provider} · version {chapter.source.version}</p>{chapter.sourceSection&&<p className="v-muted mt-2">Source section: {chapter.sourceSection}</p>}<p className="v-muted mt-2">{chapter.status==='reviewed'?'Organization-reviewed copy':chapter.status==='sample'?'Authored sample':'Sourced curriculum'} · {chapter.locale}</p><ul className="mt-4 space-y-4">{chapter.objectives.map(row=><li className="border-t pt-3" key={row.assignmentId}><h4 className="font-medium" lang={chapter.locale}>{row.title}</h4><p className="v-muted mt-2">{row.assignmentTitle} · {stateLabel[row.state]||'Saved teacher status'} · Assignment: {row.assignmentState}</p>{!!row.prerequisites.length&&<p className="v-muted mt-2">Prerequisite guidance: {row.prerequisites.map(item=>item.title).join(' · ')}. Review with your teacher if needed.</p>}<div className="mt-3 flex flex-wrap gap-2"><Link className="v-button primary" aria-label={`Open assigned objective: ${row.title}`} to={row.href}>Open assigned objective<span className="sr-only">: {row.title}</span></Link><Link className="v-button" aria-label={`Ask about assigned source: ${row.title}`} to={row.askHref}>Ask about assigned source<span className="sr-only">: {row.title}</span></Link><Link className="v-button" aria-label={`Practice assigned source: ${row.title}`} to={row.practiceHref}>Practice assigned source<span className="sr-only">: {row.title}</span></Link></div></li>)}</ul></article>)}
 {!!unmapped.length&&<section className="mt-5"><h3 className="font-medium">Assignments without an attached objective</h3><p className="v-muted mt-2">Their instructions remain usable. No chapter or curriculum mapping has been assumed.</p>{unmapped.map(row=><Link className="v-button mt-3" key={row.id} to={row.href}>{row.title}</Link>)}</section>}{!chapters.length&&!unmapped.length&&<p className="v-muted mt-5">{query?'No matching assigned chapters or objectives.':data.assignedCount?'No readable attached objectives are available. Use Classwork to review the original assignment.':'No source objectives have been assigned yet. Your own learning remains available.'}</p>}{query&&<button className="v-button mt-3" onClick={()=>setQuery('')}>Clear outline search</button>}
 </section>;
}
