import {useState} from 'react';
import {Link} from 'react-router-dom';
import {getCurriculumBridge} from '@/services/curriculumBridgeService';

export default function CurriculumBridgePlan({ctx,transitionId}){
 const [plan,setPlan]=useState(null),[error,setError]=useState('');
 function load(){try{setPlan(getCurriculumBridge(ctx,transitionId));setError('');}catch(failure){setPlan(null);setError(failure.message);}}
 return <section className="mt-4"><button className="v-button" onClick={load}>{plan?'Refresh sourced bridge guidance':'Load available bridge guidance'}</button>{error&&<p role="alert" className="v-notice v-error mt-3">{error}</p>}{plan&&<div className="mt-4 space-y-4"><p className="v-muted">{plan.mappingCount} reviewed equivalent mappings. This plan preserves original evidence and review dates; it does not score or transfer mastery.</p>{plan.missingSubjects.length>0&&<p role="status" className="v-notice">Reviewed content in this teaching language is unavailable for: {plan.missingSubjects.join(', ')}. Load a sourced outline when it is available, then refresh this guidance.</p>}{!plan.canStart&&<p className="v-muted">New-stage activities are available after this stage change is active.</p>}
  {plan.rows.map(row=><div className="rounded-xl border border-slate-200 p-3" key={row.unitId}><h4 className="font-medium">{row.title}</h4><p className="mt-2 text-sm">{row.status==='equivalent'?`Reviewed equivalent: ${row.target.title}`:row.status==='current'?'Already in this curriculum':row.status==='archive'?'Archived from the new curriculum · resume anytime':'Mapping needs review'}</p><p className="v-muted mt-2">{row.reason}</p>{row.reviewedAt&&<p className="v-muted mt-2">Mapping reviewed {new Date(row.reviewedAt).toLocaleDateString()} · {row.source?.provider} · version {row.source?.version}</p>}<Link className="v-button mt-2" to={row.originalPath}>Resume original activity<span className="sr-only">: {row.title}</span></Link></div>)}
  {plan.targets.map(target=><div className="rounded-xl border border-slate-200 p-3" key={`${target.subject}:${target.id}`}><h4 className="font-medium">{target.title}</h4><p className="v-muted mt-2">{target.subject} · {target.source?.provider} · version {target.source?.version}</p>{target.prerequisites.length?<ul className="mt-3 list-disc space-y-2 pl-5">{target.prerequisites.map(item=><li key={item.id}>{item.title}: {item.priorReadiness?'Prior recorded readiness on a reviewed equivalent; no new assessment':item.available?'Review this sourced prerequisite before the objective':'Guidance unavailable; source review needed'}</li>)}</ul>:<p className="v-muted mt-2">No prerequisites declared by this source.</p>}{plan.canStart&&<Link className="v-button mt-3" to={target.path}>Explore sourced objective<span className="sr-only">: {target.title}</span></Link>}</div>)}
 </div>}</section>;
}
