import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft,ArrowRight,Maximize2,MessageCircle,RotateCcw,CheckCircle2 } from 'lucide-react';
import { getJourney } from '@/services/journeys';
import { answerQuestion,updateSession,saveArtifact,mastery,beginReview,snapshot } from '@/services/workspaceService';

const stages=['diagnosing','explaining','exploring','checking','practicing','building','reflecting','completed'];
export default function GuideActivity({ctx,session,onAsk,onFocus}){
 const [error,setError]=useState('');const [feedback,setFeedback]=useState(null);const [answer,setAnswer]=useState('');const [savedProject,setSavedProject]=useState(()=>snapshot(ctx).artifacts.some(a=>a.journeyId===session.journeyId));
 const journey=getJourney(session.journeyId,session.locale);const question=journey.questions[session.position];const stage=session.stage;const stageIndex=stages.indexOf(stage);const isQuestion=stage==='checking'||stage==='practicing';
 function update(patch){try{updateSession(ctx,session.id,patch);setError('');}catch(e){setError(e.message);}}
 function advance(){setFeedback(null);setAnswer('');if(stage==='checking'){update({stage:'practicing',position:0});return;}if(stage==='practicing'&&session.position<journey.questions.length-1){update({position:session.position+1});return;}update({stage:stages[Math.min(stageIndex+1,stages.length-1)],position:0});}
 function respond(){try{const result=answerQuestion(ctx,session.id,answer);setFeedback(result);}catch(e){setError(e.message);}}
 useEffect(()=>{setAnswer(session.answers[`${session.stage}:${session.position}:${session.reviewRound||0}`]||'');setFeedback(null);},[session.id,session.stage,session.position,session.reviewRound]);
 const stageLabels={diagnosing:'Start with what you know',explaining:'Understand the idea',exploring:'Explore it yourself',checking:'Check your understanding',practicing:'Make it stick',building:'Put it to work',reflecting:'Reflect and continue',completed:'A useful step forward',remediating:'Try a smaller step'};
 return <div className="flex min-w-0 flex-col gap-5">
  <div className="flex items-center justify-between gap-3"><span className="text-xs font-medium text-[#5f6368]">Learning activity · Demo content</span><button className="v-button !px-3" aria-label="Toggle activity focus" onClick={onFocus}><Maximize2 size={18}/></button></div>
  <div><h2 className="v-title" lang={session.locale}>{journey.title}</h2><p className="v-muted mt-2" lang={session.locale}>{journey.objective}</p></div>
  <div className="flex flex-wrap items-center gap-3"><label className="text-xs text-[#5f6368]">Teaching language<select aria-label="Activity language" className="v-field mt-1" value={session.locale} onChange={e=>update({locale:e.target.value})}><option value="en">English</option><option value="hi">हिन्दी</option><option value="bn">বাংলা</option></select></label><label className="text-xs text-[#5f6368]">Representation<select aria-label="Representation" className="v-field mt-1" value={session.representation} onChange={e=>update({representation:e.target.value})}><option value="interactive">Interactive</option><option value="text">Text alternative</option></select></label></div>
  <ol aria-label="Learning stages" className="flex flex-wrap gap-2">{stages.map((s,i)=><li key={s} aria-current={s===stage?'step':undefined} className={`rounded-full px-2.5 py-1 text-xs ${s===stage?'bg-blue-700 text-white':'bg-white text-[#5f6368]'}`}>{i+1}. {s=== 'diagnosing'?'Start':s[0].toUpperCase()+s.slice(1)}</li>)}</ol>
  {session.interrupted&&<div className="v-notice"><p>Your activity is paused while you ask. Your position and controls are saved.</p><button className="v-button mt-2" onClick={()=>update({interrupted:false})}>That makes sense · Resume</button></div>}
  <section className="v-card" lang={session.locale}><h3 className="mb-4 text-lg font-medium" lang="en">{stageLabels[stage]}</h3>
   {stage==='diagnosing'&&<><p className="v-muted">{journey.objective}</p><p className="mt-4 text-sm" lang="en">Think about an example you already know. You can begin without a diagnostic score.</p><button onClick={advance} className="v-button primary mt-5">Start exploring <ArrowRight size={16}/></button></>}
   {(stage==='explaining'||stage==='remediating')&&<><p className="whitespace-pre-wrap text-base leading-8">{journey.explanation}</p><p className="v-muted mt-5" lang="en">Read at your own pace. This text is also the accessible alternative to the visual activity.</p>{stage==='remediating'&&<button className="v-button mt-4" onClick={()=>update({stage:'checking'})}>Try the check again</button>}</>}
   {stage==='exploring'&&<><p className="v-muted mb-5">{journey.exploration}</p>{session.representation==='text'?<p className="text-base leading-8">{journey.explanation}</p>:session.journeyId==='cube'?<>
    <div className="cube-stage" role="img" aria-label={`Cube with side ${session.canvas.size}; volume ${session.canvas.size**3} cubic units`}><div className="learning-cube" aria-hidden="true" style={{transform:`rotateX(-18deg) rotateY(${session.canvas.rotation}deg) scale(${.6+session.canvas.size/10})`}}>{['translateZ(55px)','rotateY(180deg) translateZ(55px)','rotateY(90deg) translateZ(55px)','rotateY(-90deg) translateZ(55px)','rotateX(90deg) translateZ(55px)','rotateX(-90deg) translateZ(55px)'].map((transform,i)=><span key={transform} style={{transform}}>{i===0?session.canvas.size:''}</span>)}</div></div>
    <p className="my-4 text-center text-lg tabular-nums">V = {session.canvas.size} × {session.canvas.size} × {session.canvas.size} = <strong>{session.canvas.size**3}</strong></p><label className="block text-sm">Side length: {session.canvas.size}<input aria-label="Cube side length" className="mt-3 w-full" type="range" min="1" max="8" value={session.canvas.size} onChange={e=>update({canvas:{...session.canvas,size:Number(e.target.value)}})}/></label><label className="mt-4 block text-sm">Rotation<input aria-label="Cube rotation" className="mt-3 w-full" type="range" min="0" max="360" value={session.canvas.rotation} onChange={e=>update({canvas:{...session.canvas,rotation:Number(e.target.value)}})}/></label><button className="v-button mt-4" onClick={()=>update({canvas:{size:3,rotation:25}})}><RotateCcw size={16}/>Reset model</button>
   </>:session.journeyId==='fractions'?<><div aria-label={`${session.canvas.size} eighths selected`} className="my-8 flex h-16 overflow-hidden rounded-lg border border-blue-700">{Array.from({length:8},(_,i)=><div key={i} className={`flex-1 border-r border-blue-700 ${i<session.canvas.size?'bg-blue-500':'bg-white'}`}/>)}</div><label className="text-sm">{session.canvas.size}/8<input aria-label="Selected eighths" className="mt-4 w-full" type="range" min="0" max="8" value={session.canvas.size} onChange={e=>update({canvas:{...session.canvas,size:Number(e.target.value)}})}/></label><div className="mt-2 flex justify-between text-xs"><span>0</span><span>1/2 = 4/8</span><span>1</span></div></>:<table className="w-full text-left text-sm"><caption className="mb-3 text-left">Fictional three-week sample</caption><thead><tr><th className="py-3">Week</th><th>Completed tasks</th></tr></thead><tbody>{[20,30,25].map((n,i)=><tr key={i} className="border-t"><td className="py-3">{i+1}</td><td>{n}</td></tr>)}</tbody></table>}</>}
   {isQuestion&&question&&<><p className="mb-3 text-xs text-[#5f6368]">{session.position+1} / {journey.questions.length}</p><fieldset><legend className="mb-4 text-base font-medium leading-7">{question.prompt}</legend><div className="space-y-3">{question.options.map((option,i)=><label key={option} className="flex min-h-12 items-center gap-3 rounded-xl border p-3 text-sm"><input type="radio" name="activity-answer" value={i} checked={answer===String(i)} onChange={e=>{setAnswer(e.target.value);setFeedback(null);}}/>{option}</label>)}</div></fieldset><button className="v-button primary mt-5" disabled={!answer} onClick={respond}>Check my answer</button>{feedback&&<div className="v-notice mt-4" role="status"><p className="font-medium" lang="en">{feedback.correct?'That’s right.':'Let’s look at the reasoning.'}</p><p className="mt-2">{feedback.explanation}</p><button className="v-button mt-3" onClick={advance}>{feedback.correct?'Continue':'Continue with this explanation'}</button>{!feedback.correct&&<button className="v-button ml-2 mt-3" onClick={()=>{setFeedback(null);update({stage:'remediating'});}}>Review the idea</button>}</div>}</>}
   {stage==='building'&&<><h4 className="text-base font-medium">{journey.project}</h4><p className="v-muted mt-3">{journey.projectBrief}</p><button className="v-button primary mt-5" onClick={()=>{try{saveArtifact(ctx,{title:journey.project,body:journey.projectBrief,journeyId:journey.id});setSavedProject(true);}catch(e){setError(e.message);}}} disabled={savedProject}>{savedProject?'Project saved':'Create project draft'}</button>{savedProject&&<Link className="v-button ml-2 mt-3" to="/dashboard/build">Open Build</Link>}</>}
   {stage==='reflecting'&&<><label className="text-sm" lang="en">How confident do you feel? (Your own assessment)<select className="v-field mt-3" value={session.confidence??''} onChange={e=>update({confidence:Number(e.target.value)})}><option value="" disabled>Choose or skip</option><option value="25">I need more support</option><option value="50">I’m beginning to understand</option><option value="75">I can explain it</option><option value="100">I can apply it independently</option></select></label><p className="v-muted mt-4" lang="en">This self-report is separate from your answers. Review this idea again tomorrow to check what you remember.</p></>}
   {stage==='completed'&&<><CheckCircle2 className="mb-4 text-green-700"/><p className="text-base" lang="en">Activity completed. Evidence stage: <strong>{mastery(session.evidence,true)}</strong>.</p><p className="v-muted mt-3" lang="en">Completing a lesson is not the same as mastery. Varied application and delayed recall build stronger evidence.</p><Link className="v-button mt-5" to="/dashboard/progress">View evidence</Link><button className="v-button ml-2 mt-3" onClick={()=>{try{beginReview(ctx,session.id);}catch(e){setError(e.message);}}}>Start a new review</button></>}
  </section>
  {!isQuestion&&!['diagnosing','completed','remediating'].includes(stage)&&<div className="flex justify-between gap-3"><button className="v-button" onClick={()=>update({stage:stages[Math.max(0,stageIndex-1)]})}><ArrowLeft size={16}/>Back</button><button className="v-button primary" onClick={advance}>Continue <ArrowRight size={16}/></button></div>}
  <label className="text-sm">Your private notes<textarea className="v-field mt-2" rows={3} value={session.notes} onChange={e=>update({notes:e.target.value})} placeholder="Keep a thought, example, or question…"/></label>
  <div className="flex flex-wrap items-center justify-between gap-3"><button className="v-button" onClick={()=>{update({interrupted:true});onAsk();}}><MessageCircle size={16}/>Ask Visionary</button><span className="text-xs text-[#5f6368]">Saved on this device</span></div>{error&&<p role="alert" className="v-notice v-error">{error}</p>}
 </div>;
}
