import {useState} from 'react';
import {familyClassworkDigest} from '@/services/workspaceService';
import {parentCopy} from '@/lib/parentCopy';
export default function ParentClassworkDigest({ctx,childId,days=7,locale='en'}){
 const t=parentCopy(locale);const [,setRetry]=useState(0);let digest;
 const date=value=>{const parsed=new Date(value);return Number.isFinite(parsed.getTime())?parsed.toLocaleDateString(locale):value;};
 try{digest=familyClassworkDigest(ctx,childId,days);}catch{return <section className="mt-6 rounded-2xl border border-[#dadce0] p-4" role="status" lang={locale}><h3 className="text-base font-medium">{t('Classwork updates unavailable')}</h3><p className="v-muted mt-2">{t('The local classwork records could not be read or sharing changed. Reopen this report to try again.')}</p><button className="v-button mt-3" onClick={()=>setRetry(value=>value+1)}>{t('Retry report')}</button></section>;}
 return <section className="mt-6 rounded-2xl border border-[#dadce0] p-4" lang={locale} aria-label={t('Returned classwork')}><h3 className="text-base font-medium">{t('Returned classwork')}</h3><p className="v-muted mt-1">{t('Last {days} days',{days})} · {t('Shared progress summary from this device. Answers, grades and private teacher feedback are not included.')}</p>{digest.returned.length?<ul className="mt-3 divide-y divide-[#dadce0]">{digest.returned.map(item=><li key={item.id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span lang="en">{item.title}</span><span className="text-[#5f6368]">{t('Returned')} {date(item.date)}</span></li>)}</ul>:<p className="v-muted mt-3">{t('No classwork was returned in this period. This does not describe the learner’s ability.')}</p>}<h4 className="mt-5 border-t border-[#dadce0] pt-4 text-sm font-medium">{t('Due in the next 7 days')}</h4>{digest.upcoming.length?<ul className="mt-2 divide-y divide-[#dadce0]">{digest.upcoming.map(item=><li key={item.id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span lang="en">{item.title}</span><span className="text-[#5f6368]">{t('Due')} {date(item.dueDate)}</span></li>)}</ul>:<p className="v-muted mt-2">{t('No upcoming classwork due date is recorded for this learner’s active classes.')}</p>}</section>;
}
