import CurriculumBridgePlan from './CurriculumBridgePlan';
import {useState} from 'react';
import {Link} from 'react-router-dom';
import {getStageContinuity} from '@/services/stageTransitionService';

const label=profile=>[profile.stage,profile.classLevel?`Class ${profile.classLevel}`:'',profile.board,profile.institution,profile.exam].filter(Boolean).join(' · ')||'Not set';
export default function StageChangeDetails({ctx,transition}) {
 const [details,setDetails]=useState(null),[error,setError]=useState('');
 function load(){try{setDetails(getStageContinuity(ctx,transition.id));setError('');}catch(failure){setDetails(null);setError(failure.message);}}
 return <details className="mt-4" onToggle={event=>{if(event.currentTarget.open)load();}}><summary className="cursor-pointer font-medium">See what changed and your bridge plan</summary>
  {error?<div role="alert" className="v-notice v-error mt-3">{error}<button className="v-button mt-3" onClick={load}>Retry stage details</button></div>:details&&<div className="mt-4 space-y-5">
   <p className="v-muted">Trigger: {transition.trigger||'Legacy notice; trigger not recorded'}. {transition.boundaryReasons?.length?`Confirmation needed: ${transition.boundaryReasons.join(', ')}.`:transition.policy==='AUTO'?'Eligible change; no required confirmation.':'Confirmation required.'}</p><dl className="text-sm"><dt className="font-medium">Previous profile</dt><dd className="mt-1">{label(details.from)}</dd><dt className="mt-3 font-medium">Proposed profile</dt><dd className="mt-1">{label(details.to)}</dd></dl>
   <section><h3 className="font-medium">Subjects</h3>{[['kept','Kept in your profile'],['added','Added to your profile'],['removed','Removed from your active profile']].map(([key,title])=><p className="v-muted mt-2" key={key}>{title}: {details.subjects[key].join(', ')||'None'}</p>)}<p className="v-muted mt-2">Removing a subject from your profile keeps its saved activities available below.</p></section>
   <section><h3 className="font-medium">Bridge plan</h3><p className="v-muted mt-2">Your stage profile changes separately from curriculum approval. Use the sourced guidance below to check available mappings. Saved results have not been relabelled as new-stage mastery.</p>{details.subjects.added.length>0&&<ul className="mt-3 list-disc space-y-2 pl-5">{details.subjects.added.map(subject=><li key={subject}>Find reviewed content and prerequisite guidance for {subject} before starting its new-stage work.</li>)}</ul>}<p className="v-muted mt-3">Continue saved activities at their exact position while the new mapping is unavailable. Review any due practice on its original source; your due dates are unchanged.</p><Link className="v-button mt-3" to="/dashboard/learn">Open learning outline</Link><CurriculumBridgePlan ctx={ctx} transitionId={transition.id}/></section>
   <section><h3 className="font-medium">Saved learning · resume anytime</h3><p className="v-muted mt-2">{details.sourceSelection?`Current saved outline: ${details.sourceSelection.board} · ${details.sourceSelection.classLevel} · ${details.sourceSelection.subject}.`:'No saved outline yet.'} Individual activities may use earlier sources.</p>{details.activities.length?details.activities.map(item=><div className="mt-3 rounded-xl border border-slate-200 p-3" key={item.id}><p className="font-medium" lang={item.locale}>{item.title}</p><p className="v-muted mt-1">Saved step: {item.stage}{item.dueAt?` · Review due ${new Date(item.dueAt).toLocaleDateString()}`:''}</p><Link className="v-button mt-2" to={item.path}>Resume saved activity<span className="sr-only">: {item.title}</span></Link></div>):<p className="v-muted mt-3">No learning activities have been saved yet.</p>}</section>
   <section><h3 className="font-medium">Open classwork</h3><p className="v-muted mt-2">Assigned content stays with its original class copy and deadline.</p>{details.classwork.length?details.classwork.map(item=><div className="mt-3" key={item.id}><p>{item.title} · {item.className}{item.dueAt?` · Due ${new Date(item.dueAt).toLocaleDateString()}`:''}</p><Link className="v-button mt-2" to={item.path}>Open assigned copy<span className="sr-only">: {item.title}</span></Link></div>):<p className="v-muted mt-3">No open classwork in this workspace.</p>}</section>
   <p className="v-muted">Preferences, private notes and saved projects are retained. This preview does not generate new curriculum or notify anyone outside existing sharing permissions.</p><button className="v-button" onClick={load}>Refresh stage details</button>
  </div>}
 </details>;
}
