import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/lib/AuthContext';
import { roleNames } from '@/services/workspaceService';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
export default function WorkspaceSwitcher(){
 const {workspaces,activeWorkspace,switchWorkspace,addRole,person,setAgeBand}=useAuth();const navigate=useNavigate();const [open,setOpen]=useState(false);const [role,setRole]=useState('teacher');const [adult,setAdult]=useState(false);const [error,setError]=useState('');
 const availableRoles=person?.ageBand==='minor'?[]:Object.keys(roleNames).filter(key=>!workspaces.some(w=>w.role===key));
 // The switcher only makes sense when more than one workspace exists (class, organization or extra role connections); with a single workspace it would be an arrow that leads nowhere.
 if(workspaces.length<=1)return null;
 function change(value){if(value==='add'){setRole(availableRoles[0]);setError('');setOpen(true);return;}try{switchWorkspace(value);navigate(workspaces.find(w=>w.id===value)?.lastPath||'/dashboard/home');}catch(e){setError(e.message);}}
 return <><label className="workspace-switcher min-w-0 max-w-[160px] text-xs"><span className="sr-only">Active workspace</span><select aria-label="Active workspace" value={activeWorkspace?.id||''} onChange={e=>change(e.target.value)} className="h-11 w-full cursor-pointer truncate rounded-full border border-transparent bg-[#f6f8fc] px-3 text-sm text-[#121317] hover:bg-[#e8f0fd]">{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}{availableRoles.length>0&&<option value="add">+ Add a role</option>}</select></label><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>Add a workspace role</DialogTitle><DialogDescription>Keep one account. Your conversations and drafts remain separate in each workspace. This does not grant access to an existing institution.</DialogDescription><label className="text-sm">Role<select className="v-field mt-2" value={role} onChange={e=>setRole(e.target.value)}>{Object.entries(roleNames).filter(([key])=>!workspaces.some(w=>w.role===key)).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{person?.ageBand!=='adult'&&<label className="flex gap-3 text-sm"><input type="checkbox" checked={adult} onChange={e=>setAdult(e.target.checked)}/>I am 18 or older. This preview does not verify identity.</label>}{error&&<p role="alert" className="v-notice v-error">{error}</p>}<button className="v-button primary" onClick={()=>{try{if(adult)setAgeBand('adult');addRole(role);setOpen(false);navigate('/dashboard/home');}catch(e){setError(e.message);}}}>Add role</button></DialogContent></Dialog></>;
}
